# Generated by Django 5.2 on 2026-01-09 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="When this record was created (UTC for system-wide data)",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="When this record was last updated (UTC for system-wide data)",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="usermanagementsettings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="When this record was created (UTC for system-wide data)",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="usermanagementsettings",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="usermanagementsettings",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="When this record was last updated (UTC for system-wide data)",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="When this record was created (UTC for system-wide data)",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="When this record was last updated (UTC for system-wide data)",
                verbose_name="Updated At",
            ),
        ),
    ]
