# Generated by Django 5.2 on 2025-12-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_cropping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="email_domain",
        ),
        migrations.AddField(
            model_name="school",
            name="database_alias",
            field=models.CharField(
                default="atepi_palabek",
                help_text="Database key e.g. atepi_palabek",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="school",
            name="domain",
            field=models.CharField(
                help_text="Email domain e.g. atepi.palabek.sch",
                max_length=191,
                unique=True,
            ),
        ),
    ]
