# Generated by Django 5.2 on 2025-12-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_school_email_domain_school_database_alias_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name_of_person_in_charge",
        ),
    ]
