# Generated by Django 5.2 on 2025-12-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprofile_name_of_person_in_charge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="cropping",
        ),
    ]
