# Generated by Django 5.2 on 2026-04-01 19:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_specialaccountmappings_petty_cash_account_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="expense",
            name="finance_exp_academi_32f090_idx",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="academic_session",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="auto_create_journal_entry",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="processing_fee_amount",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="vendor_contact",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="vendor_name",
        ),
        migrations.RemoveField(
            model_name="expenseline",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="expenseline",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="expenseline",
            name="tax_rate",
        ),
        migrations.RemoveField(
            model_name="expensepayment",
            name="auto_create_journal_entry",
        ),
        migrations.AddField(
            model_name="expense",
            name="payee_contact",
            field=models.CharField(
                blank=True,
                help_text="Phone or email — optional",
                max_length=100,
                verbose_name="Payee Contact",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payee_name",
            field=models.CharField(
                blank=True,
                help_text="Supplier name, staff member name, or leave blank for petty cash",
                max_length=200,
                verbose_name="Payee Name",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPPLIER", "Supplier / Vendor"),
                    ("STAFF", "Staff Member"),
                    ("PETTY", "Petty Cash"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="SUPPLIER",
                max_length=10,
                verbose_name="Payee Type",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="approved_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Approved By ID"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="budget_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Budget line this expense is charged against",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="finance.budgetline",
                verbose_name="Budget Line",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="budget_override_reason",
            field=models.TextField(
                blank=True,
                help_text="Required if expense exceeds budget limit",
                verbose_name="Budget Override Reason",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                help_text="All line items belong to this category",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="finance.expensecategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.CharField(
                help_text="One-line title e.g. 'Electricity bill — January'",
                max_length=255,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Header-level GL account — auto-assigned from category. Ignored when line items exist (per-line accounts take over).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="charged_expenses",
                to="finance.account",
                verbose_name="Expense Account",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(
                db_index=True,
                help_text="Auto-set to school today by signal if not supplied",
                verbose_name="Expense Date",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_number",
            field=models.CharField(
                db_index=True,
                help_text="Auto-generated by signal on save",
                max_length=50,
                unique=True,
                verbose_name="Expense Number",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="fiscal_period",
            field=models.ForeignKey(
                help_text="Auto-set to current open period by signal if not supplied",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="core.fiscalperiod",
                verbose_name="Fiscal Period",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Journal entry created automatically when expense is approved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="finance.journalentry",
                verbose_name="Journal Entry",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Free-text context for the whole expense — verbal approvals, delivery notes, references, etc.",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="preferred_payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_expenses",
                to="core.paymentmethod",
                verbose_name="Preferred Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="rejected_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Rejected By ID"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Rejection Reason"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="requested_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Requested By ID"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of all line amounts — updated by ExpenseLine signal",
                max_digits=12,
                verbose_name="Subtotal Amount",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Optional header-level tax — entered manually by accountant",
                max_digits=12,
                verbose_name="Tax Amount",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="subtotal_amount + tax_amount — updated by ExpenseLine signal",
                max_digits=12,
                verbose_name="Total Amount",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="vendor_reference",
            field=models.CharField(
                blank=True,
                help_text="Supplier invoice number or receipt reference — optional",
                max_length=100,
                verbose_name="Vendor Invoice / Reference",
            ),
        ),
        migrations.AlterField(
            model_name="expenseline",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="quantity × unit_price — set by form clean() and signal, not user-entered",
                max_digits=12,
                verbose_name="Line Amount",
            ),
        ),
        migrations.AlterField(
            model_name="expenseline",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional — omit when qty, unit price and account are self-explanatory",
                max_length=255,
                verbose_name="Line Description",
            ),
        ),
        migrations.AlterField(
            model_name="expenseline",
            name="expense_account",
            field=models.ForeignKey(
                help_text="Per-line GL account — overrides Expense.expense_account when lines exist",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expense_lines",
                to="finance.account",
                verbose_name="Expense Account",
            ),
        ),
        migrations.AlterField(
            model_name="expenseline",
            name="unit_of_measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.unitofmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["payee_type"], name="finance_exp_payee_t_4ab8fa_idx"
            ),
        ),
    ]
