# Generated by Django 5.2 on 2026-04-04 05:22

import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_specialaccountmappings_petty_cash_account_and_more"),
        ("finance", "0002_remove_expense_finance_exp_academi_32f090_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenseline",
            name="expense_account",
        ),
        migrations.AlterField(
            model_name="expenseline",
            name="description",
            field=models.CharField(
                help_text="What was purchased — e.g. 'Box of chalk', 'Boda fare to market'",
                max_length=255,
                verbose_name="Line Description",
            ),
        ),
        migrations.AlterField(
            model_name="expenseline",
            name="unit_of_measure",
            field=models.ForeignKey(
                default=finance.models.get_default_uom,
                help_text="Unit for the quantity — e.g. box, ream, hour, day, trip",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.unitofmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
    ]
