# Generated by Django 5.2 on 2025-12-30 10:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "year_name",
                    models.CharField(
                        help_text="E.g., '2024', '2024-2025', '2024/2025'",
                        max_length=20,
                        verbose_name="Academic Year",
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Position of this period within the year (1, 2, 3, etc.)",
                        verbose_name="Period Number",
                    ),
                ),
                (
                    "term_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to auto-generate from school configuration. Provide custom name for special sessions (e.g., 'December Holiday Program').",
                        max_length=50,
                        verbose_name="Period Name",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("term", "Term"),
                            ("semester", "Semester"),
                            ("quarter", "Quarter"),
                            ("trimester", "Trimester"),
                            ("module", "Module"),
                            ("block", "Block"),
                            ("yearlong", "Year-long"),
                            ("intensive", "Intensive"),
                            ("holiday_program", "Holiday Program"),
                            ("remedial", "Remedial Program"),
                            ("summer_school", "Summer School"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        help_text="Leave blank to auto-set from school configuration. Select manually for special sessions.",
                        max_length=20,
                        verbose_name="Period Type",
                    ),
                ),
                (
                    "is_special_session",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Check this for holiday programs, summer school, remedial classes, or other sessions outside the regular term structure. This allows you to customize the period type and name.",
                        verbose_name="Is Special Session",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="When classes begin for this session",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True,
                        help_text="When classes end for this session",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the current active session",
                        verbose_name="Is Current Session",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this session is active for enrollment and activities",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_academically_closed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Academic activities frozen - grades locked, reports final, no enrollment changes",
                        verbose_name="Academically Closed",
                    ),
                ),
                (
                    "academic_closure_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this session was academically closed",
                        null=True,
                        verbose_name="Academic Closure Date",
                    ),
                ),
                (
                    "closed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of user who closed this session",
                        max_length=100,
                        null=True,
                        verbose_name="Closed By User ID",
                    ),
                ),
                (
                    "allows_promotion",
                    models.BooleanField(
                        default=False,
                        help_text="Whether students can be promoted at the end of this period",
                        verbose_name="Allows Promotion",
                    ),
                ),
                (
                    "promotion_done",
                    models.BooleanField(
                        default=False,
                        help_text="Whether student promotion has been completed",
                        verbose_name="Promotion Completed",
                    ),
                ),
                (
                    "enrollment_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Last date for student enrollment",
                        null=True,
                        verbose_name="Enrollment Deadline",
                    ),
                ),
                (
                    "late_enrollment_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether students can enroll after deadline",
                        verbose_name="Late Enrollment Allowed",
                    ),
                ),
                (
                    "minimum_attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=75.0,
                        help_text="Minimum attendance required for this session",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Minimum Attendance %",
                    ),
                ),
                (
                    "registration_fee_required",
                    models.BooleanField(
                        default=True,
                        help_text="DEPRECATED: Use FiscalPeriod settings instead",
                        verbose_name="Registration Fee Required",
                    ),
                ),
                (
                    "late_payment_penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="DEPRECATED: Use FiscalPeriod settings instead",
                        max_digits=5,
                        verbose_name="Late Payment Penalty Rate",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this session",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
                "ordering": ["-start_date", "term_number"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="E.g., A, B, C (leave blank if no sections)",
                        max_length=10,
                        null=True,
                        verbose_name="Section",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Maximum Students"
                    ),
                ),
                (
                    "class_schedule",
                    models.TextField(blank=True, verbose_name="Class Schedule"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End Time"),
                ),
                (
                    "class_motto",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Class Motto"
                    ),
                ),
                (
                    "class_colors",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Class Colors"
                    ),
                ),
                (
                    "class_average_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current class average performance score",
                        max_digits=5,
                        null=True,
                        verbose_name="Class Average Score",
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Class attendance rate percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Attendance Rate",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["academic_level__order", "section"],
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Room Name")),
                (
                    "room_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Room Number"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Building"
                    ),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="Floor"),
                ),
                (
                    "wing",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Wing/Section"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=0, verbose_name="Capacity"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Classroom"),
                            ("LABORATORY", "Laboratory"),
                            ("COMPUTER_LAB", "Computer Laboratory"),
                            ("LIBRARY", "Library"),
                            ("AUDITORIUM", "Auditorium"),
                            ("GYMNASIUM", "Gymnasium"),
                            ("WORKSHOP", "Workshop"),
                            ("CONFERENCE", "Conference Room"),
                            ("MUSIC_ROOM", "Music Room"),
                            ("ART_ROOM", "Art Room"),
                            ("SCIENCE_LAB", "Science Laboratory"),
                            ("LANGUAGE_LAB", "Language Laboratory"),
                            ("EXAMINATION_HALL", "Examination Hall"),
                        ],
                        default="REGULAR",
                        max_length=20,
                        verbose_name="Room Type",
                    ),
                ),
                (
                    "has_projector",
                    models.BooleanField(default=False, verbose_name="Has Projector"),
                ),
                (
                    "has_computer",
                    models.BooleanField(default=False, verbose_name="Has Computer"),
                ),
                (
                    "has_air_conditioning",
                    models.BooleanField(
                        default=False, verbose_name="Has Air Conditioning"
                    ),
                ),
                (
                    "has_whiteboard",
                    models.BooleanField(default=True, verbose_name="Has Whiteboard"),
                ),
                (
                    "has_blackboard",
                    models.BooleanField(default=True, verbose_name="Has Blackboard"),
                ),
                (
                    "has_smart_board",
                    models.BooleanField(default=False, verbose_name="Has Smart Board"),
                ),
                (
                    "has_internet",
                    models.BooleanField(
                        default=False, verbose_name="Has Internet Access"
                    ),
                ),
                (
                    "has_sound_system",
                    models.BooleanField(default=False, verbose_name="Has Sound System"),
                ),
                (
                    "specialized_equipment",
                    models.TextField(
                        blank=True,
                        help_text="List of specialized equipment available in this room",
                        verbose_name="Specialized Equipment",
                    ),
                ),
                (
                    "is_accessible",
                    models.BooleanField(default=True, verbose_name="Is Accessible"),
                ),
                (
                    "accessibility_features",
                    models.TextField(
                        blank=True,
                        help_text="Specific accessibility features available",
                        verbose_name="Accessibility Features",
                    ),
                ),
                (
                    "is_bookable",
                    models.BooleanField(default=True, verbose_name="Is Bookable"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires Approval"
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Maintenance Date"
                    ),
                ),
                (
                    "safety_inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Safety Inspection Date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Classroom",
                "verbose_name_plural": "Classrooms",
                "ordering": ["building", "floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="Is Optional"),
                ),
                (
                    "hours_per_week",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Hours Per Week"
                    ),
                ),
                (
                    "total_hours",
                    models.PositiveIntegerField(default=0, verbose_name="Total Hours"),
                ),
                (
                    "schedule_days",
                    models.JSONField(
                        blank=True,
                        help_text="Days of the week when this subject is taught",
                        null=True,
                        verbose_name="Schedule Days",
                    ),
                ),
                (
                    "preferred_periods",
                    models.JSONField(
                        blank=True,
                        help_text="Preferred time periods for this subject",
                        null=True,
                        verbose_name="Preferred Periods",
                    ),
                ),
                ("syllabus", models.TextField(blank=True, verbose_name="Syllabus")),
                (
                    "learning_objectives",
                    models.TextField(blank=True, verbose_name="Learning Objectives"),
                ),
                (
                    "assessment_criteria",
                    models.TextField(blank=True, verbose_name="Assessment Criteria"),
                ),
                (
                    "continuous_assessment_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="Percentage weight of continuous assessment",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Continuous Assessment Weight",
                    ),
                ),
                (
                    "final_exam_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=60.0,
                        help_text="Percentage weight of final examination",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Final Exam Weight",
                    ),
                ),
                (
                    "textbook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Textbook"
                    ),
                ),
                (
                    "reference_materials",
                    models.TextField(blank=True, verbose_name="Reference Materials"),
                ),
                (
                    "required_equipment",
                    models.TextField(blank=True, verbose_name="Required Equipment"),
                ),
                (
                    "class_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current class average for this subject",
                        max_digits=5,
                        null=True,
                        verbose_name="Class Average",
                    ),
                ),
                (
                    "pass_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of students passing this subject",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pass Rate",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Class Subject",
                "verbose_name_plural": "Class Subjects",
                "ordering": ["class_instance", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., 'Easter Monday', 'Mid-Term Break', 'Independence Day'",
                        max_length=200,
                        verbose_name="Holiday Name",
                    ),
                ),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public Holiday"),
                            ("SCHOOL_BREAK", "School Break"),
                            ("SCHOOL_EVENT", "School Event"),
                            ("RELIGIOUS", "Religious Holiday"),
                            ("PROFESSIONAL", "Professional Day"),
                            ("EXAMINATION", "Examination Period"),
                            ("CUSTOM", "Custom Holiday"),
                        ],
                        db_index=True,
                        default="PUBLIC",
                        max_length=20,
                        verbose_name="Holiday Type",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="First day of holiday",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Last day of holiday (leave blank for single-day holidays)",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "is_school_closed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether school is completely closed",
                        verbose_name="School Closed",
                    ),
                ),
                (
                    "is_partial_closure",
                    models.BooleanField(
                        default=False,
                        help_text="School open but limited activities (e.g., exams only)",
                        verbose_name="Partial Closure",
                    ),
                ),
                (
                    "affects_attendance",
                    models.BooleanField(
                        default=True,
                        help_text="Whether absence on this day affects attendance records",
                        verbose_name="Affects Attendance",
                    ),
                ),
                (
                    "affects_payroll",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a paid holiday for staff",
                        verbose_name="Affects Payroll",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this holiday repeats annually",
                        verbose_name="Is Recurring",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FF0000",
                        help_text="Hex color for calendar display (e.g., #FF0000)",
                        max_length=7,
                        verbose_name="Calendar Color",
                    ),
                ),
                (
                    "notify_parents",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification to parents about this holiday",
                        verbose_name="Notify Parents",
                    ),
                ),
                (
                    "notify_staff",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification to staff about this holiday",
                        verbose_name="Notify Staff",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about this holiday",
                        verbose_name="Description",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes (not visible to parents/students)",
                        verbose_name="Internal Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentClassEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "auto_create_invoice",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create invoice when enrollment is finalized",
                        verbose_name="Auto-Create Invoice",
                    ),
                ),
                ("enrollment_date", models.DateField(verbose_name="Enrollment Date")),
                (
                    "roll_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Roll Number"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "enrollment_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Admission"),
                            ("CONTINUING", "Continuing Student"),
                            ("TRANSFER_IN", "Transfer from Another School"),
                            ("REPEATER", "Repeating Class"),
                            ("READMISSION", "Readmitted Student"),
                            ("PROMOTED", "Promoted from Previous Level"),
                            ("TRANSFERRED", "Transferred Between Classes"),
                            ("REPEATED", "Repeated Current Level"),
                            ("INTERNAL_TRANSFER", "Internal Class Transfer"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Enrollment Type",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped Out"),
                            ("TRANSFERRED", "Transferred"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ONGOING",
                        max_length=20,
                        verbose_name="Completion Status",
                    ),
                ),
                (
                    "enrollment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this enrollment",
                        verbose_name="Enrollment Notes",
                    ),
                ),
                (
                    "progression_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal Progression"),
                            ("SKIP", "Level Skipped"),
                            ("REPEAT", "Level Repeated"),
                            ("LATERAL", "Lateral Transfer"),
                            ("READMISSION", "Readmission"),
                        ],
                        default="NORMAL",
                        help_text="Type of academic progression this enrollment represents",
                        max_length=20,
                        verbose_name="Progression Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Class Enrollment",
                "verbose_name_plural": "Student Class Enrollments",
                "ordering": ["class_instance", "roll_number", "student__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Subject Name")),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="Short form for display purposes (e.g., MATH, ENG, SCI)",
                        max_length=10,
                        unique=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Subject Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("MATH", "Mathematics"),
                            ("LANG_ARTS", "Language Arts"),
                            ("SCIENCES", "Sciences"),
                            ("SOCIAL", "Social Studies"),
                            ("LITERACY", "Literacy"),
                            ("NUMERACY", "Numeracy"),
                            ("SCIENCE_ENV", "Environmental Education"),
                            ("RELIGION", "Religious & Moral Education"),
                            ("CREATIVE", "Creative Arts & Life Skills"),
                            ("MOTHER_TONGUE", "Mother Tongue"),
                            ("FOREIGN_LANG", "Foreign Language"),
                            ("ARTS_CRAFTS", "Arts and Crafts"),
                            ("MUSIC", "Music"),
                            ("PE", "Physical Education"),
                            ("RELIGIOUS", "Religious Studies"),
                            ("COMPUTER", "Computer Studies"),
                            ("LIFE_SKILLS", "Life Skills"),
                            ("TECHNICAL", "Technical Subjects"),
                            ("BUSINESS", "Business Studies"),
                            ("AGRICULTURE", "Agriculture"),
                            ("HOME_ECON", "Home Economics"),
                            ("EXTRA", "Extracurricular Activities"),
                            ("CLUBS", "Clubs and Societies"),
                            ("GUIDANCE", "Guidance & Counselling"),
                            ("OTHER", "Other / Miscellaneous"),
                        ],
                        default="SCIENCES",
                        max_length=20,
                        verbose_name="Subject Type",
                    ),
                ),
                (
                    "credit_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="Credit Hours",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_compulsory",
                    models.BooleanField(default=True, verbose_name="Is Compulsory"),
                ),
                (
                    "pass_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pass Mark",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="INTERMEDIATE",
                        max_length=20,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "weight_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for GPA calculation (1.0 = normal weight)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(3.0),
                        ],
                        verbose_name="Weight Factor",
                    ),
                ),
                (
                    "textbook_required",
                    models.BooleanField(default=True, verbose_name="Textbook Required"),
                ),
                (
                    "recommended_textbooks",
                    models.TextField(blank=True, verbose_name="Recommended Textbooks"),
                ),
                (
                    "required_materials",
                    models.TextField(blank=True, verbose_name="Required Materials"),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["subject_type", "abbreviation"],
            },
        ),
        migrations.CreateModel(
            name="AcademicLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Level Name")),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Level Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="For ordering levels", verbose_name="Order"
                    ),
                ),
                (
                    "has_sections",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this level has multiple sections/streams (A, B, C, etc.)",
                        verbose_name="Has Sections/Streams",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_graduation_level",
                    models.BooleanField(
                        default=False,
                        help_text="Whether completing this level constitutes graduation",
                        verbose_name="Is Graduation Level",
                    ),
                ),
                (
                    "next_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="The level students progress to after completing this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_levels",
                        to="academics.academiclevel",
                        verbose_name="Next Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Level",
                "verbose_name_plural": "Academic Levels",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AcademicProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "overall_grade",
                    models.CharField(
                        blank=True,
                        help_text="Letter grade (A, B+, C, etc.)",
                        max_length=5,
                        verbose_name="Overall Grade",
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grade Point Average (0.00 - 4.00)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="GPA",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Overall percentage score",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Overall Percentage",
                    ),
                ),
                (
                    "total_school_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of school days in the session",
                        verbose_name="Total School Days",
                    ),
                ),
                (
                    "days_attended",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of days student was present",
                        verbose_name="Days Attended",
                    ),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Attendance Percentage",
                    ),
                ),
                (
                    "progress_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("SATISFACTORY", "Satisfactory"),
                            ("NEEDS_IMPROVEMENT", "Needs Improvement"),
                            ("POOR", "Poor"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Progress Status",
                    ),
                ),
                (
                    "is_eligible_for_promotion",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Eligible for Promotion",
                    ),
                ),
                (
                    "promotion_decision",
                    models.CharField(
                        choices=[
                            ("PROMOTED", "Promoted"),
                            ("REPEAT", "Repeat Class"),
                            ("CONDITIONAL", "Conditional Promotion"),
                            ("PENDING", "Decision Pending"),
                            ("TRANSFERRED", "Transferred Out"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Promotion Decision",
                    ),
                ),
                (
                    "promotion_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when promotion decision was made",
                        null=True,
                        verbose_name="Promotion Date",
                    ),
                ),
                (
                    "total_subjects",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of subjects taken",
                        verbose_name="Total Subjects",
                    ),
                ),
                (
                    "subjects_passed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of subjects passed",
                        verbose_name="Subjects Passed",
                    ),
                ),
                (
                    "subjects_failed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of subjects failed",
                        verbose_name="Subjects Failed",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Mark this as the final academic record for the session",
                        verbose_name="Is Final Record",
                    ),
                ),
                (
                    "final_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this record was finalized",
                        null=True,
                        verbose_name="Final Record Date",
                    ),
                ),
                (
                    "finalized_by",
                    models.CharField(
                        blank=True,
                        help_text="User who finalized this record",
                        max_length=100,
                        verbose_name="Finalized By",
                    ),
                ),
                (
                    "teacher_comments",
                    models.TextField(
                        blank=True,
                        help_text="Class teacher's comments on student progress",
                        verbose_name="Teacher Comments",
                    ),
                ),
                (
                    "head_teacher_comments",
                    models.TextField(
                        blank=True,
                        help_text="Head teacher or principal's comments",
                        verbose_name="Head Teacher Comments",
                    ),
                ),
                (
                    "parent_comments",
                    models.TextField(
                        blank=True,
                        help_text="Parent/guardian feedback (if applicable)",
                        verbose_name="Parent Comments",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recommendations for improvement or next steps",
                        verbose_name="Recommendations",
                    ),
                ),
                (
                    "promoted_to_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academic level student was promoted to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_students",
                        to="academics.academiclevel",
                        verbose_name="Promoted to Academic Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Progress",
                "verbose_name_plural": "Academic Progress Records",
                "ordering": ["-academic_session__start_date", "student__last_name"],
            },
        ),
    ]
