# Generated by Django 5.2 on 2025-12-14 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Level Name")),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Level Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="For ordering levels", verbose_name="Order"
                    ),
                ),
                (
                    "has_sections",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this level has multiple sections/streams (A, B, C, etc.)",
                        verbose_name="Has Sections/Streams",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_graduation_level",
                    models.BooleanField(
                        default=False,
                        help_text="Whether completing this level constitutes graduation",
                        verbose_name="Is Graduation Level",
                    ),
                ),
                (
                    "next_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="The level students progress to after completing this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_levels",
                        to="academics.academiclevel",
                        verbose_name="Next Level",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="academics_a_created_407795_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="academics_a_updated_e6bf26_idx"
                    ),
                    models.Index(
                        fields=["created_by_id"], name="academics_a_created_da5740_idx"
                    ),
                    models.Index(
                        fields=["updated_by_id"], name="academics_a_updated_878c52_idx"
                    ),
                ],
            },
        ),
    ]
