# Generated by Django 5.2 on 2025-12-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_progress",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["is_current"], name="academics_a_is_curr_e0bc3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["is_active"], name="academics_a_is_acti_3c0aae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["is_academically_closed"], name="academics_a_is_acad_321bcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["is_special_session"], name="academics_a_is_spec_5691b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["start_date", "end_date"], name="academics_a_start_d_75c697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["year_name", "term_number"],
                name="academics_a_year_na_d889b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["allows_promotion", "promotion_done"],
                name="academics_a_allows__18da4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["period_type"], name="academics_a_period__989038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["enrollment_deadline"], name="academics_a_enrollm_49e2d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="session_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("late_payment_penalty_rate__gte", 0),
                    ("late_payment_penalty_rate__lte", 100),
                ),
                name="valid_penalty_rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_attendance_percentage__gte", 0),
                    ("minimum_attendance_percentage__lte", 100),
                ),
                name="valid_attendance_percentage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicsession",
            unique_together={("year_name", "term_number")},
        ),
        migrations.AddField(
            model_name="academicprogress",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="academic_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.academiclevel",
                verbose_name="Academic Level",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
    ]
