# Generated by Django 5.2 on 2025-12-17 12:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "year_name",
                    models.CharField(
                        help_text="E.g., '2024-2025' or '2024'",
                        max_length=20,
                        verbose_name="Academic Year",
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        help_text="Position of this period within the year (1, 2, 3, etc.)",
                        verbose_name="Period Number",
                    ),
                ),
                (
                    "term_name",
                    models.CharField(
                        help_text="E.g., 'Fall Semester', 'Term 1', 'Quarter 3', etc.",
                        max_length=50,
                        verbose_name="Period Name",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("term", "Term"),
                            ("semester", "Semester"),
                            ("quarter", "Quarter"),
                            ("trimester", "Trimester"),
                            ("module", "Module"),
                            ("block", "Block"),
                            ("yearlong", "Year-long"),
                            ("intensive", "Intensive"),
                            ("custom", "Custom"),
                        ],
                        default="term",
                        help_text="Type of academic period (automatically set from school configuration)",
                        max_length=15,
                        verbose_name="Period Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="Is Current Session"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
                (
                    "allows_promotion",
                    models.BooleanField(
                        default=False,
                        help_text="Whether students can be promoted at the end of this period",
                        verbose_name="Allows Promotion",
                    ),
                ),
                (
                    "promotion_done",
                    models.BooleanField(
                        default=False, verbose_name="Promotion Completed"
                    ),
                ),
                (
                    "registration_fee_required",
                    models.BooleanField(
                        default=True, verbose_name="Registration Fee Required"
                    ),
                ),
                (
                    "late_payment_penalty_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage penalty for late payments (e.g., 5.00 for 5%)",
                        max_digits=5,
                        verbose_name="Late Payment Penalty Rate",
                    ),
                ),
                (
                    "enrollment_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Last date for student enrollment",
                        null=True,
                        verbose_name="Enrollment Deadline",
                    ),
                ),
                (
                    "late_enrollment_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether students can enroll after deadline",
                        verbose_name="Late Enrollment Allowed",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Session Closed"),
                ),
                (
                    "closure_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closure Date"
                    ),
                ),
                (
                    "closed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of user who closed this session",
                        max_length=100,
                        null=True,
                        verbose_name="Closed By User ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
                "ordering": ["-start_date", "term_number"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="E.g., A, B, C (leave blank if no sections)",
                        max_length=10,
                        null=True,
                        verbose_name="Section",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Maximum Students"
                    ),
                ),
                (
                    "class_schedule",
                    models.TextField(blank=True, verbose_name="Class Schedule"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End Time"),
                ),
                (
                    "class_motto",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Class Motto"
                    ),
                ),
                (
                    "class_colors",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Class Colors"
                    ),
                ),
                (
                    "class_average_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current class average performance score",
                        max_digits=5,
                        null=True,
                        verbose_name="Class Average Score",
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Class attendance rate percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Attendance Rate",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["academic_level__order", "section"],
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Room Name")),
                (
                    "room_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Room Number"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Building"
                    ),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="Floor"),
                ),
                (
                    "wing",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Wing/Section"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=0, verbose_name="Capacity"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Classroom"),
                            ("LABORATORY", "Laboratory"),
                            ("COMPUTER_LAB", "Computer Laboratory"),
                            ("LIBRARY", "Library"),
                            ("AUDITORIUM", "Auditorium"),
                            ("GYMNASIUM", "Gymnasium"),
                            ("WORKSHOP", "Workshop"),
                            ("CONFERENCE", "Conference Room"),
                            ("MUSIC_ROOM", "Music Room"),
                            ("ART_ROOM", "Art Room"),
                            ("SCIENCE_LAB", "Science Laboratory"),
                            ("LANGUAGE_LAB", "Language Laboratory"),
                            ("EXAMINATION_HALL", "Examination Hall"),
                        ],
                        default="REGULAR",
                        max_length=20,
                        verbose_name="Room Type",
                    ),
                ),
                (
                    "has_projector",
                    models.BooleanField(default=False, verbose_name="Has Projector"),
                ),
                (
                    "has_computer",
                    models.BooleanField(default=False, verbose_name="Has Computer"),
                ),
                (
                    "has_air_conditioning",
                    models.BooleanField(
                        default=False, verbose_name="Has Air Conditioning"
                    ),
                ),
                (
                    "has_whiteboard",
                    models.BooleanField(default=True, verbose_name="Has Whiteboard"),
                ),
                (
                    "has_blackboard",
                    models.BooleanField(default=True, verbose_name="Has Blackboard"),
                ),
                (
                    "has_smart_board",
                    models.BooleanField(default=False, verbose_name="Has Smart Board"),
                ),
                (
                    "has_internet",
                    models.BooleanField(
                        default=False, verbose_name="Has Internet Access"
                    ),
                ),
                (
                    "has_sound_system",
                    models.BooleanField(default=False, verbose_name="Has Sound System"),
                ),
                (
                    "specialized_equipment",
                    models.TextField(
                        blank=True,
                        help_text="List of specialized equipment available in this room",
                        verbose_name="Specialized Equipment",
                    ),
                ),
                (
                    "is_accessible",
                    models.BooleanField(default=True, verbose_name="Is Accessible"),
                ),
                (
                    "accessibility_features",
                    models.TextField(
                        blank=True,
                        help_text="Specific accessibility features available",
                        verbose_name="Accessibility Features",
                    ),
                ),
                (
                    "is_bookable",
                    models.BooleanField(default=True, verbose_name="Is Bookable"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires Approval"
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Maintenance Date"
                    ),
                ),
                (
                    "safety_inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Safety Inspection Date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Classroom",
                "verbose_name_plural": "Classrooms",
                "ordering": ["building", "floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="Is Optional"),
                ),
                (
                    "hours_per_week",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Hours Per Week"
                    ),
                ),
                (
                    "total_hours",
                    models.PositiveIntegerField(default=0, verbose_name="Total Hours"),
                ),
                (
                    "schedule_days",
                    models.JSONField(
                        blank=True,
                        help_text="Days of the week when this subject is taught",
                        null=True,
                        verbose_name="Schedule Days",
                    ),
                ),
                (
                    "preferred_periods",
                    models.JSONField(
                        blank=True,
                        help_text="Preferred time periods for this subject",
                        null=True,
                        verbose_name="Preferred Periods",
                    ),
                ),
                ("syllabus", models.TextField(blank=True, verbose_name="Syllabus")),
                (
                    "learning_objectives",
                    models.TextField(blank=True, verbose_name="Learning Objectives"),
                ),
                (
                    "assessment_criteria",
                    models.TextField(blank=True, verbose_name="Assessment Criteria"),
                ),
                (
                    "continuous_assessment_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="Percentage weight of continuous assessment",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Continuous Assessment Weight",
                    ),
                ),
                (
                    "final_exam_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=60.0,
                        help_text="Percentage weight of final examination",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Final Exam Weight",
                    ),
                ),
                (
                    "textbook",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Textbook"
                    ),
                ),
                (
                    "reference_materials",
                    models.TextField(blank=True, verbose_name="Reference Materials"),
                ),
                (
                    "required_equipment",
                    models.TextField(blank=True, verbose_name="Required Equipment"),
                ),
                (
                    "class_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current class average for this subject",
                        max_digits=5,
                        null=True,
                        verbose_name="Class Average",
                    ),
                ),
                (
                    "pass_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of students passing this subject",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pass Rate",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Class Subject",
                "verbose_name_plural": "Class Subjects",
                "ordering": ["class_instance", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Holiday Name")),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public Holiday"),
                            ("SCHOOL", "School Event"),
                            ("BREAK", "Term Break"),
                        ],
                        default="PUBLIC",
                        max_length=10,
                        verbose_name="Holiday Type",
                    ),
                ),
                (
                    "break_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TERM_BREAK", "Break Between Terms"),
                            ("YEAR_END", "End of Academic Year"),
                            ("YEAR_BREAK", "Break Between Years"),
                        ],
                        help_text="Only applicable for term breaks",
                        max_length=12,
                        null=True,
                        verbose_name="Break Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Subject Name")),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="Short form for display purposes (e.g., MATH, ENG, SCI)",
                        max_length=10,
                        unique=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Subject Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("MATH", "Mathematics"),
                            ("LANG_ARTS", "Language Arts"),
                            ("SCIENCES", "Sciences"),
                            ("SOCIAL", "Social Studies"),
                            ("LITERACY", "Literacy"),
                            ("NUMERACY", "Numeracy"),
                            ("SCIENCE_ENV", "Environmental Education"),
                            ("RELIGION", "Religious & Moral Education"),
                            ("CREATIVE", "Creative Arts & Life Skills"),
                            ("MOTHER_TONGUE", "Mother Tongue"),
                            ("FOREIGN_LANG", "Foreign Language"),
                            ("ARTS_CRAFTS", "Arts and Crafts"),
                            ("MUSIC", "Music"),
                            ("PE", "Physical Education"),
                            ("RELIGIOUS", "Religious Studies"),
                            ("COMPUTER", "Computer Studies"),
                            ("LIFE_SKILLS", "Life Skills"),
                            ("TECHNICAL", "Technical Subjects"),
                            ("BUSINESS", "Business Studies"),
                            ("AGRICULTURE", "Agriculture"),
                            ("HOME_ECON", "Home Economics"),
                            ("EXTRA", "Extracurricular Activities"),
                            ("CLUBS", "Clubs and Societies"),
                            ("GUIDANCE", "Guidance & Counselling"),
                            ("OTHER", "Other / Miscellaneous"),
                        ],
                        default="SCIENCES",
                        max_length=20,
                        verbose_name="Subject Type",
                    ),
                ),
                (
                    "credit_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="Credit Hours",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_compulsory",
                    models.BooleanField(default=True, verbose_name="Is Compulsory"),
                ),
                (
                    "pass_mark",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pass Mark",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="INTERMEDIATE",
                        max_length=20,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "weight_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for GPA calculation (1.0 = normal weight)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(3.0),
                        ],
                        verbose_name="Weight Factor",
                    ),
                ),
                (
                    "textbook_required",
                    models.BooleanField(default=True, verbose_name="Textbook Required"),
                ),
                (
                    "recommended_textbooks",
                    models.TextField(blank=True, verbose_name="Recommended Textbooks"),
                ),
                (
                    "required_materials",
                    models.TextField(blank=True, verbose_name="Required Materials"),
                ),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["subject_type", "abbreviation"],
            },
        ),
        migrations.AlterModelOptions(
            name="academiclevel",
            options={
                "ordering": ["order"],
                "verbose_name": "Academic Level",
                "verbose_name_plural": "Academic Levels",
            },
        ),
        migrations.RemoveIndex(
            model_name="academiclevel",
            name="academics_a_created_407795_idx",
        ),
        migrations.RemoveIndex(
            model_name="academiclevel",
            name="academics_a_updated_e6bf26_idx",
        ),
        migrations.RemoveIndex(
            model_name="academiclevel",
            name="academics_a_created_da5740_idx",
        ),
        migrations.RemoveIndex(
            model_name="academiclevel",
            name="academics_a_updated_878c52_idx",
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["is_current"], name="academics_a_is_curr_e0bc3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["is_active"], name="academics_a_is_acti_3c0aae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["start_date", "end_date"], name="academics_a_start_d_75c697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["year_name", "term_number"],
                name="academics_a_year_na_d889b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["allows_promotion", "promotion_done"],
                name="academics_a_allows__18da4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["period_type"], name="academics_a_period__989038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["is_closed"], name="academics_a_is_clos_832032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicsession",
            index=models.Index(
                fields=["enrollment_deadline"], name="academics_a_enrollm_49e2d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lte", models.F("end_date"))),
                name="session_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("late_payment_penalty_rate__gte", 0),
                    ("late_payment_penalty_rate__lte", 100),
                ),
                name="valid_penalty_rate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicsession",
            unique_together={("year_name", "term_number")},
        ),
        migrations.AddField(
            model_name="class",
            name="academic_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.academiclevel",
                verbose_name="Academic Level",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
    ]
