# Generated by Django 5.2 on 2025-12-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("fees", "0001_initial"),
        ("hr", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="assistant_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_assisted",
                to="hr.teacher",
                verbose_name="Assistant Teacher",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_led",
                to="hr.teacher",
                verbose_name="Class Teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["room_type"], name="academics_c_room_ty_a1cd8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["building", "floor"], name="academics_c_buildin_147a5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["is_active"], name="academics_c_is_acti_1d4af1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["capacity"], name="academics_c_capacit_7aee82_idx"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_classes",
                to="academics.classroom",
                verbose_name="Primary Classroom",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="class_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.class",
                verbose_name="Class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_subjects",
                to="hr.teacher",
                verbose_name="Subject Teacher",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="academic_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic session this holiday falls within (optional, for reference)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holidays",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="academic_invoice",
            field=models.OneToOneField(
                blank=True,
                help_text="Invoice generated for this class enrollment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_enrollment",
                to="fees.feeinvoice",
                verbose_name="Academic Fees Invoice",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_class_enrollments",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="class_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.class",
                verbose_name="Class",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="previous_enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous class enrollment before promotion/transfer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_enrollment",
                to="academics.studentclassenrollment",
                verbose_name="Previous Enrollment",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="academicprogress",
            name="class_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to="academics.studentclassenrollment",
                verbose_name="Class Enrollment",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="applicable_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Academic levels where this subject is offered",
                to="academics.academiclevel",
                verbose_name="Applicable Academic Levels",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="hr.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects that must be completed before taking this subject",
                related_name="prerequisite_for",
                to="academics.subject",
                verbose_name="Prerequisites",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["academic_level", "academic_session"],
                name="academics_c_academi_54ee3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["class_teacher"], name="academics_c_class_t_c0909b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["is_active"], name="academics_c_is_acti_01dd66_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section__isnull", False)),
                fields=("academic_level", "section", "academic_session"),
                name="unique_class_with_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section__isnull", True)),
                fields=("academic_level", "academic_session"),
                name="unique_class_without_section",
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["start_date", "end_date"], name="academics_h_start_d_d8e1e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["holiday_type"], name="academics_h_holiday_a14fd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["is_school_closed"], name="academics_h_is_scho_a7f738_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["academic_session"], name="academics_h_academi_f5423a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["is_recurring"], name="academics_h_is_recu_fabd78_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="holiday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__lte", models.F("end_date")),
                    ("end_date__isnull", True),
                    _connector="OR",
                ),
                name="holiday_start_before_end",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["student", "academic_session"],
                name="academics_s_student_0b485f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["class_instance", "is_active"],
                name="academics_s_class_i_b3fc38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["enrollment_type"], name="academics_s_enrollm_eacaf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["completion_status"], name="academics_s_complet_87b917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["enrollment_date"], name="academics_s_enrollm_eb709c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["student", "is_active", "completion_status"],
                name="academics_s_student_7a3bf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["progression_type"], name="academics_s_progres_f5d2e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["academic_session", "is_active", "completion_status"],
                name="academics_s_academi_946eae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["roll_number"], name="academics_s_roll_nu_7ea1fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["class_instance", "academic_session", "roll_number"],
                name="academics_s_class_i_6d8e5e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("completion_status", "ONGOING"), ("is_active", True)
                ),
                fields=("student", "academic_session"),
                name="unique_active_enrollment_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "class_instance", "academic_session"),
                name="unique_student_class_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("roll_number__isnull", False),
                    models.Q(("roll_number", ""), _negated=True),
                ),
                fields=("class_instance", "academic_session", "roll_number"),
                name="unique_roll_number_per_class_session",
            ),
        ),
        migrations.AddIndex(
            model_name="academicprogress",
            index=models.Index(
                fields=["student", "academic_session"],
                name="academics_a_student_4b7ca2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicprogress",
            index=models.Index(
                fields=["is_eligible_for_promotion"],
                name="academics_a_is_elig_d229c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicprogress",
            index=models.Index(
                fields=["promotion_decision"], name="academics_a_promoti_7db391_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicprogress",
            index=models.Index(
                fields=["is_final"], name="academics_a_is_fina_03f8e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicprogress",
            index=models.Index(
                fields=["progress_status"], name="academics_a_progres_68e398_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicprogress",
            index=models.Index(
                fields=["class_enrollment"], name="academics_a_class_e_487989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicprogress",
            index=models.Index(
                fields=["promoted_to_level"], name="academics_a_promote_d71e78_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("days_attended__lte", models.F("total_school_days"))
                ),
                name="attendance_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("gpa__gte", 0), ("gpa__lte", 4)),
                    ("gpa__isnull", True),
                    _connector="OR",
                ),
                name="gpa_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("percentage__gte", 0), ("percentage__lte", 100)),
                    ("percentage__isnull", True),
                    _connector="OR",
                ),
                name="percentage_valid_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicprogress",
            unique_together={("student", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["subject_type"], name="academics_s_subject_ead729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_active"], name="academics_s_is_acti_c08ed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_compulsory"], name="academics_s_is_comp_26568a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["department"], name="academics_s_departm_84879b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["class_instance", "is_active"],
                name="academics_c_class_i_c8fcf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["teacher"], name="academics_c_teacher_68a872_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["subject"], name="academics_c_subject_10f4e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["is_optional"], name="academics_c_is_opti_a3c872_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_instance", "subject")},
        ),
    ]
