# Generated by Django 5.2 on 2025-12-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0002_academicsession_class_classroom_classsubject_holiday_and_more",
        ),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="assistant_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_assisted",
                to="hr.teacher",
                verbose_name="Assistant Teacher",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_led",
                to="hr.teacher",
                verbose_name="Class Teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["room_type"], name="academics_c_room_ty_a1cd8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["building", "floor"], name="academics_c_buildin_147a5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["is_active"], name="academics_c_is_acti_1d4af1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(
                fields=["capacity"], name="academics_c_capacit_7aee82_idx"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_classes",
                to="academics.classroom",
                verbose_name="Primary Classroom",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="class_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.class",
                verbose_name="Class",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_subjects",
                to="hr.teacher",
                verbose_name="Subject Teacher",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="academic_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="next_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Only applicable for term breaks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preceding_breaks",
                to="academics.academicsession",
                verbose_name="Session After Break",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="previous_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Only applicable for term breaks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="following_breaks",
                to="academics.academicsession",
                verbose_name="Session Before Break",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="applicable_levels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Academic levels where this subject is offered",
                to="academics.academiclevel",
                verbose_name="Applicable Academic Levels",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="hr.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects that must be completed before taking this subject",
                related_name="prerequisite_for",
                to="academics.subject",
                verbose_name="Prerequisites",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["academic_level", "academic_session"],
                name="academics_c_academi_54ee3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["class_teacher"], name="academics_c_class_t_c0909b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["is_active"], name="academics_c_is_acti_01dd66_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section__isnull", False)),
                fields=("academic_level", "section", "academic_session"),
                name="unique_class_with_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section__isnull", True)),
                fields=("academic_level", "academic_session"),
                name="unique_class_without_section",
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["start_date", "end_date"], name="academics_h_start_d_d8e1e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["holiday_type"], name="academics_h_holiday_a14fd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["break_type"], name="academics_h_break_t_2d1bbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["subject_type"], name="academics_s_subject_ead729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_active"], name="academics_s_is_acti_c08ed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_compulsory"], name="academics_s_is_comp_26568a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["department"], name="academics_s_departm_84879b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["class_instance", "is_active"],
                name="academics_c_class_i_c8fcf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["teacher"], name="academics_c_teacher_68a872_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["subject"], name="academics_c_subject_10f4e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsubject",
            index=models.Index(
                fields=["is_optional"], name="academics_c_is_opti_a3c872_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_instance", "subject")},
        ),
    ]
