# Generated by Django 5.2 on 2026-04-01 15:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicprogress",
            name="days_attended",
            field=models.PositiveIntegerField(default=0, verbose_name="Days Attended"),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="final_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Final Record Date"
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="finalized_by",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Finalized By"
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="GPA",
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="head_teacher_comments",
            field=models.TextField(blank=True, verbose_name="Head Teacher Comments"),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="is_final",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Final Record"
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="overall_grade",
            field=models.CharField(
                blank=True, max_length=5, verbose_name="Overall Grade"
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="parent_comments",
            field=models.TextField(blank=True, verbose_name="Parent Comments"),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Overall Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="promoted_to_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoted_students",
                to="academics.academiclevel",
                verbose_name="Promoted to Academic Level",
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="promotion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Promotion Date"
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="recommendations",
            field=models.TextField(blank=True, verbose_name="Recommendations"),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="subjects_failed",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Subjects Failed"
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="subjects_passed",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Subjects Passed"
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="teacher_comments",
            field=models.TextField(blank=True, verbose_name="Teacher Comments"),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="total_school_days",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total School Days"
            ),
        ),
        migrations.AlterField(
            model_name="academicprogress",
            name="total_subjects",
            field=models.PositiveIntegerField(default=0, verbose_name="Total Subjects"),
        ),
        migrations.AlterField(
            model_name="class",
            name="attendance_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Attendance Rate",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="class_average_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Class Average Score",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="accessibility_features",
            field=models.TextField(blank=True, verbose_name="Accessibility Features"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="specialized_equipment",
            field=models.TextField(blank=True, verbose_name="Specialized Equipment"),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="class_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Class Average",
            ),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="continuous_assessment_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=40.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Continuous Assessment Weight",
            ),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="final_exam_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=60.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Final Exam Weight",
            ),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="pass_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Pass Rate",
            ),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="preferred_periods",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Preferred Periods"
            ),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="schedule_days",
            field=models.JSONField(blank=True, null=True, verbose_name="Schedule Days"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="affects_attendance",
            field=models.BooleanField(default=True, verbose_name="Affects Attendance"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="affects_payroll",
            field=models.BooleanField(default=False, verbose_name="Affects Payroll"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="is_partial_closure",
            field=models.BooleanField(default=False, verbose_name="Partial Closure"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="is_recurring",
            field=models.BooleanField(default=False, verbose_name="Is Recurring"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="is_school_closed",
            field=models.BooleanField(default=True, verbose_name="School Closed"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Internal Notes"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="notify_parents",
            field=models.BooleanField(default=True, verbose_name="Notify Parents"),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="notify_staff",
            field=models.BooleanField(default=True, verbose_name="Notify Staff"),
        ),
        migrations.AlterField(
            model_name="studentclassenrollment",
            name="enrollment_notes",
            field=models.TextField(blank=True, verbose_name="Enrollment Notes"),
        ),
        migrations.AlterField(
            model_name="studentclassenrollment",
            name="previous_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_enrollment",
                to="academics.studentclassenrollment",
                verbose_name="Previous Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="studentclassenrollment",
            name="progression_type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal Progression"),
                    ("SKIP", "Level Skipped"),
                    ("REPEAT", "Level Repeated"),
                    ("LATERAL", "Lateral Transfer"),
                    ("READMISSION", "Readmission"),
                ],
                default="NORMAL",
                max_length=20,
                verbose_name="Progression Type",
            ),
        ),
    ]
