# Generated by Django 5.2 on 2025-12-30 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Model Type"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Object ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        max_length=200, verbose_name="Object Representation"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of field changes: {'field_name': {'old': 'value', 'new': 'value'}}",
                        verbose_name="Changes",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who performed this action",
                        max_length=50,
                        null=True,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="User Email"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User Name"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this action occurred (in school's operational timezone)",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "change_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Change Reason"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Session Key"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Request Path"
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="utils_audit_content_131a61_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="utils_audit_user_id_9929fa_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="utils_audit_timesta_d9644a_idx"
                    ),
                    models.Index(
                        fields=["action"], name="utils_audit_action_1d6570_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this financial action occurred (in school's operational timezone)",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INVOICE_CREATE", "Invoice Created"),
                            ("INVOICE_UPDATE", "Invoice Updated"),
                            ("INVOICE_CANCEL", "Invoice Cancelled"),
                            ("PAYMENT_RECEIVE", "Payment Received"),
                            ("PAYMENT_REFUND", "Payment Refunded"),
                            ("BALANCE_ADJUST", "Student Balance Adjusted"),
                            ("SCHOLARSHIP_APPLY", "Scholarship Applied"),
                            ("SCHOLARSHIP_REMOVE", "Scholarship Removed"),
                            ("DISCOUNT_APPLY", "Discount Applied"),
                            ("DISCOUNT_REMOVE", "Discount Removed"),
                            ("FEE_STRUCTURE_CREATE", "Fee Structure Created"),
                            ("FEE_STRUCTURE_UPDATE", "Fee Structure Updated"),
                            ("BULK_INVOICE_CREATE", "Bulk Invoice Generation"),
                            ("FINANCIAL_REPORT_GENERATE", "Financial Report Generated"),
                            ("FINANCIAL_DATA_EXPORT", "Financial Data Exported"),
                            ("SETTINGS_CHANGE", "Financial Settings Changed"),
                            ("USER_ACCESS_FINANCIAL", "Financial Module Accessed"),
                            ("ACCOUNT_CREATE", "Account Created"),
                            ("ACCOUNT_UPDATE", "Account Updated"),
                            ("JOURNAL_POST", "Journal Entry Posted"),
                            ("RECONCILIATION", "Account Reconciliation"),
                            ("EXPENSE_CREATE", "Expense Created"),
                            ("EXPENSE_APPROVE", "Expense Approved"),
                            ("BUDGET_CREATE", "Budget Created"),
                            ("BUDGET_APPROVE", "Budget Approved"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who performed this action",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=200, null=True)),
                ("user_role", models.CharField(blank=True, max_length=100, null=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "object_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "amount_involved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monetary amount involved in the action",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default="UGX", max_length=3, null=True
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "student_admission_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "academic_session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "academic_session_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Values before change", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="Values after change", null=True
                    ),
                ),
                (
                    "changes_summary",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable summary of changes",
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "compliance_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Compliance-related flags or concerns",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context-specific data",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this action was performed automatically by the system",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        help_text="For grouping related bulk operations",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Audit Log",
                "verbose_name_plural": "Financial Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "action"],
                        name="utils_finan_timesta_2bc6fc_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="utils_finan_user_id_aa50a1_idx",
                    ),
                    models.Index(
                        fields=["student_id", "timestamp"],
                        name="utils_finan_student_bfb358_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "timestamp"],
                        name="utils_finan_risk_le_978129_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="utils_finan_ip_addr_99ad88_idx",
                    ),
                    models.Index(
                        fields=["academic_session_id", "action"],
                        name="utils_finan_academi_5a395b_idx",
                    ),
                ],
            },
        ),
    ]
