# Generated by Django 5.2 on 2025-12-14 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Model Type"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Object ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        max_length=200, verbose_name="Object Representation"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionary of field changes: {'field_name': {'old': 'value', 'new': 'value'}}",
                        verbose_name="Changes",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="User ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="User Email"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User Name"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "change_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Change Reason"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Session Key"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Request Path"
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="utils_audit_content_131a61_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="utils_audit_user_id_9929fa_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="utils_audit_timesta_d9644a_idx"
                    ),
                    models.Index(
                        fields=["action"], name="utils_audit_action_1d6570_idx"
                    ),
                ],
            },
        ),
    ]
