# Generated by Django 5.2 on 2025-12-17 12:12

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "school_currency",
                    djmoney.models.fields.CurrencyField(
                        default="UGX",
                        help_text="Primary currency for this school",
                        max_length=3,
                    ),
                ),
                (
                    "currency_position",
                    models.CharField(
                        choices=[
                            ("BEFORE", "Before amount (UGX 100.00)"),
                            ("AFTER", "After amount (100.00 UGX)"),
                            ("BEFORE_NO_SPACE", "Before, no space (UGX100.00)"),
                            ("AFTER_NO_SPACE", "After, no space (100.00UGX)"),
                        ],
                        default="BEFORE",
                        max_length=20,
                        verbose_name="Currency Position",
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Number of decimal places for currency display",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Decimal Places",
                    ),
                ),
                (
                    "use_thousand_separator",
                    models.BooleanField(
                        default=True, verbose_name="Use Thousand Separator"
                    ),
                ),
                (
                    "default_payment_terms_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Default Payment Terms (Days)"
                    ),
                ),
                (
                    "late_fee_enabled",
                    models.BooleanField(default=True, verbose_name="Enable Late Fees"),
                ),
                (
                    "late_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Default Late Fee Percentage",
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Default Grace Period (Days)"
                    ),
                ),
                (
                    "minimum_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="Minimum amount for any payment transaction in school currency",
                        max_digits=12,
                        verbose_name="Minimum Payment Amount",
                    ),
                ),
                (
                    "auto_apply_scholarships",
                    models.BooleanField(
                        default=True, verbose_name="Auto Apply Scholarships"
                    ),
                ),
                (
                    "scholarship_approval_required",
                    models.BooleanField(
                        default=False, verbose_name="Scholarship Approval Required"
                    ),
                ),
                (
                    "auto_apply_discounts",
                    models.BooleanField(
                        default=True, verbose_name="Auto Apply Discounts"
                    ),
                ),
                (
                    "discount_approval_required",
                    models.BooleanField(
                        default=True, verbose_name="Discount Approval Required"
                    ),
                ),
                (
                    "expense_approval_required",
                    models.BooleanField(
                        default=True, verbose_name="Expense Approval Required"
                    ),
                ),
                (
                    "expense_approval_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100000.00"),
                        max_digits=12,
                        verbose_name="Expense Approval Limit",
                    ),
                ),
                (
                    "send_invoice_emails",
                    models.BooleanField(
                        default=True, verbose_name="Send Invoice Emails"
                    ),
                ),
                (
                    "send_payment_confirmations",
                    models.BooleanField(
                        default=True, verbose_name="Send Payment Confirmations"
                    ),
                ),
                (
                    "send_overdue_reminders",
                    models.BooleanField(
                        default=True, verbose_name="Send Overdue Reminders"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="utils_finan_created_32536a_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="utils_finan_updated_eaabba_idx"
                    ),
                    models.Index(
                        fields=["created_by_id"], name="utils_finan_created_683ad0_idx"
                    ),
                    models.Index(
                        fields=["updated_by_id"], name="utils_finan_updated_7999cb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SchoolConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "term_system",
                    models.CharField(
                        choices=[
                            ("term", "Terms (3 per year)"),
                            ("semester", "Semesters (2 per year)"),
                            ("quarter", "Quarters (4 per year)"),
                            ("trimester", "Trimesters (3 per year)"),
                            ("module", "Modules (6-8 per year)"),
                            ("block", "Block Schedule (4-6 per year)"),
                            ("yearlong", "Year-long Program (1 per year)"),
                            ("intensive", "Intensive Programs (8-12 per year)"),
                            ("custom", "Custom System"),
                        ],
                        default="term",
                        help_text="The academic period system used by the school",
                        max_length=15,
                        verbose_name="Academic Period System",
                    ),
                ),
                (
                    "periods_per_year",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of academic periods in one academic year (1-20)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Periods Per Year",
                    ),
                ),
                (
                    "period_naming_convention",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric (Term 1, Term 2, etc.)"),
                            ("ordinal", "Ordinal (First Term, Second Term, etc.)"),
                            ("seasonal", "Seasonal (Fall, Spring, Summer)"),
                            ("monthly", "Monthly (January, February, etc.)"),
                            ("alpha", "Alphabetical (Term A, Term B, etc.)"),
                            ("roman", "Roman Numerals (Term I, Term II, etc.)"),
                            ("custom", "Custom Names"),
                        ],
                        default="numeric",
                        max_length=20,
                        verbose_name="Period Naming Convention",
                    ),
                ),
                (
                    "custom_period_names",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Custom names for each period position. E.g., {"1": "Fall Semester", "2": "Spring Semester"}',
                        verbose_name="Custom Period Names",
                    ),
                ),
                (
                    "academic_year_type",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar Year (Jan-Dec)"),
                            ("northern", "Northern Hemisphere (Sep-Jun)"),
                            ("southern", "Southern Hemisphere (Feb-Nov)"),
                            ("tropical", "Tropical Regions (Jan-Nov)"),
                            ("east_africa", "East African Calendar (Jan-Nov)"),
                            ("west_africa", "West African Calendar (Sep-Jul)"),
                            ("sahel", "Sahel Region (Oct-Jun)"),
                            ("financial", "Financial Year (Apr-Mar)"),
                            ("custom", "Custom Year Dates"),
                        ],
                        default="northern",
                        help_text="When your academic year typically runs",
                        max_length=15,
                        verbose_name="Academic Year Type",
                    ),
                ),
                (
                    "academic_year_start_month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=9,
                        help_text="Month when academic year typically starts (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Academic Year Start Month",
                    ),
                ),
                (
                    "academic_year_start_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Day when academic year typically starts",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Academic Year Start Day",
                    ),
                ),
                (
                    "regional_season_type",
                    models.CharField(
                        choices=[
                            ("temperate", "Temperate (Spring/Summer/Fall/Winter)"),
                            ("tropical_wet_dry", "Tropical (Wet/Dry Seasons)"),
                            ("desert", "Desert (Hot/Cool Seasons)"),
                            ("equatorial", "Equatorial (Year-round)"),
                            ("monsoon", "Monsoon (Pre/Monsoon/Post)"),
                            ("custom_regional", "Custom Regional Seasons"),
                        ],
                        default="temperate",
                        help_text="Climate-based season naming for your region",
                        max_length=20,
                        verbose_name="Regional Season Type",
                    ),
                ),
                (
                    "custom_season_names",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Regional season names. E.g., {'1': 'Harmattan', '2': 'Rainy Season'}",
                        verbose_name="Custom Season Names",
                    ),
                ),
                (
                    "auto_create_breaks",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create holiday records for breaks between terms",
                        verbose_name="Auto-Create Term Breaks",
                    ),
                ),
                (
                    "minimum_break_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum number of days for a break to be considered significant",
                        verbose_name="Minimum Break Days",
                    ),
                ),
                (
                    "default_period_duration_weeks",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Typical duration of each academic period in weeks",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                        verbose_name="Default Period Duration (weeks)",
                    ),
                ),
                (
                    "enable_automatic_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Send automatic payment and deadline reminders",
                        verbose_name="Enable Automatic Reminders",
                    ),
                ),
                (
                    "enable_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Send SMS notifications to parents and students",
                        verbose_name="Enable SMS Notifications",
                    ),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send email notifications",
                        verbose_name="Enable Email Notifications",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="utils_schoo_created_c15878_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="utils_schoo_updated_1636be_idx"
                    ),
                    models.Index(
                        fields=["created_by_id"], name="utils_schoo_created_cbe8c0_idx"
                    ),
                    models.Index(
                        fields=["updated_by_id"], name="utils_schoo_updated_5dc2e0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INVOICE_CREATE", "Invoice Created"),
                            ("INVOICE_UPDATE", "Invoice Updated"),
                            ("INVOICE_CANCEL", "Invoice Cancelled"),
                            ("PAYMENT_RECEIVE", "Payment Received"),
                            ("PAYMENT_REFUND", "Payment Refunded"),
                            ("BALANCE_ADJUST", "Student Balance Adjusted"),
                            ("SCHOLARSHIP_APPLY", "Scholarship Applied"),
                            ("SCHOLARSHIP_REMOVE", "Scholarship Removed"),
                            ("DISCOUNT_APPLY", "Discount Applied"),
                            ("DISCOUNT_REMOVE", "Discount Removed"),
                            ("FEE_STRUCTURE_CREATE", "Fee Structure Created"),
                            ("FEE_STRUCTURE_UPDATE", "Fee Structure Updated"),
                            ("BULK_INVOICE_CREATE", "Bulk Invoice Generation"),
                            ("FINANCIAL_REPORT_GENERATE", "Financial Report Generated"),
                            ("FINANCIAL_DATA_EXPORT", "Financial Data Exported"),
                            ("SETTINGS_CHANGE", "Financial Settings Changed"),
                            ("USER_ACCESS_FINANCIAL", "Financial Module Accessed"),
                            ("ACCOUNT_CREATE", "Account Created"),
                            ("ACCOUNT_UPDATE", "Account Updated"),
                            ("JOURNAL_POST", "Journal Entry Posted"),
                            ("RECONCILIATION", "Account Reconciliation"),
                            ("EXPENSE_CREATE", "Expense Created"),
                            ("EXPENSE_APPROVE", "Expense Approved"),
                            ("BUDGET_CREATE", "Budget Created"),
                            ("BUDGET_APPROVE", "Budget Approved"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=200, null=True)),
                ("user_role", models.CharField(blank=True, max_length=100, null=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "object_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "amount_involved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monetary amount involved in the action",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "student_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "student_admission_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "academic_session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "academic_session_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, help_text="Values before change", null=True
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, help_text="Values after change", null=True
                    ),
                ),
                (
                    "changes_summary",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable summary of changes",
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "compliance_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Compliance-related flags or concerns",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context-specific data",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this action was performed automatically by the system",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        help_text="For grouping related bulk operations",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Audit Log",
                "verbose_name_plural": "Financial Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "action"],
                        name="utils_finan_timesta_2bc6fc_idx",
                    ),
                    models.Index(
                        fields=["user_id", "timestamp"],
                        name="utils_finan_user_id_aa50a1_idx",
                    ),
                    models.Index(
                        fields=["student_id", "timestamp"],
                        name="utils_finan_student_bfb358_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "timestamp"],
                        name="utils_finan_risk_le_978129_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="utils_finan_ip_addr_99ad88_idx",
                    ),
                    models.Index(
                        fields=["academic_session_id", "action"],
                        name="utils_finan_academi_5a395b_idx",
                    ),
                ],
            },
        ),
    ]
