# Generated by Django 5.2 on 2025-12-30 10:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "primary_phone",
                    models.CharField(max_length=20, verbose_name="Primary Phone"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Secondary Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=80, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Occupation"
                    ),
                ),
                (
                    "employer",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Employer"
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Work Phone"
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Monthly Income",
                    ),
                ),
                ("home_address", models.TextField(verbose_name="Home Address")),
                (
                    "work_address",
                    models.TextField(blank=True, verbose_name="Work Address"),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="District"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="City"),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="UG", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="National ID"
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Passport Number"
                    ),
                ),
                (
                    "guardian_type",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Guardian"),
                            ("SECONDARY", "Secondary Guardian"),
                            ("EMERGENCY", "Emergency Contact"),
                            ("FINANCIAL", "Financial Sponsor"),
                        ],
                        default="PRIMARY",
                        max_length=20,
                        verbose_name="Guardian Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="guardians/photos/%Y/%m/",
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guardian",
                "verbose_name_plural": "Guardians",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["guardian_type"], name="students_gu_guardia_62341c_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="students_gu_is_acti_b2eec2_idx"
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="students_gu_first_n_0bd4ca_idx",
                    ),
                    models.Index(
                        fields=["primary_phone"], name="students_gu_primary_787a00_idx"
                    ),
                    models.Index(fields=["email"], name="students_gu_email_97bf2f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Admission Number",
                    ),
                ),
                ("admission_date", models.DateField(verbose_name="Admission Date")),
                (
                    "national_student_number",
                    models.CharField(
                        blank=True,
                        help_text="Government-issued student identification number",
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="National Student Number",
                    ),
                ),
                (
                    "birth_certificate_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Birth Certificate Number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "nationality",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True, verbose_name="Nationality"
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ethnicity"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Place of Birth"
                    ),
                ),
                (
                    "birth_country",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Country of Birth",
                    ),
                ),
                (
                    "religious_affiliation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CATHOLIC", "Catholic"),
                            ("PROTESTANT", "Protestant"),
                            ("ANGLICAN", "Anglican"),
                            ("BAPTIST", "Baptist"),
                            ("PENTECOSTAL", "Pentecostal"),
                            ("EVANGELICAL", "Evangelical"),
                            ("ADVENTIST", "Adventist"),
                            ("ISLAM", "Islam"),
                            ("HINDU", "Hindu"),
                            ("BUDDHIST", "Buddhist"),
                            ("JEWISH", "Jewish"),
                            ("TRADITIONAL", "Traditional"),
                            ("NONE", "No Religion"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Religious Affiliation",
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Personal Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                ("home_address", models.TextField(verbose_name="Home Address")),
                (
                    "mailing_address",
                    models.TextField(blank=True, verbose_name="Mailing Address"),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="District"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Region/Province"
                    ),
                ),
                (
                    "country_of_residence",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Country of Residence",
                    ),
                ),
                (
                    "health_condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("CHRONIC", "Chronic Condition"),
                            ("RECOVERING", "Recovering"),
                            ("SPECIAL_NEEDS", "Special Needs"),
                            ("OTHER", "Other"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="Health Condition",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                        verbose_name="Blood Type",
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, verbose_name="Medical Conditions"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Allergies")),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="Current Medications"),
                ),
                (
                    "special_medical_needs",
                    models.TextField(blank=True, verbose_name="Special Medical Needs"),
                ),
                (
                    "emergency_medical_contact",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Emergency Medical Contact",
                    ),
                ),
                (
                    "preferred_hospital",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Preferred Hospital"
                    ),
                ),
                (
                    "medical_insurance",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Medical Insurance"
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Insurance Policy Number",
                    ),
                ),
                (
                    "has_special_needs",
                    models.BooleanField(
                        default=False, verbose_name="Has Special Needs"
                    ),
                ),
                (
                    "special_needs_description",
                    models.TextField(
                        blank=True, verbose_name="Special Needs Description"
                    ),
                ),
                (
                    "requires_special_diet",
                    models.BooleanField(
                        default=False, verbose_name="Requires Special Diet"
                    ),
                ),
                (
                    "special_diet_details",
                    models.TextField(blank=True, verbose_name="Special Diet Details"),
                ),
                (
                    "learning_disabilities",
                    models.TextField(blank=True, verbose_name="Learning Disabilities"),
                ),
                (
                    "learning_accommodations",
                    models.TextField(
                        blank=True, verbose_name="Learning Accommodations"
                    ),
                ),
                (
                    "transportation_required",
                    models.BooleanField(
                        default=False, verbose_name="Transportation Required"
                    ),
                ),
                (
                    "transport_route",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Transport Route"
                    ),
                ),
                (
                    "pickup_point",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Pickup Point"
                    ),
                ),
                (
                    "pickup_time",
                    models.TimeField(blank=True, null=True, verbose_name="Pickup Time"),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Previous School"
                    ),
                ),
                (
                    "previous_school_address",
                    models.TextField(
                        blank=True, verbose_name="Previous School Address"
                    ),
                ),
                (
                    "transfer_reason",
                    models.TextField(blank=True, verbose_name="Reason for Transfer"),
                ),
                (
                    "transfer_certificate_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Transfer Certificate Number",
                    ),
                ),
                (
                    "previous_school_completion_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Previous School Completion Date",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/photos/%Y/%m/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DISMISSED", "Dismissed"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("DECEASED", "Deceased"),
                            ("DEFERRED", "Deferred"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Enrollment Status",
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Graduation Date"
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Withdrawal Date"
                    ),
                ),
                (
                    "admission_academic_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Grade/class level at time of admission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admitted_students",
                        to="academics.academiclevel",
                        verbose_name="Admission Academic Level",
                    ),
                ),
                (
                    "current_academic_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current grade/class level",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_students",
                        to="academics.academiclevel",
                        verbose_name="Current Academic Level",
                    ),
                ),
                (
                    "previous_academic_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_students",
                        to="academics.academiclevel",
                        verbose_name="Previous Academic Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["admission_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("STEP_FATHER", "Step Father"),
                            ("STEP_MOTHER", "Step Mother"),
                            ("FOSTER_FATHER", "Foster Father"),
                            ("FOSTER_MOTHER", "Foster Mother"),
                            ("GRANDFATHER", "Grandfather"),
                            ("GRANDMOTHER", "Grandmother"),
                            ("UNCLE", "Uncle"),
                            ("AUNT", "Aunt"),
                            ("BROTHER", "Brother"),
                            ("SISTER", "Sister"),
                            ("COUSIN", "Cousin"),
                            ("GUARDIAN", "Legal Guardian"),
                            ("SPONSOR", "Sponsor"),
                            ("FRIEND", "Family Friend"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Relationship",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Primary Guardian"
                    ),
                ),
                (
                    "is_financial_responsible",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Financial Responsibility",
                    ),
                ),
                (
                    "can_pickup",
                    models.BooleanField(
                        default=True, verbose_name="Can Pickup Student"
                    ),
                ),
                (
                    "can_authorize_medical",
                    models.BooleanField(
                        default=False, verbose_name="Can Authorize Medical Treatment"
                    ),
                ),
                (
                    "emergency_contact_priority",
                    models.PositiveSmallIntegerField(
                        default=999,
                        help_text="Lower number = higher priority (1 is highest)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                        verbose_name="Emergency Contact Priority",
                    ),
                ),
                (
                    "has_custody",
                    models.BooleanField(
                        default=False, verbose_name="Has Legal Custody"
                    ),
                ),
                (
                    "custody_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Custody Percentage",
                    ),
                ),
                (
                    "receives_academic_reports",
                    models.BooleanField(
                        default=True, verbose_name="Receives Academic Reports"
                    ),
                ),
                (
                    "receives_financial_statements",
                    models.BooleanField(
                        default=True, verbose_name="Receives Financial Statements"
                    ),
                ),
                (
                    "receives_emergency_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Receives Emergency Notifications"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "relationship_start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Relationship Start Date",
                    ),
                ),
                (
                    "relationship_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Relationship End Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_relationships",
                        to="students.guardian",
                        verbose_name="Guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_relationships",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Guardian Relationship",
                "verbose_name_plural": "Student Guardian Relationships",
                "ordering": ["emergency_contact_priority", "relationship"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="guardians",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="students.StudentGuardian",
                to="students.guardian",
            ),
        ),
        migrations.CreateModel(
            name="SiblingRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Sibling"),
                            ("HALF", "Half Sibling"),
                            ("STEP", "Step Sibling"),
                            ("ADOPTED", "Adopted Sibling"),
                            ("FOSTER", "Foster Sibling"),
                            ("COUSIN", "Cousin"),
                        ],
                        default="FULL",
                        max_length=10,
                        verbose_name="Relationship Type",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "from_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sibling_relationships",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
                (
                    "to_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_sibling_relationships",
                        to="students.student",
                        verbose_name="Sibling",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sibling Relationship",
                "verbose_name_plural": "Sibling Relationships",
                "indexes": [
                    models.Index(
                        fields=["from_student", "is_verified"],
                        name="students_si_from_st_430f11_idx",
                    ),
                    models.Index(
                        fields=["to_student", "is_verified"],
                        name="students_si_to_stud_16ff44_idx",
                    ),
                ],
                "unique_together": {("from_student", "to_student")},
            },
        ),
        migrations.CreateModel(
            name="EnrollmentStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DISMISSED", "Dismissed"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("DECEASED", "Deceased"),
                            ("DEFERRED", "Deferred"),
                        ],
                        max_length=20,
                        verbose_name="Previous Status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("DISMISSED", "Dismissed"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("DECEASED", "Deceased"),
                            ("DEFERRED", "Deferred"),
                        ],
                        max_length=20,
                        verbose_name="New Status",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Reason for Change"),
                ),
                (
                    "approval_required",
                    models.BooleanField(
                        default=False, verbose_name="Approval Required"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Is Approved"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Academic session when the status change occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.academicsession",
                        verbose_name="Academic Session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment Status History",
                "verbose_name_plural": "Enrollment Status Histories",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "effective_date"],
                        name="students_en_student_63d446_idx",
                    ),
                    models.Index(
                        fields=["new_status", "effective_date"],
                        name="students_en_new_sta_a380de_idx",
                    ),
                    models.Index(
                        fields=["academic_session"],
                        name="students_en_academi_60be76_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["student", "is_active"], name="students_st_student_2e34d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["guardian", "is_active"], name="students_st_guardia_dc547e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["is_primary"], name="students_st_is_prim_e634ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["emergency_contact_priority"],
                name="students_st_emergen_8d5a58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["is_financial_responsible"],
                name="students_st_is_fina_cd648b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentguardian",
            unique_together={("student", "guardian")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_number"], name="students_st_admissi_321db4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="students_st_first_n_e9466d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollment_status"], name="students_st_enrollm_7bd618_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["current_academic_level"], name="students_st_current_a9ef82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_date"], name="students_st_admissi_4d51f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["date_of_birth"], name="students_st_date_of_a50842_idx"
            ),
        ),
    ]
