# Generated by Django 5.2 on 2025-12-14 06:57

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "primary_phone",
                    models.CharField(max_length=20, verbose_name="Primary Phone"),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Secondary Phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=80, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Occupation"
                    ),
                ),
                (
                    "employer",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Employer"
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Work Phone"
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monthly Income",
                    ),
                ),
                ("home_address", models.TextField(verbose_name="Home Address")),
                (
                    "work_address",
                    models.TextField(blank=True, verbose_name="Work Address"),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="National ID"
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Passport Number"
                    ),
                ),
                (
                    "guardian_type",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary Guardian"),
                            ("Secondary", "Secondary Guardian"),
                            ("Emergency", "Emergency Contact"),
                            ("Financial", "Financial Sponsor"),
                        ],
                        default="Primary",
                        max_length=20,
                        verbose_name="Guardian Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="guardian_photos/",
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="students_gu_created_4757b8_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="students_gu_updated_a4cdff_idx"
                    ),
                    models.Index(
                        fields=["created_by_id"], name="students_gu_created_7d9721_idx"
                    ),
                    models.Index(
                        fields=["updated_by_id"], name="students_gu_updated_5d2f97_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Admission Number"
                    ),
                ),
                ("admission_date", models.DateField(verbose_name="Admission Date")),
                (
                    "national_student_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="National Student Number",
                    ),
                ),
                (
                    "birth_certificate_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Birth Certificate Number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Middle Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "nationality",
                    django_countries.fields.CountryField(
                        default="UG", max_length=2, verbose_name="Nationality"
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ethnicity"
                    ),
                ),
                (
                    "birth_place",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Place of Birth"
                    ),
                ),
                (
                    "birth_country",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Country of Birth",
                    ),
                ),
                (
                    "religious_affiliation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("catholic", "Catholic"),
                            ("protestant", "Protestant"),
                            ("anglican", "Anglican"),
                            ("baptist", "Baptist"),
                            ("pentecostal", "Pentecostal"),
                            ("evangelical", "Evangelical"),
                            ("adventist", "Adventist"),
                            ("islam", "Islam"),
                            ("hindu", "Hindu"),
                            ("buddhist", "Buddhist"),
                            ("jewish", "Jewish"),
                            ("traditional", "Traditional"),
                            ("none", "No Religion"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Religious Affiliation",
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Personal Email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                ("home_address", models.TextField(verbose_name="Home Address")),
                (
                    "mailing_address",
                    models.TextField(blank=True, verbose_name="Mailing Address"),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="District"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Region/Province"
                    ),
                ),
                (
                    "country_of_residence",
                    django_countries.fields.CountryField(
                        default="UG", max_length=2, verbose_name="Country of Residence"
                    ),
                ),
                (
                    "health_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("chronic", "Chronic Condition"),
                            ("recovering", "Recovering"),
                            ("special_Needs", "Special Needs"),
                            ("other", "Other"),
                        ],
                        default="Good",
                        max_length=20,
                        verbose_name="Health Condition",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        max_length=10,
                        verbose_name="Blood Type",
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, verbose_name="Medical Conditions"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Allergies")),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="Current Medications"),
                ),
                (
                    "special_medical_needs",
                    models.TextField(blank=True, verbose_name="Special Medical Needs"),
                ),
                (
                    "emergency_medical_contact",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Emergency Medical Contact",
                    ),
                ),
                (
                    "preferred_hospital",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Preferred Hospital"
                    ),
                ),
                (
                    "medical_insurance",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Medical Insurance"
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Insurance Policy Number",
                    ),
                ),
                (
                    "has_special_needs",
                    models.BooleanField(
                        default=False, verbose_name="Has Special Needs"
                    ),
                ),
                (
                    "special_needs_description",
                    models.TextField(
                        blank=True, verbose_name="Special Needs Description"
                    ),
                ),
                (
                    "requires_special_diet",
                    models.BooleanField(
                        default=False, verbose_name="Requires Special Diet"
                    ),
                ),
                (
                    "special_diet_details",
                    models.TextField(blank=True, verbose_name="Special Diet Details"),
                ),
                (
                    "learning_disabilities",
                    models.TextField(blank=True, verbose_name="Learning Disabilities"),
                ),
                (
                    "learning_accommodations",
                    models.TextField(
                        blank=True, verbose_name="Learning Accommodations"
                    ),
                ),
                (
                    "transportation_required",
                    models.BooleanField(
                        default=False, verbose_name="Transportation Required"
                    ),
                ),
                (
                    "transport_route",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Transport Route"
                    ),
                ),
                (
                    "pickup_point",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Pickup Point"
                    ),
                ),
                (
                    "pickup_time",
                    models.TimeField(blank=True, null=True, verbose_name="Pickup Time"),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Previous School"
                    ),
                ),
                (
                    "previous_school_address",
                    models.TextField(
                        blank=True, verbose_name="Previous School Address"
                    ),
                ),
                (
                    "transfer_reason",
                    models.TextField(blank=True, verbose_name="Reason for Transfer"),
                ),
                (
                    "transfer_certificate_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Transfer Certificate Number",
                    ),
                ),
                (
                    "previous_school_completion_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Previous School Completion Date",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/photos",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("dismissed", "Dismissed"),
                            ("graduated", "Graduated"),
                            ("transferred", "Transferred"),
                            ("withdrawn", "Withdrawn"),
                            ("deceased", "Deceased"),
                            ("deferred", "Deferred"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Enrollment Status",
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Graduation Date"
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Withdrawal Date"
                    ),
                ),
                (
                    "admission_academic_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admitted_students",
                        to="academics.academiclevel",
                        verbose_name="Admission Academic Level",
                    ),
                ),
                (
                    "current_academic_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_students",
                        to="academics.academiclevel",
                        verbose_name="Current Academic Level",
                    ),
                ),
                (
                    "guardians",
                    models.ManyToManyField(blank=True, to="students.guardian"),
                ),
                (
                    "previous_academic_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_students",
                        to="academics.academiclevel",
                        verbose_name="Previous Academic Level",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="students_st_created_78a19f_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="students_st_updated_69dec6_idx"
                    ),
                    models.Index(
                        fields=["created_by_id"], name="students_st_created_a09b6c_idx"
                    ),
                    models.Index(
                        fields=["updated_by_id"], name="students_st_updated_a7179c_idx"
                    ),
                ],
            },
        ),
    ]
