# Generated by Django 5.2 on 2025-12-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Admission Number"
            ),
        ),
    ]
