# Generated by Django 5.2 on 2025-12-15 06:04

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_admission_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="country_of_residence",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Country of Residence"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="nationality",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Nationality"
            ),
        ),
    ]
