# Generated by Django 5.2 on 2025-12-17 12:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0002_academicsession_class_classroom_classsubject_holiday_and_more",
        ),
        ("hr", "0001_initial"),
        ("students", "0003_alter_student_country_of_residence_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardingEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "boarding_type",
                    models.CharField(
                        choices=[
                            ("FULL_BOARDER", "Full Boarder"),
                            ("WEEKLY_BOARDER", "Weekly Boarder"),
                            ("FLEXI_BOARDER", "Flexible Boarder"),
                        ],
                        help_text="Type of boarding arrangement for this student",
                        max_length=20,
                        verbose_name="Boarding Type",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Room Number"
                    ),
                ),
                (
                    "bed_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Bed Number"
                    ),
                ),
                (
                    "boarding_roll_number",
                    models.CharField(
                        blank=True,
                        help_text="Roll number for dormitory attendance and management",
                        max_length=20,
                        verbose_name="Boarding Roll Number",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(verbose_name="Boarding Enrollment Date"),
                ),
                (
                    "effective_start_date",
                    models.DateField(
                        help_text="Date when boarding actually starts",
                        verbose_name="Effective Start Date",
                    ),
                ),
                (
                    "effective_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when boarding ends",
                        null=True,
                        verbose_name="Effective End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                            ("COMPLETED", "Completed"),
                            ("PENDING", "Pending Approval"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "guardian_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether guardian has provided written consent for boarding",
                        verbose_name="Guardian Consent",
                    ),
                ),
                (
                    "consent_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Consent Date"
                    ),
                ),
                (
                    "consent_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="boarding_consents/",
                        verbose_name="Consent Document",
                    ),
                ),
                (
                    "boarding_days",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of days when student boards (required for FLEXI_BOARDER)",
                        null=True,
                        verbose_name="Boarding Days",
                    ),
                ),
                (
                    "dietary_requirements",
                    models.TextField(blank=True, verbose_name="Dietary Requirements"),
                ),
                (
                    "medical_requirements",
                    models.TextField(blank=True, verbose_name="Medical Requirements"),
                ),
                (
                    "special_accommodations",
                    models.TextField(blank=True, verbose_name="Special Accommodations"),
                ),
                (
                    "emergency_contact_during_boarding",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Emergency Contact During Boarding",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Emergency Contact Name",
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Emergency Contact Relationship",
                    ),
                ),
                (
                    "reason_for_boarding",
                    models.TextField(blank=True, verbose_name="Reason for Boarding"),
                ),
                (
                    "termination_reason",
                    models.TextField(blank=True, verbose_name="Termination Reason"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Administrative Notes"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Boarding Enrollment",
                "verbose_name_plural": "Boarding Enrollments",
                "ordering": [
                    "-academic_session__start_date",
                    "dormitory",
                    "boarding_roll_number",
                    "student__last_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Dormitory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Dormitory Name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Dormitory Code"
                    ),
                ),
                (
                    "dormitory_type",
                    models.CharField(
                        choices=[
                            ("BOYS", "Boys Dormitory"),
                            ("GIRLS", "Girls Dormitory"),
                            ("MIXED", "Mixed Dormitory"),
                            ("STAFF", "Staff Quarters"),
                        ],
                        max_length=10,
                        verbose_name="Dormitory Type",
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Building"
                    ),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="Floor"),
                ),
                (
                    "wing",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Wing/Section"
                    ),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(verbose_name="Total Capacity"),
                ),
                (
                    "current_occupancy",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Current Occupancy"
                    ),
                ),
                (
                    "room_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Rooms"
                    ),
                ),
                (
                    "beds_per_room",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Beds per Room"
                    ),
                ),
                (
                    "has_bathroom",
                    models.BooleanField(default=True, verbose_name="Has Bathroom"),
                ),
                (
                    "has_study_area",
                    models.BooleanField(default=False, verbose_name="Has Study Area"),
                ),
                (
                    "has_common_room",
                    models.BooleanField(default=False, verbose_name="Has Common Room"),
                ),
                (
                    "has_laundry",
                    models.BooleanField(
                        default=False, verbose_name="Has Laundry Facilities"
                    ),
                ),
                (
                    "has_kitchen",
                    models.BooleanField(default=False, verbose_name="Has Kitchen"),
                ),
                (
                    "has_wifi",
                    models.BooleanField(default=False, verbose_name="Has WiFi"),
                ),
                (
                    "has_security",
                    models.BooleanField(default=True, verbose_name="Has Security"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_available_for_new_admissions",
                    models.BooleanField(
                        default=True, verbose_name="Available for New Admissions"
                    ),
                ),
                (
                    "maintenance_status",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent Condition"),
                            ("GOOD", "Good Condition"),
                            ("FAIR", "Fair Condition"),
                            ("NEEDS_REPAIR", "Needs Repair"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("CONDEMNED", "Condemned"),
                        ],
                        default="GOOD",
                        max_length=20,
                        verbose_name="Maintenance Status",
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Maintenance Date"
                    ),
                ),
                (
                    "next_maintenance_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Maintenance Due"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "facilities_description",
                    models.TextField(blank=True, verbose_name="Facilities Description"),
                ),
                (
                    "rules_and_regulations",
                    models.TextField(blank=True, verbose_name="Rules and Regulations"),
                ),
                (
                    "emergency_procedures",
                    models.TextField(blank=True, verbose_name="Emergency Procedures"),
                ),
                (
                    "dormitory_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Dormitory Phone"
                    ),
                ),
                (
                    "dormitory_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Dormitory Email"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dormitory",
                "verbose_name_plural": "Dormitories",
                "ordering": ["dormitory_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentClassEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("enrollment_date", models.DateField(verbose_name="Enrollment Date")),
                (
                    "roll_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Roll Number"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "enrollment_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Admission"),
                            ("CONTINUING", "Continuing Student"),
                            ("TRANSFER_IN", "Transfer from Another School"),
                            ("REPEATER", "Repeating Class"),
                            ("READMISSION", "Readmitted Student"),
                            ("PROMOTED", "Promoted from Previous Level"),
                            ("TRANSFERRED", "Transferred Between Classes"),
                            ("REPEATED", "Repeated Current Level"),
                            ("INTERNAL_TRANSFER", "Internal Class Transfer"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Enrollment Type",
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completion Date"
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped Out"),
                            ("TRANSFERRED", "Transferred"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ONGOING",
                        max_length=20,
                        verbose_name="Completion Status",
                    ),
                ),
                (
                    "enrollment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this enrollment",
                        verbose_name="Enrollment Notes",
                    ),
                ),
                (
                    "progression_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal Progression"),
                            ("SKIP", "Level Skipped"),
                            ("REPEAT", "Level Repeated"),
                            ("LATERAL", "Lateral Transfer"),
                            ("READMISSION", "Readmission"),
                        ],
                        default="NORMAL",
                        help_text="Type of academic progression this enrollment represents",
                        max_length=20,
                        verbose_name="Progression Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Class Enrollment",
                "verbose_name_plural": "Student Class Enrollments",
                "ordering": ["class_instance", "roll_number", "student__last_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Created From IP"
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Updated From IP"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Step_Father", "Step Father"),
                            ("Step_Mother", "Step Mother"),
                            ("Foster_Father", "Foster Father"),
                            ("Foster_Mother", "Foster Mother"),
                            ("Grandfather", "Grandfather"),
                            ("Grandmother", "Grandmother"),
                            ("Uncle", "Uncle"),
                            ("Aunt", "Aunt"),
                            ("Brother", "Brother"),
                            ("Sister", "Sister"),
                            ("Cousin", "Cousin"),
                            ("Guardian", "Legal Guardian"),
                            ("Sponsor", "Sponsor"),
                            ("Friend", "Family Friend"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Relationship",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Guardian"),
                ),
                (
                    "is_financial_responsible",
                    models.BooleanField(
                        default=False, verbose_name="Financial Responsibility"
                    ),
                ),
                (
                    "can_pickup",
                    models.BooleanField(
                        default=True, verbose_name="Can Pickup Student"
                    ),
                ),
                (
                    "can_authorize_medical",
                    models.BooleanField(
                        default=False, verbose_name="Can Authorize Medical Treatment"
                    ),
                ),
                (
                    "emergency_contact_priority",
                    models.PositiveSmallIntegerField(
                        default=999,
                        help_text="Lower number = higher priority",
                        verbose_name="Emergency Contact Priority",
                    ),
                ),
                (
                    "has_custody",
                    models.BooleanField(
                        default=False, verbose_name="Has Legal Custody"
                    ),
                ),
                (
                    "custody_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Custody Percentage",
                    ),
                ),
                (
                    "receives_academic_reports",
                    models.BooleanField(
                        default=True, verbose_name="Receives Academic Reports"
                    ),
                ),
                (
                    "receives_financial_statements",
                    models.BooleanField(
                        default=True, verbose_name="Receives Financial Statements"
                    ),
                ),
                (
                    "receives_emergency_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Receives Emergency Notifications"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "relationship_start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Relationship Start Date",
                    ),
                ),
                (
                    "relationship_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Relationship End Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Guardian Relationship",
                "verbose_name_plural": "Student Guardian Relationships",
                "ordering": ["emergency_contact_priority", "relationship"],
            },
        ),
        migrations.AlterModelOptions(
            name="guardian",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Guardian",
                "verbose_name_plural": "Guardians",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["admission_number"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.RemoveIndex(
            model_name="guardian",
            name="students_gu_created_4757b8_idx",
        ),
        migrations.RemoveIndex(
            model_name="guardian",
            name="students_gu_updated_a4cdff_idx",
        ),
        migrations.RemoveIndex(
            model_name="guardian",
            name="students_gu_created_7d9721_idx",
        ),
        migrations.RemoveIndex(
            model_name="guardian",
            name="students_gu_updated_5d2f97_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_created_78a19f_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_updated_69dec6_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_created_a09b6c_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_st_updated_a7179c_idx",
        ),
        migrations.AddIndex(
            model_name="guardian",
            index=models.Index(
                fields=["guardian_type"], name="students_gu_guardia_62341c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardian",
            index=models.Index(
                fields=["is_active"], name="students_gu_is_acti_b2eec2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardian",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="students_gu_first_n_0bd4ca_idx",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_enrollments",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_boarding_enrollments",
                to="hr.staff",
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="consenting_guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boarding_consents",
                to="students.guardian",
                verbose_name="Consenting Guardian",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_enrollments",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="dormitory",
            name="assistant_dormitory_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assisted_dormitories",
                to="hr.staff",
                verbose_name="Assistant Dormitory Master",
            ),
        ),
        migrations.AddField(
            model_name="dormitory",
            name="dormitory_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_dormitories",
                to="hr.staff",
                verbose_name="Dormitory Master",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="dormitory",
            field=models.ForeignKey(
                help_text="Dormitory assignment is required for all boarding students",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boarding_enrollments",
                to="students.dormitory",
                verbose_name="Dormitory",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_class_enrollments",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="class_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.class",
                verbose_name="Class",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="previous_enrollment",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous class enrollment before promotion/transfer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_enrollment",
                to="students.studentclassenrollment",
                verbose_name="Previous Enrollment",
            ),
        ),
        migrations.AddField(
            model_name="studentclassenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="guardian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_relationships",
                to="students.guardian",
                verbose_name="Guardian",
            ),
        ),
        migrations.AddField(
            model_name="studentguardian",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardian_relationships",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardians",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="students.StudentGuardian",
                through_fields=("student", "guardian"),
                to="students.guardian",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_number"], name="students_st_admissi_321db4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="students_st_first_n_e9466d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollment_status"], name="students_st_enrollm_7bd618_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["current_academic_level"], name="students_st_current_a9ef82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_date"], name="students_st_admissi_4d51f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dormitory",
            index=models.Index(
                fields=["dormitory_type"], name="students_do_dormito_c03dc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dormitory",
            index=models.Index(
                fields=["is_active"], name="students_do_is_acti_5d3e64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dormitory",
            index=models.Index(fields=["code"], name="students_do_code_3baca7_idx"),
        ),
        migrations.AddIndex(
            model_name="dormitory",
            index=models.Index(
                fields=["maintenance_status"], name="students_do_mainten_f0f94c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["student", "academic_session"],
                name="students_bo_student_e93fc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["boarding_type"], name="students_bo_boardin_e3ef2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(fields=["status"], name="students_bo_status_70ebae_idx"),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["dormitory"], name="students_bo_dormito_5b3e32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["enrollment_date"], name="students_bo_enrollm_6488e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["effective_start_date"], name="students_bo_effecti_f8d24c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["boarding_roll_number"], name="students_bo_boardin_c70dee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["dormitory", "academic_session", "boarding_roll_number"],
                name="students_bo_dormito_2a6317_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["student", "status"], name="students_bo_student_f77119_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["dormitory", "status"], name="students_bo_dormito_b6ddc6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardingenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "PENDING"])),
                fields=("student", "academic_session"),
                name="unique_active_boarding_per_student_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardingenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("boarding_roll_number__isnull", False),
                    models.Q(("boarding_roll_number", ""), _negated=True),
                    ("status", "ACTIVE"),
                ),
                fields=("dormitory", "academic_session", "boarding_roll_number"),
                name="unique_boarding_roll_number_per_dormitory_session",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["student", "academic_session"],
                name="students_st_student_24a03e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["class_instance", "is_active"],
                name="students_st_class_i_abd8ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["enrollment_type"], name="students_st_enrollm_db18db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["completion_status"], name="students_st_complet_8a599d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["enrollment_date"], name="students_st_enrollm_8d474b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["student", "is_active", "completion_status"],
                name="students_st_student_1e2527_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["progression_type"], name="students_st_progres_9a5a48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["academic_session", "is_active", "completion_status"],
                name="students_st_academi_5e7789_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["roll_number"], name="students_st_roll_nu_85b356_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentclassenrollment",
            index=models.Index(
                fields=["class_instance", "academic_session", "roll_number"],
                name="students_st_class_i_f72bc2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("completion_status", "ONGOING"), ("is_active", True)
                ),
                fields=("student", "academic_session"),
                name="unique_active_enrollment_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "class_instance", "academic_session"),
                name="unique_student_class_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentclassenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("roll_number__isnull", False),
                    models.Q(("roll_number", ""), _negated=True),
                ),
                fields=("class_instance", "academic_session", "roll_number"),
                name="unique_roll_number_per_class_session",
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["student", "is_active"], name="students_st_student_2e34d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["guardian", "is_active"], name="students_st_guardia_dc547e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["is_primary"], name="students_st_is_prim_e634ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["emergency_contact_priority"],
                name="students_st_emergen_8d5a58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentguardian",
            index=models.Index(
                fields=["is_financial_responsible"],
                name="students_st_is_fina_cd648b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentguardian",
            unique_together={("student", "guardian")},
        ),
    ]
