# Generated by Django 5.2 on 2025-12-30 10:47

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoreAccountMappings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Core Account Mappings",
                "verbose_name_plural": "Core Account Mappings",
            },
        ),
        migrations.CreateModel(
            name="ExpenseAccountMappings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Account Mappings",
                "verbose_name_plural": "Expense Account Mappings",
            },
        ),
        migrations.CreateModel(
            name="FinancialSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "school_currency",
                    models.CharField(
                        default="UGX",
                        help_text="Primary currency for this school (ISO 4217 code)",
                        max_length=3,
                        verbose_name="School Currency",
                    ),
                ),
                (
                    "currency_position",
                    models.CharField(
                        choices=[
                            ("BEFORE", "Before amount (UGX 100.00)"),
                            ("AFTER", "After amount (100.00 UGX)"),
                            ("BEFORE_NO_SPACE", "Before, no space (UGX100.00)"),
                            ("AFTER_NO_SPACE", "After, no space (100.00UGX)"),
                        ],
                        default="BEFORE",
                        help_text="How to display currency symbols",
                        max_length=20,
                        verbose_name="Currency Position",
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Number of decimal places for currency display (0-4)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Decimal Places",
                    ),
                ),
                (
                    "use_thousand_separator",
                    models.BooleanField(
                        default=True,
                        help_text="Display numbers with comma separators (e.g., 1,000,000)",
                        verbose_name="Use Thousand Separator",
                    ),
                ),
                (
                    "invoice_prefix",
                    models.CharField(
                        blank=True,
                        default="INV",
                        help_text="Prefix for invoice numbers (leave blank for no prefix)",
                        max_length=10,
                        verbose_name="Invoice Number Prefix",
                    ),
                ),
                (
                    "include_year_in_invoice_number",
                    models.BooleanField(
                        default=True,
                        help_text="Include year in invoice number format",
                        verbose_name="Include Year in Invoice Number",
                    ),
                ),
                (
                    "payment_prefix",
                    models.CharField(
                        blank=True,
                        default="PMT",
                        help_text="Prefix for payment numbers (leave blank for no prefix)",
                        max_length=10,
                        verbose_name="Payment Number Prefix",
                    ),
                ),
                (
                    "include_year_in_payment_number",
                    models.BooleanField(
                        default=True,
                        help_text="Include year in payment number format",
                        verbose_name="Include Year in Payment Number",
                    ),
                ),
                (
                    "receipt_prefix",
                    models.CharField(
                        blank=True,
                        default="RCPT",
                        help_text="Prefix for receipt numbers (leave blank for no prefix)",
                        max_length=10,
                        verbose_name="Receipt Number Prefix",
                    ),
                ),
                (
                    "expense_prefix",
                    models.CharField(
                        blank=True,
                        default="EXP",
                        help_text="Prefix for expense numbers (leave blank for no prefix)",
                        max_length=10,
                        verbose_name="Expense Number Prefix",
                    ),
                ),
                (
                    "include_year_in_expense_number",
                    models.BooleanField(
                        default=True,
                        help_text="Include year in expense number format",
                        verbose_name="Include Year in Expense Number",
                    ),
                ),
                (
                    "default_payment_terms_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Default number of days for payment after invoice generation",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Default Payment Terms (Days)",
                    ),
                ),
                (
                    "late_fee_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Apply late fees to overdue invoices",
                        verbose_name="Enable Late Fees",
                    ),
                ),
                (
                    "late_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Percentage charged on overdue amounts (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Late Fee Percentage",
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days after due date before late fees apply",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Grace Period (Days)",
                    ),
                ),
                (
                    "minimum_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="Minimum amount for any payment transaction in school currency",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Payment Amount",
                    ),
                ),
                (
                    "allow_partial_payments",
                    models.BooleanField(
                        default=True,
                        help_text="Allow parents to make partial payments on invoices",
                        verbose_name="Allow Partial Payments",
                    ),
                ),
                (
                    "auto_apply_scholarships",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically apply approved scholarships to invoices",
                        verbose_name="Auto Apply Scholarships",
                    ),
                ),
                (
                    "scholarship_approval_required",
                    models.BooleanField(
                        default=False,
                        help_text="Require approval for scholarships",
                        verbose_name="Scholarship Approval Required",
                    ),
                ),
                (
                    "auto_apply_discounts",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically apply approved discounts to invoices",
                        verbose_name="Auto Apply Discounts",
                    ),
                ),
                (
                    "discount_approval_required",
                    models.BooleanField(
                        default=True,
                        help_text="Require approval for manual discounts above threshold",
                        verbose_name="Discount Approval Required",
                    ),
                ),
                (
                    "discount_approval_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100000.00"),
                        help_text="Discount amounts above this require approval",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Discount Approval Threshold",
                    ),
                ),
                (
                    "early_payment_discount_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Offer discount for early payment",
                        verbose_name="Enable Early Payment Discount",
                    ),
                ),
                (
                    "early_payment_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Percentage discount for early payment",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Early Payment Discount Percentage",
                    ),
                ),
                (
                    "early_payment_discount_days",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Days before due date to qualify for early payment discount",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Early Payment Discount Days",
                    ),
                ),
                (
                    "expense_approval_required",
                    models.BooleanField(
                        default=True,
                        help_text="Require approval for expenses above limit",
                        verbose_name="Expense Approval Required",
                    ),
                ),
                (
                    "expense_approval_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100000.00"),
                        help_text="Expense amounts above this require approval",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Expense Approval Limit",
                    ),
                ),
                (
                    "require_payment_confirmation",
                    models.BooleanField(
                        default=False,
                        help_text="Require staff to confirm payment receipt before processing",
                        verbose_name="Require Payment Confirmation",
                    ),
                ),
                (
                    "require_expense_receipts",
                    models.BooleanField(
                        default=True,
                        help_text="Require receipts/attachments for expense claims",
                        verbose_name="Require Expense Receipts",
                    ),
                ),
                (
                    "require_purchase_orders",
                    models.BooleanField(
                        default=False,
                        help_text="Require PO numbers for vendor invoices",
                        verbose_name="Require Purchase Orders",
                    ),
                ),
                (
                    "send_invoice_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Email invoices to parents",
                        verbose_name="Send Invoice Emails",
                    ),
                ),
                (
                    "send_payment_confirmations",
                    models.BooleanField(
                        default=True,
                        help_text="Email payment receipts to parents",
                        verbose_name="Send Payment Confirmations",
                    ),
                ),
                (
                    "send_overdue_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Send automatic reminders for overdue payments",
                        verbose_name="Send Overdue Reminders",
                    ),
                ),
                (
                    "overdue_reminder_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days between overdue payment reminders",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Overdue Reminder Frequency (Days)",
                    ),
                ),
                (
                    "send_sms_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="Send SMS notifications for financial transactions",
                        verbose_name="Send SMS Notifications",
                    ),
                ),
                (
                    "include_tax_in_prices",
                    models.BooleanField(
                        default=False,
                        help_text="Whether prices include tax or tax is added on top",
                        verbose_name="Include Tax in Prices",
                    ),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="Default tax rate to apply if no specific rate is set",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Default Tax Rate (%)",
                    ),
                ),
                (
                    "multi_currency_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Allow transactions in multiple currencies",
                        verbose_name="Enable Multi-Currency",
                    ),
                ),
                (
                    "auto_generate_recurring_invoices",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically generate recurring invoices on schedule",
                        verbose_name="Auto-Generate Recurring Invoices",
                    ),
                ),
                (
                    "invoice_aging_periods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Custom aging periods for AR aging reports (days)",
                        verbose_name="Invoice Aging Periods",
                    ),
                ),
                (
                    "bad_debt_write_off_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum amount to require approval for write-offs",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Bad Debt Write-Off Threshold",
                    ),
                ),
                (
                    "auto_write_off_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Days overdue before invoice can be written off",
                        validators=[django.core.validators.MinValueValidator(90)],
                        verbose_name="Auto Write-Off Days",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Settings",
                "verbose_name_plural": "Financial Settings",
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Term 1 2024 Fiscal Period', 'Q1 2024', 'April Break 2024'",
                        max_length=100,
                        verbose_name="Period Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code e.g., 'FP_2024_T1', 'Q1_2024', 'BREAK_APR_2024'",
                        max_length=20,
                        unique=True,
                        verbose_name="Period Code",
                    ),
                ),
                (
                    "period_number",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=1,
                        help_text="Sequential number within fiscal year (1, 2, 3... or 1.5 for break periods)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                        verbose_name="Period Number",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("ACADEMIC_ALIGNED", "Academic-Aligned Period"),
                            ("BREAK_PERIOD", "Break/Holiday Period"),
                            ("GRACE_PERIOD", "Grace Period"),
                            ("MONTHLY", "Monthly Period"),
                            ("QUARTERLY", "Quarterly Period"),
                            ("TERTIAL", "Tertial Period"),
                            ("SEMI_ANNUAL", "Semi-Annual Period"),
                            ("ANNUAL", "Annual Period"),
                            ("CUSTOM", "Custom Period"),
                        ],
                        db_index=True,
                        default="ACADEMIC_ALIGNED",
                        help_text="Type of fiscal period",
                        max_length=20,
                        verbose_name="Period Type",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="When this fiscal period begins",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True,
                        help_text="When this fiscal period ends",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this period is currently active for transactions",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Period has been closed (month-end/period-end close)",
                        verbose_name="Is Closed",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Period is locked for audit compliance (no changes allowed)",
                        verbose_name="Is Locked",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this period was closed",
                        null=True,
                        verbose_name="Closed At",
                    ),
                ),
                (
                    "closed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who closed this period",
                        max_length=50,
                        null=True,
                        verbose_name="Closed By",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this period was locked",
                        null=True,
                        verbose_name="Locked At",
                    ),
                ),
                (
                    "locked_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who locked this period",
                        max_length=50,
                        null=True,
                        verbose_name="Locked By",
                    ),
                ),
                (
                    "allow_advance_payments",
                    models.BooleanField(
                        default=True,
                        help_text="Accept payments for future academic sessions",
                        verbose_name="Allow Advance Payments",
                    ),
                ),
                (
                    "allow_arrears_payments",
                    models.BooleanField(
                        default=True,
                        help_text="Accept payments for past academic sessions",
                        verbose_name="Allow Arrears Payments",
                    ),
                ),
                (
                    "allow_invoice_generation",
                    models.BooleanField(
                        default=True,
                        help_text="Allow creating new invoices in this period",
                        verbose_name="Allow Invoice Generation",
                    ),
                ),
                (
                    "allow_refunds",
                    models.BooleanField(
                        default=True,
                        help_text="Allow processing refunds in this period",
                        verbose_name="Allow Refunds",
                    ),
                ),
                (
                    "require_approval_for_transactions",
                    models.BooleanField(
                        default=False,
                        help_text="Require manager approval for transactions in this period",
                        verbose_name="Require Approval",
                    ),
                ),
                (
                    "auto_close_date",
                    models.DateField(
                        blank=True,
                        help_text="Automatically close this period on this date",
                        null=True,
                        verbose_name="Auto Close Date",
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Days beyond end_date when transactions are still accepted",
                        verbose_name="Grace Period Days",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this fiscal period",
                        verbose_name="Description",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for accounting team",
                        verbose_name="Internal Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Period",
                "verbose_name_plural": "Fiscal Periods",
                "ordering": ["fiscal_year", "period_number"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., '2024', '2024/2025', 'Academic Year 2024-2025'",
                        max_length=50,
                        unique=True,
                        verbose_name="Academic Year Name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code e.g., 'AY2024', '2024-25'",
                        max_length=20,
                        unique=True,
                        verbose_name="Academic Year Code",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="When this academic year begins",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True,
                        help_text="When this academic year ends",
                        verbose_name="End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only one academic year can be active at a time",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Academic year has been closed and finalized",
                        verbose_name="Is Closed",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Academic year is locked for editing (for auditing)",
                        verbose_name="Is Locked",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this academic year",
                        verbose_name="Description",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this academic year was closed",
                        null=True,
                        verbose_name="Closed At",
                    ),
                ),
                (
                    "closed_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who closed this academic year",
                        max_length=50,
                        null=True,
                        verbose_name="Closed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Payment Method Name"
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CARD", "Card Payment"),
                            ("DIRECT_DEBIT", "Direct Debit"),
                            ("STANDING_ORDER", "Standing Order"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Method Type",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Method Code"
                    ),
                ),
                (
                    "mobile_money_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN", "MTN Mobile Money"),
                            ("AIRTEL", "Airtel Money"),
                            ("AFRICELL", "Africell Money"),
                            ("SAFARICOM", "M-Pesa (Safaricom)"),
                            ("VODACOM", "M-Pesa (Vodacom)"),
                            ("TIGO", "Tigo Pesa"),
                            ("ORANGE", "Orange Money"),
                            ("OTHER", "Other Provider"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Mobile Money Provider",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bank Name"
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Bank Account Number"
                    ),
                ),
                (
                    "bank_branch",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Bank Branch"
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="SWIFT/BIC Code"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Is Default"),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires Approval"
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Minimum Amount",
                    ),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Maximum Amount",
                    ),
                ),
                (
                    "has_transaction_fee",
                    models.BooleanField(
                        default=False, verbose_name="Has Transaction Fee"
                    ),
                ),
                (
                    "transaction_fee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIXED", "Fixed"),
                            ("PERCENTAGE", "Percentage"),
                            ("TIERED", "Tiered"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Fee Type",
                    ),
                ),
                (
                    "transaction_fee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Fee Amount",
                    ),
                ),
                (
                    "fee_bearer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PARENT", "Parent"),
                            ("SCHOOL", "School"),
                            ("SHARED", "Shared"),
                        ],
                        default="PARENT",
                        max_length=20,
                        verbose_name="Fee Bearer",
                    ),
                ),
                (
                    "processing_time",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Processing Time"
                    ),
                ),
                (
                    "requires_reference",
                    models.BooleanField(
                        default=False, verbose_name="Requires Reference Number"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon CSS Class"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Color Code"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Payment Instructions"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollAccountMappings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Account Mappings",
                "verbose_name_plural": "Payroll Account Mappings",
            },
        ),
        migrations.CreateModel(
            name="RevenueAccountMappings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Account Mappings",
                "verbose_name_plural": "Revenue Account Mappings",
            },
        ),
        migrations.CreateModel(
            name="SchoolConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "term_system",
                    models.CharField(
                        choices=[
                            ("term", "Terms (3 per year) - British/Commonwealth"),
                            ("semester", "Semesters (2 per year) - North American"),
                            ("quarter", "Quarters (4 per year)"),
                            (
                                "trimester",
                                "Trimesters (3 per year) - Same as Terms, different name",
                            ),
                            ("module", "Modules (6-8 per year)"),
                            ("block", "Block Schedule (4-6 per year)"),
                            ("yearlong", "Year-long Program (1 per year)"),
                            ("intensive", "Intensive Programs (8-12 per year)"),
                            ("custom", "Custom System"),
                        ],
                        default="term",
                        help_text="The academic period system used by the school. Note: 'Terms' and 'Trimesters' both mean 3 periods per year.",
                        max_length=15,
                        verbose_name="Academic Period System",
                    ),
                ),
                (
                    "periods_per_year",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of academic periods in one academic year (1-20)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Periods Per Year",
                    ),
                ),
                (
                    "period_naming_convention",
                    models.CharField(
                        choices=[
                            ("numeric", "Numeric (Term 1, Term 2, etc.)"),
                            ("ordinal", "Ordinal (First Term, Second Term, etc.)"),
                            ("seasonal", "Seasonal (Fall, Spring, Summer)"),
                            ("monthly", "Monthly (January, February, etc.)"),
                            ("alpha", "Alphabetical (Term A, Term B, etc.)"),
                            ("roman", "Roman Numerals (Term I, Term II, etc.)"),
                            ("custom", "Custom Names"),
                        ],
                        default="numeric",
                        max_length=20,
                        verbose_name="Period Naming Convention",
                    ),
                ),
                (
                    "custom_period_names",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Custom names for each period position. E.g., {"1": "Fall Semester", "2": "Spring Semester"}',
                        verbose_name="Custom Period Names",
                    ),
                ),
                (
                    "academic_year_type",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar Year (Jan-Dec)"),
                            ("northern", "Northern Hemisphere (Sep-Jun)"),
                            ("southern", "Southern Hemisphere (Feb-Nov)"),
                            ("tropical", "Tropical Regions (Jan-Nov)"),
                            ("east_africa", "East African Calendar (Jan-Nov)"),
                            ("west_africa", "West African Calendar (Sep-Jul)"),
                            ("sahel", "Sahel Region (Oct-Jun)"),
                            ("financial", "Financial Year (Apr-Mar)"),
                            ("custom", "Custom Year Dates"),
                        ],
                        default="east_africa",
                        help_text="When your academic year typically runs",
                        max_length=15,
                        verbose_name="Academic Year Type",
                    ),
                ),
                (
                    "academic_year_start_month",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        default=2,
                        help_text="Month when academic year typically starts (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Academic Year Start Month",
                    ),
                ),
                (
                    "academic_year_start_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Day when academic year typically starts",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Academic Year Start Day",
                    ),
                ),
                (
                    "operational_timezone",
                    models.CharField(
                        default="Africa/Kampala",
                        help_text="Timezone for academic schedules, deadlines, and automated processes. Critical for: fee due dates, exam schedules, attendance marking, report generation, and all date-based business logic.",
                        max_length=63,
                        verbose_name="Operational Timezone",
                    ),
                ),
                (
                    "regional_season_type",
                    models.CharField(
                        choices=[
                            ("temperate", "Temperate (Spring/Summer/Fall/Winter)"),
                            ("tropical_wet_dry", "Tropical (Wet/Dry Seasons)"),
                            ("desert", "Desert (Hot/Cool Seasons)"),
                            ("equatorial", "Equatorial (Year-round)"),
                            ("monsoon", "Monsoon (Pre/Monsoon/Post)"),
                            ("custom_regional", "Custom Regional Seasons"),
                        ],
                        default="equatorial",
                        help_text="Climate-based season naming for your region",
                        max_length=20,
                        verbose_name="Regional Season Type",
                    ),
                ),
                (
                    "custom_season_names",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Regional season names. E.g., {'1': 'Harmattan', '2': 'Rainy Season'}",
                        verbose_name="Custom Season Names",
                    ),
                ),
                (
                    "default_period_duration_weeks",
                    models.PositiveIntegerField(
                        default=13,
                        help_text="Typical duration of each academic period in weeks (used as a suggestion when creating sessions)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(52),
                        ],
                        verbose_name="Default Period Duration (weeks)",
                    ),
                ),
                (
                    "enable_automatic_reminders",
                    models.BooleanField(
                        default=True,
                        help_text="Send automatic payment and deadline reminders",
                        verbose_name="Enable Automatic Reminders",
                    ),
                ),
                (
                    "enable_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Send SMS notifications to parents and students",
                        verbose_name="Enable SMS Notifications",
                    ),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send email notifications",
                        verbose_name="Enable Email Notifications",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Configuration",
                "verbose_name_plural": "School Configuration",
            },
        ),
        migrations.CreateModel(
            name="SpecialAccountMappings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Account Mappings",
                "verbose_name_plural": "Special Account Mappings",
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tax Name")),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("WHT_INTEREST", "Withholding Tax on Interest"),
                            ("WHT_DIVIDEND", "Withholding Tax on Dividend"),
                            ("VAT", "Value Added Tax"),
                            ("LOCAL_SERVICE", "Local Service Tax"),
                            ("EDUCATION_TAX", "Education Tax"),
                            ("OTHER", "Other Tax"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tax Type",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Tax Rate (%)",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(db_index=True, verbose_name="Effective From"),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Effective To",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "applies_to_fees",
                    models.BooleanField(
                        default=True, verbose_name="Applies to School Fees"
                    ),
                ),
                (
                    "applies_to_services",
                    models.BooleanField(
                        default=False, verbose_name="Applies to Services"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "legal_reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Legal Reference"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "ordering": ["-effective_from", "tax_type"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "abbreviation",
                    models.CharField(max_length=10, verbose_name="Abbreviation"),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Symbol"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "uom_type",
                    models.CharField(
                        choices=[
                            ("LENGTH", "Length"),
                            ("WEIGHT", "Weight"),
                            ("VOLUME", "Volume"),
                            ("AREA", "Area"),
                            ("QUANTITY", "Quantity"),
                            ("TIME", "Time"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="UOM Type",
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        help_text="Multiply by this factor to convert to the base unit",
                        max_digits=16,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                        verbose_name="Conversion Factor",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["uom_type", "name"],
            },
        ),
    ]
