# Generated by Django 5.2 on 2025-12-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("core", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default bank account for bank payments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_bank_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_cash_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default cash account for cash payments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_cash_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_discount_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for fee discounts",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_discount_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for general expenses",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_payables_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for accounts payable",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_payables_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_receivables_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for student receivables",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_receivables_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for fee revenue",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_scholarship_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for scholarship expenses",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_scholarship_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_service_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for other service revenue",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_service_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_tax_payable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for tax payable",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_tax_payable_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="default_tax_receivable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for tax receivable",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_tax_receivable_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="accumulated_depreciation_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Contra-asset account for depreciation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accumulated_depreciation_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="default_cogs_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for cost of goods sold",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cogs_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="default_inventory_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default account for inventory asset",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="depreciation_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for depreciation charges",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="depreciation_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="fixed_assets_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset account for property, plant, equipment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fixed_assets_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="maintenance_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for maintenance",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="supplies_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for school supplies",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplies_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="utilities_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for utilities",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utilities_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="expenseaccountmappings",
            name="financial_settings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_account_mappings",
                to="core.financialsettings",
            ),
        ),
        migrations.AddField(
            model_name="coreaccountmappings",
            name="financial_settings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_account_mappings",
                to="core.financialsettings",
            ),
        ),
        migrations.AddField(
            model_name="fiscalperiod",
            name="related_academic_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated academic session (if applicable) - for reference/tracking only",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiscal_periods",
                to="academics.academicsession",
                verbose_name="Related Academic Session",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalyear",
            index=models.Index(
                fields=["start_date", "end_date"], name="core_fiscal_start_d_53aa6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalyear",
            index=models.Index(fields=["status"], name="core_fiscal_status_14550a_idx"),
        ),
        migrations.AddIndex(
            model_name="fiscalyear",
            index=models.Index(
                fields=["is_active"], name="core_fiscal_is_acti_2bfcbd_idx"
            ),
        ),
        migrations.AddField(
            model_name="fiscalperiod",
            name="fiscal_year",
            field=models.ForeignKey(
                help_text="Parent fiscal year for accounting hierarchy",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_periods",
                to="core.fiscalyear",
                verbose_name="Fiscal Year",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["method_type", "is_active"],
                name="core_paymen_method__95d3e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="core_paymen_is_acti_1617cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["code"], name="core_paymen_code_3029fb_idx"),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="bonus_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for bonuses",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bonus_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="commission_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for sales commissions",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="financial_settings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_account_mappings",
                to="core.financialsettings",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="general_allowance_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for other allowances",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="general_allowance_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="housing_allowance_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for housing allowances",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="housing_allowance_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="medical_allowance_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for medical allowances",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medical_allowance_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="overtime_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for overtime payments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overtime_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="payroll_tax_payable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for payroll taxes",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_tax_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="pension_payable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for pension contributions",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pension_payable_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="salaries_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for staff salaries",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="salaries_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="social_security_payable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for social security",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="social_security_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="staff_benefits_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for employee benefits",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_benefits_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="staff_insurance_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for staff insurance",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_insurance_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="staff_pension_contribution_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for pension contributions",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_pension_contribution_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="transport_allowance_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for transport allowances",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_allowance_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="payrollaccountmappings",
            name="wages_payable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for accrued salaries",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wages_payable_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="boarding_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for boarding fees",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boarding_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="donation_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for donations received",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donation_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="financial_settings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revenue_account_mappings",
                to="core.financialsettings",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="grant_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for grants received",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grant_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="late_fee_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for late payment fees",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="late_fee_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="meals_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for meal fees",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meals_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="penalty_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for penalties and fines",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="penalty_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="textbook_sales_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for textbook sales",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="textbook_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="transport_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for transportation fees",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="revenueaccountmappings",
            name="uniform_sales_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for uniform sales",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uniform_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="allowance_for_doubtful_accounts",
            field=models.ForeignKey(
                blank=True,
                help_text="Contra-asset account for doubtful accounts",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doubtful_accounts_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="bad_debt_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for bad debt write-offs",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bad_debt_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="bank_reconciliation_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Temporary account for bank reconciliation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_reconciliation_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="default_currency_gain_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account for foreign currency gains",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="currency_gain_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="default_currency_loss_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account for foreign currency losses",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="currency_loss_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="default_refund_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Contra-revenue account for refunds",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="default_rounding_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account for currency rounding differences",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rounding_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="default_student_deposit_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for student deposits",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_deposit_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="financial_settings",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="special_account_mappings",
                to="core.financialsettings",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="gratuity_payable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for gratuity accrued",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gratuity_payable_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="mobile_money_clearing_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Clearing account for mobile money",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mobile_money_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="payment_processing_fee_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for payment processing fees",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_processing_fee_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="petty_cash_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cash account for petty cash fund",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="petty_cash_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="recruitment_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for recruitment costs",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recruitment_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="severance_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for severance payments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="severance_expense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="staff_advance_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset account for salary advances",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_advance_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="staff_loan_receivable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset account for staff loans",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_loan_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="staff_training_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for staff training",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_training_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="student_credit_balance_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for student overpayments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_credit_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="suspense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Temporary holding account",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suspense_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="unearned_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for advance payments",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unearned_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddField(
            model_name="specialaccountmappings",
            name="withholding_tax_payable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Liability account for withholding tax",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withholding_tax_mappings",
                to="finance.account",
            ),
        ),
        migrations.AddIndex(
            model_name="taxrate",
            index=models.Index(
                fields=["tax_type", "effective_from"],
                name="core_taxrat_tax_typ_37cb92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taxrate",
            index=models.Index(
                fields=["is_active", "effective_from"],
                name="core_taxrat_is_acti_c1a802_idx",
            ),
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                help_text="The base unit this unit is derived from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_units",
                to="core.unitofmeasure",
                verbose_name="Base Unit",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["fiscal_year", "period_number"],
                name="core_fiscal_fiscal__5cc46d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="core_fiscal_start_d_9a8d82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["status", "is_active"], name="core_fiscal_status_93a2f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["period_type"], name="core_fiscal_period__051045_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["is_active", "is_closed"], name="core_fiscal_is_acti_32f917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["related_academic_session"],
                name="core_fiscal_related_a41ab7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="fiscal_period_start_before_end",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalperiod",
            unique_together={("fiscal_year", "period_number")},
        ),
        migrations.AddIndex(
            model_name="unitofmeasure",
            index=models.Index(
                fields=["uom_type", "is_active"], name="core_unitof_uom_typ_91fe63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitofmeasure",
            index=models.Index(
                fields=["base_unit", "uom_type"], name="core_unitof_base_un_c43c97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitofmeasure",
            index=models.Index(
                fields=["is_active", "uom_type"], name="core_unitof_is_acti_ee09d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unitofmeasure",
            index=models.Index(
                fields=["abbreviation"], name="core_unitof_abbrevi_dd090d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.CheckConstraint(
                condition=models.Q(("conversion_factor__gt", 0)),
                name="positive_conversion_factor",
            ),
        ),
    ]
