# Generated by Django 5.2 on 2026-04-01 09:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialsettings",
            name="allow_partial_payments",
            field=models.BooleanField(
                default=True, verbose_name="Allow Partial Payments"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="auto_apply_discounts",
            field=models.BooleanField(
                default=True, verbose_name="Auto Apply Discounts"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="auto_apply_scholarships",
            field=models.BooleanField(
                default=True, verbose_name="Auto Apply Scholarships"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="auto_generate_recurring_invoices",
            field=models.BooleanField(
                default=True, verbose_name="Auto-Generate Recurring Invoices"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="auto_update_exchange_rates",
            field=models.BooleanField(
                default=False,
                help_text="When disabled, cashiers enter rates manually.",
                verbose_name="Auto-Update Exchange Rates",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="auto_write_off_days",
            field=models.PositiveIntegerField(
                default=365,
                validators=[django.core.validators.MinValueValidator(90)],
                verbose_name="Auto Write-Off Days",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="bad_debt_write_off_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Bad Debt Write-Off Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="currency_position",
            field=models.CharField(
                choices=[
                    ("BEFORE", "Before amount  — UGX 100.00"),
                    ("AFTER", "After amount   — 100.00 UGX"),
                    ("BEFORE_NO_SPACE", "Before no space — UGX100.00"),
                    ("AFTER_NO_SPACE", "After no space  — 100.00UGX"),
                ],
                default="BEFORE",
                max_length=20,
                verbose_name="Currency Position",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="decimal_places",
            field=models.PositiveIntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
                verbose_name="Decimal Places",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="default_payment_terms_days",
            field=models.PositiveIntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="Default Payment Terms (Days)",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="default_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("18.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Default Tax Rate (%)",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="discount_approval_required",
            field=models.BooleanField(
                default=True, verbose_name="Discount Approval Required"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="discount_approval_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100000.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Discount Approval Threshold",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="early_payment_discount_days",
            field=models.PositiveIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Early Payment Discount Days",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="early_payment_discount_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Enable Early Payment Discount"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="early_payment_discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Early Payment Discount %",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="exchange_rate_update_frequency",
            field=models.PositiveIntegerField(
                default=6,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(168),
                ],
                verbose_name="Exchange Rate Update Frequency (Hours)",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="expense_approval_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100000.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Expense Approval Limit",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="expense_approval_required",
            field=models.BooleanField(
                default=True, verbose_name="Expense Approval Required"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="expense_prefix",
            field=models.CharField(
                blank=True, default="EXP", max_length=10, verbose_name="Expense Prefix"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="grace_period_days",
            field=models.PositiveIntegerField(
                default=7,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Grace Period (Days)",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="include_tax_in_prices",
            field=models.BooleanField(
                default=False, verbose_name="Include Tax in Prices"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="include_year_in_expense_number",
            field=models.BooleanField(
                default=True, verbose_name="Year in Expense Number"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="include_year_in_invoice_number",
            field=models.BooleanField(
                default=True, verbose_name="Year in Invoice Number"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="include_year_in_payment_number",
            field=models.BooleanField(
                default=True, verbose_name="Year in Payment Number"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="invoice_aging_periods",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Invoice Aging Periods (days)"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="invoice_prefix",
            field=models.CharField(
                blank=True, default="INV", max_length=10, verbose_name="Invoice Prefix"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="late_fee_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable Late Fees"),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="late_fee_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Late Fee Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="minimum_payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1000.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Minimum Payment Amount",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="multi_currency_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Enable Multi-Currency"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="overdue_reminder_days",
            field=models.PositiveIntegerField(
                default=7,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Overdue Reminder Frequency (Days)",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="payment_prefix",
            field=models.CharField(
                blank=True, default="PMT", max_length=10, verbose_name="Payment Prefix"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="receipt_prefix",
            field=models.CharField(
                blank=True, default="RCPT", max_length=10, verbose_name="Receipt Prefix"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="require_expense_receipts",
            field=models.BooleanField(
                default=True, verbose_name="Require Expense Receipts"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="require_payment_confirmation",
            field=models.BooleanField(
                default=False, verbose_name="Require Payment Confirmation"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="require_purchase_orders",
            field=models.BooleanField(
                default=False, verbose_name="Require Purchase Orders"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="scholarship_approval_required",
            field=models.BooleanField(
                default=False, verbose_name="Scholarship Approval Required"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="school_currency",
            field=models.CharField(
                default="UGX",
                help_text="ISO 4217 currency code",
                max_length=3,
                verbose_name="School Currency",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="send_invoice_emails",
            field=models.BooleanField(default=True, verbose_name="Send Invoice Emails"),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="send_overdue_reminders",
            field=models.BooleanField(
                default=True, verbose_name="Send Overdue Reminders"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="send_payment_confirmations",
            field=models.BooleanField(
                default=True, verbose_name="Send Payment Confirmations"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="send_sms_notifications",
            field=models.BooleanField(
                default=False, verbose_name="Send SMS Notifications"
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="tracked_currencies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='ISO 4217 codes. E.g. ["USD", "EUR"]. School currency auto-excluded.',
                verbose_name="Tracked Currencies",
            ),
        ),
        migrations.AlterField(
            model_name="financialsettings",
            name="use_thousand_separator",
            field=models.BooleanField(
                default=True, verbose_name="Use Thousand Separator"
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="academic_year_start_day",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Academic Year Start Day",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="academic_year_start_month",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Academic Year Start Month",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="academic_year_type",
            field=models.CharField(
                choices=[
                    ("calendar", "Calendar Year (Jan–Dec)"),
                    ("northern", "Northern Hemisphere (Sep–Jun)"),
                    ("southern", "Southern Hemisphere (Feb–Nov)"),
                    ("east_africa", "East African Calendar (Jan–Nov)"),
                    ("west_africa", "West African Calendar (Sep–Jul)"),
                    ("sahel", "Sahel Region (Oct–Jun)"),
                    ("financial", "Financial Year (Apr–Mar)"),
                    ("custom", "Custom Year Dates"),
                ],
                default="east_africa",
                max_length=15,
                verbose_name="Academic Year Type",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="custom_period_names",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='E.g. {"1": "Fall Semester", "2": "Spring Semester"}',
                verbose_name="Custom Period Names",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="custom_season_names",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='E.g. {"1": "Harmattan", "2": "Rainy Season"}',
                verbose_name="Custom Season Names",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="default_period_duration_weeks",
            field=models.PositiveIntegerField(
                default=13,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(52),
                ],
                verbose_name="Default Period Duration (weeks)",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="enable_automatic_reminders",
            field=models.BooleanField(
                default=True, verbose_name="Enable Automatic Reminders"
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="enable_email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Enable Email Notifications"
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="enable_sms",
            field=models.BooleanField(
                default=False, verbose_name="Enable SMS Notifications"
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="operational_timezone",
            field=models.CharField(
                default="Africa/Kampala",
                help_text="School timezone for fee due dates, attendance, exam schedules, report generation, and all date-based business logic.",
                max_length=63,
                verbose_name="Operational Timezone",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="period_naming_convention",
            field=models.CharField(
                choices=[
                    ("numeric", "Numeric (Term 1, Term 2…)"),
                    ("ordinal", "Ordinal (First Term, Second Term…)"),
                    ("seasonal", "Seasonal (Fall, Spring, Summer)"),
                    ("monthly", "Monthly (January, February…)"),
                    ("alpha", "Alphabetical (Term A, Term B…)"),
                    ("roman", "Roman Numerals (Term I, Term II…)"),
                    ("custom", "Custom Names"),
                ],
                default="numeric",
                max_length=20,
                verbose_name="Period Naming Convention",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="periods_per_year",
            field=models.PositiveIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name="Periods Per Year",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="regional_season_type",
            field=models.CharField(
                choices=[
                    ("temperate", "Temperate (Spring/Summer/Fall/Winter)"),
                    ("tropical_wet_dry", "Tropical (Wet/Dry Seasons)"),
                    ("desert", "Desert (Hot/Cool Seasons)"),
                    ("equatorial", "Equatorial (Year-round)"),
                    ("monsoon", "Monsoon (Pre/Monsoon/Post)"),
                    ("custom_regional", "Custom Regional Seasons"),
                ],
                default="equatorial",
                max_length=20,
                verbose_name="Regional Season Type",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="term_system",
            field=models.CharField(
                choices=[
                    ("term", "Terms (3 per year) — British/Commonwealth"),
                    ("semester", "Semesters (2 per year) — North American"),
                    ("quarter", "Quarters (4 per year)"),
                    ("trimester", "Trimesters (3 per year) — same as Terms"),
                    ("module", "Modules (6-8 per year)"),
                    ("block", "Block Schedule (4-6 per year)"),
                    ("yearlong", "Year-long Program (1 per year)"),
                    ("intensive", "Intensive Programs (8-12 per year)"),
                    ("custom", "Custom System"),
                ],
                default="term",
                max_length=15,
                verbose_name="Academic Period System",
            ),
        ),
    ]
