# Generated by Django 5.2 on 2026-04-01 11:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_initial"),
        ("core", "0003_alter_financialsettings_allow_partial_payments_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialaccountmappings",
            name="petty_cash_account",
        ),
        migrations.AlterField(
            model_name="coreaccountmappings",
            name="boarding_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Boarding revenue for category-level routing (FeesCategory types BOARDING and MEALS). Distinct from RevenueAccountMappings.boarding_revenue_account which handles invoice-type-level routing. Both can be configured independently. Falls back to default_revenue_account if not set.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_boarding_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="coreaccountmappings",
            name="uniform_and_book_sales_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Uniform and book sales revenue (REVENUE - optional). Used as fallback by FinancialSettings.get_uniform_revenue_account() when RevenueAccountMappings.uniform_sales_revenue_account is not set. Falls back to default_revenue_account if not set.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uniform_book_sales_mappings",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="fiscalperiod",
            name="period_number",
            field=models.DecimalField(
                db_index=True,
                decimal_places=1,
                help_text="Sequential number within fiscal year (1, 2, 3… or 1.5 for break periods)",
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                verbose_name="Period Number",
            ),
        ),
        migrations.AlterField(
            model_name="fiscalperiod",
            name="related_academic_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated academic session (optional). For ACADEMIC_ALIGNED periods, the fiscal period start date should be at or before the session start date (invoices go out before term begins) and end date at or after session end date (collections continue after term ends). Not required for BREAK_PERIOD, MONTHLY, QUARTERLY, or other non-academic period types.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiscal_periods",
                to="academics.academicsession",
                verbose_name="Related Academic Session",
            ),
        ),
        migrations.AlterField(
            model_name="revenueaccountmappings",
            name="boarding_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Revenue account for boarding fees (invoice-type-level routing). Distinct from CoreAccountMappings.boarding_revenue_account which handles category-level routing.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boarding_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="schoolconfiguration",
            name="operational_timezone",
            field=models.CharField(
                default="Africa/Kampala",
                help_text="School timezone for fee due dates, fiscal periods, report generation, journal entry timestamps, and all date-based business logic in the finance layer. NOTE: AcademicSession date checks currently use server time — update academics/models.py to use get_school_today() from core.utils to extend timezone awareness to the academic layer.",
                max_length=63,
                verbose_name="Operational Timezone",
            ),
        ),
        migrations.AlterField(
            model_name="specialaccountmappings",
            name="mobile_money_clearing_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Clearing/suspense account for mobile money reconciliation. NOT used for payment routing — use CoreAccountMappings.mobile_money_account instead.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mobile_money_mappings",
                to="finance.account",
            ),
        ),
    ]
