# Generated by Django 5.2 on 2026-04-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_specialaccountmappings_petty_cash_account_and_more"),
        ("finance", "0003_remove_expenseline_expense_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coreaccountmappings",
            name="boarding_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Boarding revenue for BOARDING, MEALS, and LAUNDRY category types. Distinct from RevenueAccountMappings.boarding_revenue_account which handles invoice-type-level routing. Falls back to default_revenue_account.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="core_boarding_revenue_mappings",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="coreaccountmappings",
            name="uniform_and_book_sales_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Uniform and book sales revenue (REVENUE - optional). Used as fallback by FinancialSettings.get_uniform_revenue_account(). Falls back to default_revenue_account if not set.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uniform_book_sales_mappings",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="processing_time",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Instant', '1–3 business days'. Displayed to cashiers at payment entry.",
                max_length=100,
                verbose_name="Processing Time",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="requires_reference",
            field=models.BooleanField(
                default=False,
                help_text="Auto-set to True on first save for BANK_TRANSFER, CHEQUE, DIRECT_DEBIT, and STANDING_ORDER. Can be overridden after creation.",
                verbose_name="Requires Reference Number",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["is_default"], name="core_paymen_is_defa_e8df07_idx"
            ),
        ),
    ]
