# Generated by Django 5.2 on 2025-12-30 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("birth_certificate", "Birth Certificate"),
                            ("passport", "Passport"),
                            ("national_id", "National ID"),
                            ("immunization_record", "Immunization Record"),
                            ("medical_report", "Medical Report"),
                            ("previous_school_report", "Previous School Report"),
                            ("transfer_certificate", "Transfer Certificate"),
                            ("admission_letter", "Admission Letter"),
                            ("parent_letter", "Parent/Guardian Letter"),
                            ("photo", "Photograph"),
                            ("scholarship_document", "Scholarship Document"),
                            ("disciplinary_record", "Disciplinary Record"),
                            ("achievement_certificate", "Achievement Certificate"),
                            ("sports_certificate", "Sports Certificate"),
                            ("other", "Other Document"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Descriptive name for the document",
                        max_length=100,
                        verbose_name="Document Name",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        help_text="Upload document file (PDF, DOC, DOCX, JPG, PNG)",
                        upload_to="student_documents/%Y/%m/",
                        verbose_name="Document File",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Official document number (if applicable)",
                        max_length=50,
                        verbose_name="Document Number",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when document was issued",
                        null=True,
                        verbose_name="Issue Date",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date when document expires",
                        null=True,
                        verbose_name="Expiry Date",
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        blank=True,
                        help_text="Organization that issued the document",
                        max_length=100,
                        verbose_name="Issuing Authority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("requires_update", "Requires Update"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether document has been verified by staff",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "verified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who verified this document",
                        max_length=50,
                        null=True,
                        verbose_name="Verified By ID",
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from document verification process",
                        verbose_name="Verification Notes",
                    ),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        db_index=True,
                        default="internal",
                        max_length=15,
                        verbose_name="Confidentiality Level",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this document is required for enrollment",
                        verbose_name="Is Required",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether document is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description or notes about the document",
                        verbose_name="Description",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for easy searching",
                        max_length=200,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="File size in bytes",
                        null=True,
                        verbose_name="File Size",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="File extension",
                        max_length=10,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Upload Date"
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Accessed"
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times document has been accessed",
                        verbose_name="Access Count",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Document",
                "verbose_name_plural": "Student Documents",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "access_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Access Date/Time",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("upload", "Upload"),
                            ("print", "Print"),
                            ("share", "Share"),
                            ("verify", "Verify"),
                            ("reject", "Reject"),
                        ],
                        db_index=True,
                        default="view",
                        max_length=20,
                        verbose_name="Access Type",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser user agent string",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="User session identifier",
                        max_length=40,
                        verbose_name="Session ID",
                    ),
                ),
                (
                    "referrer_url",
                    models.URLField(
                        blank=True,
                        help_text="URL that referred to this access",
                        max_length=500,
                        verbose_name="Referrer URL",
                    ),
                ),
                (
                    "access_duration",
                    models.DurationField(
                        blank=True,
                        help_text="How long the document was accessed (for view operations)",
                        null=True,
                        verbose_name="Access Duration",
                    ),
                ),
                (
                    "file_size_at_access",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Size of file when accessed (in bytes)",
                        null=True,
                        verbose_name="File Size at Access",
                    ),
                ),
                (
                    "was_successful",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the access operation was successful",
                        verbose_name="Was Successful",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if access failed",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this access",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO country code from IP geolocation",
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City from IP geolocation",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="documents.studentdocument",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Access Log",
                "verbose_name_plural": "Document Access Logs",
                "ordering": ["-access_datetime"],
            },
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["student", "document_type"],
                name="documents_s_student_db545f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(fields=["status"], name="documents_s_status_3bee8b_idx"),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["is_verified"], name="documents_s_is_veri_5a1490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["expiry_date"], name="documents_s_expiry__f8fa3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["student", "is_active"], name="documents_s_student_f7f425_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocument",
            index=models.Index(
                fields=["confidentiality_level"], name="documents_s_confide_49e3a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("document_number__isnull", False),
                    models.Q(("document_number", ""), _negated=True),
                ),
                fields=("student", "document_type", "document_number"),
                name="unique_student_document_number",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["document", "access_datetime"],
                name="documents_d_documen_65043d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["access_type"], name="documents_d_access__fa4303_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["ip_address"], name="documents_d_ip_addr_4ecddf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["was_successful"], name="documents_d_was_suc_8db48b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["access_datetime"], name="documents_d_access__96e691_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["document", "access_type"],
                name="documents_d_documen_d70af1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccesslog",
            index=models.Index(
                fields=["created_by_id", "access_datetime"],
                name="documents_d_created_3e8ba4_idx",
            ),
        ),
    ]
