# Generated by Django 5.2 on 2026-04-05 17:45

import datetime
import django.db.models.deletion
import hr.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_coreaccountmappings_boarding_revenue_account_and_more"),
        ("finance", "0003_remove_expenseline_expense_account_and_more"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="approved_by_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Approved By ID"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="auto_renew",
            field=models.BooleanField(default=False, verbose_name="Auto Renew"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="basic_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Basic salary amount — interpreted based on salary_frequency",
                max_digits=10,
                verbose_name="Basic Salary",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="benefits_package",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Benefits Package"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="probation_period_months",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 if no probation",
                verbose_name="Probation Period (Months)",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="renewal_period_months",
            field=models.PositiveIntegerField(
                default=12, verbose_name="Renewal Period (Months)"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="requires_renewal_approval",
            field=models.BooleanField(
                default=True, verbose_name="Requires Renewal Approval"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="signed_by_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Signed By ID"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="special_terms",
            field=models.TextField(
                blank=True, verbose_name="Special Terms & Conditions"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="terminated_by_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Terminated By ID"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="head_id",
            field=models.CharField(
                blank=True,
                help_text="Staff ID (Staff.staff_id) who heads this department",
                max_length=50,
                null=True,
                verbose_name="Department Head ID",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="required_qualifications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of qualification strings for this designation. If left empty, get_qualifications() returns sensible defaults based on is_teaching and department type.",
                verbose_name="Required Qualifications",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="approved_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Approved By ID"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="auto_create_journal_entry",
            field=models.BooleanField(
                default=True, verbose_name="Auto-Create Journal Entry"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Bank Account"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="basic_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Basic Salary",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="currency",
            field=models.CharField(
                default=hr.models._payroll_default_currency,
                help_text="ISO 4217 currency code this payroll is denominated in. Defaults to the school's primary currency from FinancialSettings — non-UGX schools no longer need to manually correct this field.",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="days_worked",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Days Worked"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employer_cost_in_school_currency",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="employer_total_cost × exchange_rate",
                max_digits=15,
                verbose_name="Employer Cost in School Currency",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employer_total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Total Employer Cost",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                help_text="Rate between payroll currency and school currency at time of payment. Stored permanently.",
                max_digits=12,
                verbose_name="Exchange Rate",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="is_prorated",
            field=models.BooleanField(default=False, verbose_name="Is Prorated"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payrolls",
                to="finance.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="local_service_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Local Service Tax",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="net_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Net Pay",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="net_pay_in_school_currency",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="net_pay × exchange_rate",
                max_digits=15,
                verbose_name="Net Pay in School Currency",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="nssf_employee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="NSSF Employee Contribution",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="nssf_employer",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="NSSF Employer Contribution",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="paid_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Paid By ID"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="pay_frequency",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("WEEKLY", "Weekly"),
                    ("BIWEEKLY", "Bi-Weekly"),
                    ("SEMI_MONTHLY", "Semi-Monthly"),
                    ("QUARTERLY", "Quarterly"),
                ],
                db_index=True,
                default="MONTHLY",
                max_length=12,
                verbose_name="Pay Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="pay_period_end",
            field=models.DateField(db_index=True, verbose_name="Pay Period End"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="pay_period_start",
            field=models.DateField(db_index=True, verbose_name="Pay Period Start"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="paye_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="PAYE Amount",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="payment_date",
            field=models.DateField(db_index=True, verbose_name="Payment Date"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="payment_journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_payments",
                to="finance.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_payrolls",
                to="core.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Payment Reference"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="payroll_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated reference (e.g. PAY/2025/12/0001)",
                max_length=30,
                unique=True,
                verbose_name="Payroll Number",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="reversal_approved_by_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Reversal Approved By ID",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="reversal_journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_payrolls",
                to="finance.journalentry",
                verbose_name="Reversal Journal Entry",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="reversal_reason",
            field=models.TextField(blank=True, verbose_name="Reversal Reason"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="reversed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Reversed"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="reversed_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Reversed By ID"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="statutory_adjustments_notes",
            field=models.TextField(
                blank=True, verbose_name="Statutory Adjustments Notes"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="statutory_reversals_required",
            field=models.BooleanField(
                default=False, verbose_name="Statutory Reversals Required"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="taxable_income",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Gross pay minus pre-tax deductions and non-taxable allowances",
                max_digits=15,
                verbose_name="Taxable Income",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_allowances",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Total Allowances",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_bonuses",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Total Bonuses",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Total Deductions",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_statutory_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Total Statutory Deductions",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_voluntary_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                verbose_name="Total Voluntary Deductions",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_working_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Total Working Days"
            ),
        ),
        migrations.AlterField(
            model_name="staffdesignation",
            name="start_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Start Date"
            ),
        ),
    ]
