# Generated by Django 5.2 on 2026-02-13 08:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("finance", "0001_initial"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="currency",
            field=models.CharField(
                default="UGX",
                help_text="ISO 4217 currency code (e.g., UGX, USD, KES)",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="employer_total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="True cost of this employee to the school for this period: gross_pay + nssf_employer + any other employer contributions. Use this for budget and cost-of-employment reporting.",
                max_digits=15,
                verbose_name="Total Employer Cost",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                help_text="Exchange rate to base currency (UGX) at time of payment. Use 1.000000 for UGX payrolls.",
                max_digits=10,
                verbose_name="Exchange Rate",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="local_service_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Local Service Tax (LST) deducted this period",
                max_digits=15,
                verbose_name="Local Service Tax",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="nssf_employee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Employee portion of NSSF contribution (deducted from gross pay)",
                max_digits=15,
                verbose_name="NSSF Employee Contribution",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="nssf_employer",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Employer's NSSF contribution. This is a cost to the school and does NOT appear in the employee's net pay calculation.",
                max_digits=15,
                verbose_name="NSSF Employer Contribution",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="paye_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Income tax (Pay As You Earn) withheld this period. Stored here for quick access on payslips and P9/P10 reports.",
                max_digits=15,
                verbose_name="PAYE Amount",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="taxable_income",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Gross pay minus pre-tax deductions and non-taxable allowances. This is the base used to calculate PAYE.",
                max_digits=15,
                verbose_name="Taxable Income",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_allowances",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of all PayrollAllowance entries for this pay period",
                max_digits=15,
                verbose_name="Total Allowances",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_bonuses",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of all PayrollBonus entries for this pay period",
                max_digits=15,
                verbose_name="Total Bonuses",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_statutory_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="PAYE + NSSF Employee + Local Service Tax (for compliance reporting)",
                max_digits=15,
                verbose_name="Total Statutory Deductions",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="total_voluntary_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="All non-statutory deductions: loans, SACCO, insurance, pension contributions, union dues, etc.",
                max_digits=15,
                verbose_name="Total Voluntary Deductions",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="gross_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="basic_salary + total_allowances + total_bonuses",
                max_digits=15,
                verbose_name="Gross Pay",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="net_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount actually paid to employee (gross_pay - total_deductions)",
                max_digits=15,
                verbose_name="Net Pay",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="total_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="total_statutory_deductions + total_voluntary_deductions",
                max_digits=15,
                verbose_name="Total Deductions",
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["currency"], name="hr_payroll_currenc_c20ff8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_allowances__gte", 0)),
                name="payroll_total_allowances_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_bonuses__gte", 0)),
                name="payroll_total_bonuses_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_deductions__gte", 0)),
                name="payroll_total_deductions_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_statutory_deductions__gte", 0)),
                name="payroll_statutory_deductions_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_voluntary_deductions__gte", 0)),
                name="payroll_voluntary_deductions_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("nssf_employer__gte", 0)),
                name="payroll_nssf_employer_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("employer_total_cost__gte", 0)),
                name="payroll_employer_total_cost_non_negative",
            ),
        ),
    ]
