# Generated by Django 5.2 on 2026-02-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_payroll_currency_payroll_employer_total_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="payroll_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-generated payroll reference number (e.g. PAY/2025/12/0001)",
                max_length=30,
                unique=True,
                verbose_name="Payroll Number",
            ),
        ),
    ]
