# Generated by Django 5.2 on 2026-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_initial"),
        ("fees", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentscholarshipapplication",
            name="reviewed_by",
        ),
        migrations.AddField(
            model_name="studentscholarshipapplication",
            name="reviewed_by_id",
            field=models.CharField(
                blank=True,
                help_text="User ID who reviewed this application",
                max_length=50,
                null=True,
                verbose_name="Reviewed By ID",
            ),
        ),
        migrations.AddIndex(
            model_name="studentscholarshipapplication",
            index=models.Index(
                fields=["reviewed_by_id"], name="fees_studen_reviewe_654ec1_idx"
            ),
        ),
    ]
