# Generated by Django 5.2 on 2026-02-03 06:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_initial"),
        ("fees", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarshipprogram",
            name="allows_category_customization",
            field=models.BooleanField(
                default=True,
                help_text="If True, scholarship officers can customize category discounts when awarding scholarships. If False, default_category_discounts template is enforced for all students.",
                verbose_name="Allow Category Customization Per Student",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipprogram",
            name="category_discount_description",
            field=models.TextField(
                blank=True,
                help_text="Human-readable explanation of how category discounts work for this program. Example: 'This scholarship covers 100% of tuition fees but does not cover boarding or meal costs.'",
                verbose_name="Category Discount Explanation",
            ),
        ),
        migrations.AddField(
            model_name="scholarshipprogram",
            name="default_category_discounts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Default discount rules per fee category (used when discount_type = CATEGORY_SPECIFIC).\n        When awarding scholarships, these defaults are pre-filled but can be customized per student.\n        \n        Structure:\n        {\n            "TUITION": {\n                "type": "percentage" | "fixed_amount" | "full_waiver" | "none",\n                "value": 100.00,\n                "description": "Optional explanation"\n            },\n            "BOARDING": {\n                "type": "none",\n                "value": 0.00,\n                "description": "Not covered by this scholarship"\n            },\n            "MEALS": {\n                "type": "percentage",\n                "value": 50.00\n            }\n        }\n        \n        Common Templates:\n        \n        1. FULL TUITION ONLY:\n        {\n            "TUITION": {"type": "full_waiver", "value": 100.00},\n            "BOARDING": {"type": "none", "value": 0.00},\n            "MEALS": {"type": "none", "value": 0.00},\n            "TRANSPORT": {"type": "none", "value": 0.00}\n        }\n        \n        2. 50% EVERYTHING:\n        {\n            "TUITION": {"type": "percentage", "value": 50.00},\n            "BOARDING": {"type": "percentage", "value": 50.00},\n            "MEALS": {"type": "percentage", "value": 50.00}\n        }\n        \n        3. TUITION + PARTIAL BOARDING:\n        {\n            "TUITION": {"type": "full_waiver", "value": 100.00},\n            "BOARDING": {"type": "percentage", "value": 50.00},\n            "MEALS": {"type": "percentage", "value": 50.00}\n        }\n        \n        4. FIXED AMOUNTS:\n        {\n            "TUITION": {"type": "fixed_amount", "value": 500000.00},\n            "EXAM": {"type": "fixed_amount", "value": 50000.00},\n            "BOARDING": {"type": "none", "value": 0.00}\n        }\n        \n        Notes:\n        - Only used when discount_type = \'CATEGORY_SPECIFIC\'\n        - Category codes must match FeesCategory.category_type or FeesCategory.code\n        - If a category is not listed, no discount is applied by default\n        - Scholarship officers can customize these when awarding scholarships\n        ',
                verbose_name="Default Category Discount Template",
            ),
        ),
        migrations.AddField(
            model_name="studentscholarship",
            name="category_discount_notes",
            field=models.TextField(
                blank=True,
                help_text="Administrative notes explaining why specific category discounts were configured",
                verbose_name="Category Discount Notes",
            ),
        ),
        migrations.AddField(
            model_name="studentscholarship",
            name="category_discounts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        JSON mapping fee category codes to discount configurations.\n        \n        Structure:\n        {\n            "TUITION": {\n                "type": "percentage" | "fixed_amount" | "full_waiver" | "none",\n                "value": 100.00,\n                "notes": "Optional notes"\n            },\n            "BOARDING": {\n                "type": "none",\n                "value": 0.00\n            },\n            "MEALS": {\n                "type": "percentage",\n                "value": 50.00\n            }\n        }\n        \n        Discount Types:\n        - "percentage": value is percentage (0-100)\n        - "fixed_amount": value is specific amount per invoice\n        - "full_waiver": 100% discount (value ignored)\n        - "none": no discount for this category\n        \n        Examples:\n        \n        1. Full tuition waiver, no boarding discount:\n        {\n            "TUITION": {"type": "full_waiver", "value": 100.00},\n            "BOARDING": {"type": "none", "value": 0.00}\n        }\n        \n        2. 50% discount on everything:\n        {\n            "TUITION": {"type": "percentage", "value": 50.00},\n            "BOARDING": {"type": "percentage", "value": 50.00},\n            "MEALS": {"type": "percentage", "value": 50.00}\n        }\n        \n        3. Fixed amount tuition, percentage boarding:\n        {\n            "TUITION": {"type": "fixed_amount", "value": 500000.00},\n            "BOARDING": {"type": "percentage", "value": 25.00}\n        }\n        \n        4. Complex scenario:\n        {\n            "TUITION": {"type": "full_waiver", "value": 100.00},\n            "EXAM": {"type": "percentage", "value": 75.00},\n            "BOARDING": {"type": "none", "value": 0.00},\n            "MEALS": {"type": "fixed_amount", "value": 50000.00},\n            "TRANSPORT": {"type": "percentage", "value": 50.00}\n        }\n        \n        Notes:\n        - If a category is not listed, it defaults to program\'s global discount\n        - Category codes match FeesCategory.category_type or FeesCategory.code\n        - For budget-based scholarships, total spending across all categories\n          is tracked against amount_awarded\n        ',
                verbose_name="Category-Specific Discount Rules",
            ),
        ),
        migrations.AddField(
            model_name="studentscholarship",
            name="use_category_specific_discounts",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Enable granular control per fee category. If True, uses category_discounts field. If False, uses program's global discount for all categories.",
                verbose_name="Use Category-Specific Discounts",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="applicable_fee_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Legacy field: Leave empty to apply to all fee categories. For CATEGORY_SPECIFIC mode, use default_category_discounts instead.",
                to="fees.feescategory",
                verbose_name="Applicable Fee Categories (Legacy Filter)",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="application_end_date",
            field=models.DateField(
                blank=True,
                help_text="Deadline for scholarship applications",
                null=True,
                verbose_name="Application End Date",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="application_start_date",
            field=models.DateField(
                blank=True,
                help_text="When students can start applying",
                null=True,
                verbose_name="Application Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="award_announcement_date",
            field=models.DateField(
                blank=True,
                help_text="When scholarship awards will be announced",
                null=True,
                verbose_name="Award Announcement Date",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="current_budget_used",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount awarded to date (tracked automatically)",
                max_digits=15,
                verbose_name="Current Budget Used",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="current_recipient_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of students currently receiving this scholarship",
                verbose_name="Current Recipients",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For PERCENTAGE discount type: applies to all categories",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Global Discount Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("PERCENTAGE", "Percentage Discount (Global)"),
                    ("FIXED_AMOUNT", "Fixed Amount Discount (Global)"),
                    ("FULL_WAIVER", "Full Fee Waiver (Global)"),
                    ("CATEGORY_SPECIFIC", "Category-Specific Discounts"),
                ],
                help_text="PERCENTAGE/FIXED_AMOUNT/FULL_WAIVER: Same discount for all categories. CATEGORY_SPECIFIC: Define different discounts per category.",
                max_length=20,
                verbose_name="Discount Type",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="external_funding_source",
            field=models.CharField(
                blank=True,
                help_text="Source of external funding (e.g., foundation, corporation)",
                max_length=200,
                verbose_name="External Funding Source",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="fixed_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="For FIXED_AMOUNT discount type: applies to all categories",
                max_digits=12,
                null=True,
                verbose_name="Global Fixed Discount Amount",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="is_accepting_applications",
            field=models.BooleanField(
                default=True,
                help_text="Whether this program is currently accepting applications",
                verbose_name="Accepting Applications",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Only active programs can award scholarships",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="maximum_award_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overall cap on total discount per student (across all categories)",
                max_digits=12,
                null=True,
                verbose_name="Maximum Award Amount Per Student",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="maximum_recipients",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of students who can receive this scholarship",
                null=True,
                verbose_name="Maximum Number of Recipients",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="minimum_attendance_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Student must maintain this attendance to qualify/renew",
                max_digits=5,
                null=True,
                verbose_name="Minimum Attendance Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="minimum_gpa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Student must maintain this GPA to qualify/renew",
                max_digits=4,
                null=True,
                verbose_name="Minimum GPA Requirement",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="renewal_policy",
            field=models.CharField(
                choices=[
                    ("AUTOMATIC", "Automatic Renewal"),
                    ("PERFORMANCE_BASED", "Performance-Based Review"),
                    ("ANNUAL_APPLICATION", "Annual Re-application Required"),
                    ("ONE_TIME_ONLY", "One-Time Award"),
                ],
                default="ANNUAL_APPLICATION",
                help_text="How scholarships are renewed for subsequent years/terms",
                max_length=20,
                verbose_name="Renewal Policy",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="sponsor_contact",
            field=models.TextField(
                blank=True,
                help_text="Contact details for sponsor/donor",
                verbose_name="Sponsor Contact Information",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="sponsor_name",
            field=models.CharField(
                blank=True,
                help_text="Name of sponsor/donor (for SPONSORED programs)",
                max_length=200,
                verbose_name="Sponsor Name",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipprogram",
            name="valid_sessions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sessions in which this program is available (leave empty for all sessions)",
                to="academics.academicsession",
                verbose_name="Valid Academic Sessions",
            ),
        ),
        migrations.AddIndex(
            model_name="scholarshipprogram",
            index=models.Index(
                fields=["program_type"], name="fees_schola_program_17fe04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scholarshipprogram",
            index=models.Index(
                fields=["discount_type"], name="fees_schola_discoun_9e4511_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentscholarship",
            index=models.Index(
                fields=["use_category_specific_discounts"],
                name="fees_studen_use_cat_cb8400_idx",
            ),
        ),
    ]
