# Generated by Django 5.2 on 2026-03-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeinvoice",
            name="fee_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="fees.feesstructure",
            ),
        ),
    ]
