# Generated by Django 5.2 on 2026-04-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_remove_studentscholarshipapplication_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountpolicy",
            name="max_discount_per_student",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Max discount per student",
            ),
        ),
        migrations.AlterField(
            model_name="discountpolicy",
            name="total_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Total budget",
            ),
        ),
    ]
