# Generated by Django 5.2 on 2026-04-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0003_alter_discountpolicy_max_discount_per_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feescategory",
            name="applicability",
            field=models.CharField(
                choices=[
                    ("ALL", "All Students"),
                    ("DAY_SCHOLARS", "Day Scholars Only"),
                    ("BOARDERS", "Boarders Only"),
                    ("WEEKLY_BOARDERS", "Weekly Boarders Only"),
                    ("FULL_BOARDERS", "Full Boarders Only"),
                    ("FLEXI_BOARDERS", "Flexible Boarders Only"),
                    ("NEW_STUDENTS", "New Students Only"),
                    ("CONTINUING_STUDENTS", "Continuing Students Only"),
                    ("SCHOLARSHIP_STUDENTS", "Scholarship Students"),
                    ("TRANSPORT_USERS", "Transport Users Only"),
                    ("SCIENCE_STUDENTS", "Science Stream Students"),
                    ("ICT_STUDENTS", "ICT / Computer Students"),
                    ("PARTICIPANTS", "Activity Participants Only"),
                    ("DEFAULTERS", "Students with Outstanding Balances"),
                    ("OPTIONAL", "Optional / Elective"),
                ],
                default="ALL",
                max_length=25,
                verbose_name="Applicable To",
            ),
        ),
        migrations.AlterField(
            model_name="feescategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("TUITION", "Tuition Fee"),
                    ("EXAM", "Examination Fee"),
                    ("LABORATORY", "Laboratory Fee"),
                    ("LIBRARY", "Library Fee"),
                    ("BOOKS", "Books & Materials"),
                    ("TECHNOLOGY", "Technology Fee"),
                    ("BOARDING", "Boarding Fee"),
                    ("MEALS", "Meals Fee"),
                    ("LAUNDRY", "Laundry Fee"),
                    ("TRANSPORT", "Transport Fee"),
                    ("MEDICAL", "Medical Fee"),
                    ("INSURANCE", "Insurance Fee"),
                    ("SPORT", "Sports Fee"),
                    ("CLUB", "Club / Activity Fee"),
                    ("FIELD_TRIP", "Field Trip"),
                    ("UNIFORM", "Uniform Fee"),
                    ("REGISTRATION", "Registration Fee"),
                    ("ADMISSION", "Admission Fee"),
                    ("DEVELOPMENT", "Development Levy"),
                    ("GRADUATION", "Graduation Fee"),
                    ("PTA", "PTA Levy"),
                    ("DEPOSIT", "Refundable Deposit"),
                    ("LATE_PAYMENT", "Late Payment Fee"),
                    ("PENALTY", "Penalty / Fine"),
                    ("PHOTO", "Photography Fee"),
                    ("PUBLICATION", "Publication Fee"),
                    ("MISCELLANEOUS", "Miscellaneous"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=20,
                verbose_name="Category Type",
            ),
        ),
        migrations.AlterField(
            model_name="feescategory",
            name="display_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Display groups are seeded before fee categories during school initialization. The init config passes group names as strings — the init command must resolve these to DisplayGroup instances before saving.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fees.displaygroup",
                verbose_name="Display Group",
            ),
        ),
        migrations.AlterField(
            model_name="feescategory",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("TERMLY", "Per Term"),
                    ("YEARLY", "Yearly"),
                    ("MONTHLY", "Monthly"),
                    ("WEEKLY", "Weekly"),
                    ("DAILY", "Daily"),
                    ("ONE_TIME", "One Time"),
                    ("PER_INCIDENT", "Per Incident"),
                ],
                default="TERMLY",
                max_length=20,
                verbose_name="Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="feescategory",
            name="is_recurring",
            field=models.BooleanField(
                default=True,
                help_text="True for periodic fees (TERMLY, MONTHLY, YEARLY). Automatically set to False for ONE_TIME and PER_INCIDENT frequencies — do not set manually.",
                verbose_name="Recurring",
            ),
        ),
        migrations.AddIndex(
            model_name="feescategory",
            index=models.Index(
                fields=["frequency"], name="fees_feesca_frequen_3aa7e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feescategory",
            index=models.Index(
                fields=["is_recurring"], name="fees_feesca_is_recu_8acccc_idx"
            ),
        ),
    ]
