# Generated by Django 5.2 on 2026-04-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0004_alter_feescategory_applicability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdiscount",
            name="override_category_matrix",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-category discount overrides for this student. Maps FeesCategory.category_type → discount %. Example: {"TUITION": 40, "BOARDING": 0}. Only used when policy.value_mode is CATEGORY_MATRIX. Categories not listed fall through to the policy matrix. Do not set alongside other override fields.',
                verbose_name="Override category matrix",
            ),
        ),
        migrations.AddField(
            model_name="studentdiscount",
            name="override_tier_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Caps the tier-calculated discount at this value for this student. Tier logic still runs normally — only the result is capped. Only meaningful when policy.value_mode is TIERED. Do not set alongside other override fields.",
                max_digits=12,
                null=True,
                verbose_name="Override tier cap",
            ),
        ),
        migrations.AlterField(
            model_name="studentdiscount",
            name="override_fixed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Replaces the policy calculation entirely with this fixed amount cap for this student. Do not set alongside other override fields.",
                max_digits=12,
                null=True,
                verbose_name="Override fixed amount",
            ),
        ),
        migrations.AlterField(
            model_name="studentdiscount",
            name="override_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Replaces the policy calculation entirely with this flat % for this student. Do not set alongside other override fields.",
                max_digits=5,
                null=True,
                verbose_name="Override %",
            ),
        ),
    ]
