"""
Django settings for schoolara project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add the 'apps' directory to the Python path to show where apps are located
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# =============================================================================
# SECURITY
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f70nbgoweb^5ry54plu30k@_fpt60klja0r)(-t^!1l*xc5mh7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Schoolara apps
    'core',
    'accounts',
    'students',
    'boarding',
    'discipline',
    'documents',
    'academics',
    'exams',
    'hr',
    'fees',
    'finance',
    'inventory',
    'uniforms',
    'utils',

    # Third-party apps
    'django.contrib.humanize',
    'widget_tweaks',
]

# =============================================================================
# MIDDLEWARE  (ORDER MATTERS)
# =============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 1 — Sets request.school and DB routing context (must be first of ours)
    'schoolara.middleware.SchoolDatabaseMiddleware',

    # 2 — Activates the school's operational timezone for the request
    'core.timezone_middleware.SchoolTimezoneMiddleware',

    # 3 — Captures user/IP/session for audit trail (needs timezone active)
    'utils.middleware.AuditContextMiddleware',

    # 4 — Detects stale exchange rates; triggers async update if needed.
    #     Never makes HTTP calls inline — queues a Celery task or logs a warning.
    #     Requires SchoolDatabaseMiddleware to have run first (needs request.school).
    'core.middleware.ExchangeRateMiddleware',
]

# =============================================================================
# IMAGE CROPPING
# =============================================================================

THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'easy_thumbnails.processors.filters',
)

IMAGE_CROPPING_THUMB_SIZE = (300, 300)
IMAGE_CROPPING_SIZE_WARNING = True

# =============================================================================
# URL CONFIGURATION
# =============================================================================

ROOT_URLCONF = 'schoolara.urls'

# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Django defaults
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Branding & user
                'core.context_processors.school_branding',
                'core.context_processors.user_preferences',
                'core.context_processors.theme_colors',
                'core.context_processors.user_security_context',
                'core.context_processors.navigation_permissions',

                # Academic & financial
                'core.context_processors.school_configuration',
                'core.context_processors.active_academic_session',
                'core.context_processors.active_fiscal_period',
                'core.context_processors.payment_methods_context',
            ],
            'libraries': {
                'custom_filters':  'utils.templatetags.custom_filters',
                'currency_filters': 'core.templatetags.currency_filters',
                'hr_filters':      'hr.templatetags.hr_filters',
                'exam_filters':    'exams.templatetags.exam_filters',
                'fees_tags':       'fees.templatetags.fees_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'schoolara.wsgi.application'

# =============================================================================
# DATABASES
# =============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'schools_core_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    'atepi_palabek': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'atepi_palabek_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    'atepi_pajok': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'atepi_pajok_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
}

DATABASE_ROUTERS = ['schoolara.routers.SchoolRouter']

# =============================================================================
# AUTHENTICATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTHENTICATION_BACKENDS = [
    'accounts.backends.SchoolAuthBackend',       # School-specific authentication
    'accounts.backends.PermissionBackend',       # Role-based permissions
    'django.contrib.auth.backends.ModelBackend', # Fallback
]

# =============================================================================
# INTERNATIONALISATION
# =============================================================================

LANGUAGE_CODE = 'en-us'

# Server timezone stays UTC — school-local time is handled per-school via
# SchoolTimezoneMiddleware and SchoolConfiguration.operational_timezone.
TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ   = True

# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CACHE
# Required by ExchangeRateMiddleware for staleness-check throttling.
# For production, replace LocMemCache with Redis or Memcached so that
# the cache is shared across all worker processes/gunicorn workers.
# =============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'schoolara-cache',
        'TIMEOUT': 3600,  # 1 hour default TTL
    }
}

# Production example (Redis):
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }

# =============================================================================
# EXCHANGE RATE API KEYS
# Set these in environment variables — never hard-code in source control.
#
# ExchangeRate-API: free tier, no key required (tried first).
# Fixer.io:         free tier requires key — https://fixer.io/
# OpenExchangeRates: free tier requires key — https://openexchangerates.org/
#
# Leave blank to use manual rate entry only.
# =============================================================================

FIXER_API_KEY        = os.environ.get('FIXER_API_KEY', '')
OPENEXCHANGE_API_KEY = os.environ.get('OPENEXCHANGE_API_KEY', '')

# =============================================================================
# CELERY  (optional — remove this section if not using Celery)
# If Celery is not configured, exchange rates are updated via cron +
# management command instead:
#   0 */6 * * *  python manage.py update_exchange_rates >> /var/log/exchange_rates.log 2>&1
# =============================================================================

# CELERY_BROKER_URL    = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
# CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'UTC'
#
# CELERY_BEAT_SCHEDULE = {
#     'update-exchange-rates': {
#         'task': 'core.update_exchange_rates',
#         'schedule': crontab(minute=0, hour='*/6'),  # every 6 hours
#     },
# }

# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'students': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}