"""
Django settings for schoolara project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add the 'apps' directory to the Python path to show where apps are located
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f70nbgoweb^5ry54plu30k@_fpt60klja0r)(-t^!1l*xc5mh7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Schoolara apps
    'core',
    'accounts',
    'students',
    'boarding',
    'discipline',
    'documents',
    'academics',
    'exams',
    'hr',
    'fees',
    'finance',
    'inventory',
    'uniforms',
    'utils',

    # Third-party Apps
    'django.contrib.humanize',
    'widget_tweaks',   
]


# Image Cropping Configuration
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'easy_thumbnails.processors.scale_and_crop',
    'easy_thumbnails.processors.filters',
)

# Optional: Image cropping widget settings
IMAGE_CROPPING_THUMB_SIZE = (300, 300)
IMAGE_CROPPING_SIZE_WARNING = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # ✅ School Management System Middlewares (ORDER MATTERS!)
    'schoolara.middleware.SchoolDatabaseMiddleware',           # 1️⃣ Sets request.school_timezone
    'schoolara.timezone_middleware.SchoolTimezoneMiddleware',  # 2️⃣ Activates timezone
    
    # ✅ Audit middleware - NOW can capture school timezone
    'utils.middleware.AuditContextMiddleware',  # 3️⃣ Captures context after timezone is set
]

# Logging configuration for debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'students': {  # Add this - replace 'students' with your app name
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'INFO',  # Changed to DEBUG to see SQL queries
            'propagate': False,
        },
    },
}

# Cache configuration (required for middleware)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 3600,  # 1 hour
    }
}

ROOT_URLCONF = 'schoolara.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',   # ← project-wide templates
        ],
        'APP_DIRS': True,            # ← enables app templates
        'OPTIONS': {
            'context_processors': [
                # Django defaults
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # Accounts context processors (user, school, theme)
                'accounts.context_processors.active_school',
                'accounts.context_processors.user_context',
                'accounts.context_processors.user_theme_preferences',
                'accounts.context_processors.theme_colors',
                'accounts.context_processors.user_security_context',
                'accounts.context_processors.navigation_permissions',
                'accounts.context_processors.user_notifications_count',
                
                # Core context processors (financial, configuration, fiscal)
                'core.context_processors.school_configuration',      # ✅ Exists
                'core.context_processors.active_academic_session',   # ✅ Exists
                'core.context_processors.active_fiscal_period',      # ✅ Exists
                'core.context_processors.payment_methods_context',   # ✅ Exists
            ],
            'libraries': {
                # Custom template tag libraries
                'custom_filters': 'utils.templatetags.custom_filters',
                'currency_filters': 'core.templatetags.currency_filters',
                'hr_filters': 'hr.templatetags.hr_filters',
                'exam_filters': 'exams.templatetags.exam_filters',
                'fees_tags': 'fees.templatetags.fees_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'schoolara.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'schools_core_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    'atepi_palabek': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'atepi_palabek_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    'atepi_pajok': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'atepi_pajok_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
}

DATABASE_ROUTERS = ['schoolara.routers.SchoolRouter']

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication Backends - Custom email authentication
AUTHENTICATION_BACKENDS = [
    'accounts.backends.SchoolAuthBackend',        # School-specific authentication
    'accounts.backends.PermissionBackend',        # Role-based permissions
    'django.contrib.auth.backends.ModelBackend',  # Fallback
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',     # ← Project-level static folder
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
