# Generated by Django 5.2 on 2025-12-30 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("core", "0002_initial"),
        ("hr", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplinaryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "incident_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this incident",
                        max_length=20,
                        unique=True,
                        verbose_name="Incident Number",
                    ),
                ),
                (
                    "incident_date",
                    models.DateField(db_index=True, verbose_name="Incident Date"),
                ),
                (
                    "incident_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Incident Time"
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("tardiness", "Tardiness"),
                            ("absence", "Unexcused Absence"),
                            ("disrespect", "Disrespect to Staff"),
                            ("bullying", "Bullying"),
                            ("fighting", "Fighting"),
                            ("academic_dishonesty", "Academic Dishonesty"),
                            ("inappropriate_behavior", "Inappropriate Behavior"),
                            ("dress_code", "Dress Code Violation"),
                            ("technology_misuse", "Technology Misuse"),
                            ("vandalism", "Vandalism"),
                            ("substance_abuse", "Substance Abuse"),
                            ("theft", "Theft"),
                            ("insubordination", "Insubordination"),
                            ("disruption", "Classroom Disruption"),
                            ("truancy", "Truancy"),
                            ("harassment", "Harassment"),
                            ("inappropriate_language", "Inappropriate Language"),
                            ("safety_violation", "Safety Violation"),
                            ("property_damage", "Property Damage"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Incident Type",
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                            ("severe", "Severe"),
                        ],
                        db_index=True,
                        default="minor",
                        max_length=10,
                        verbose_name="Severity Level",
                    ),
                ),
                (
                    "incident_description",
                    models.TextField(
                        help_text="Detailed description of what happened",
                        verbose_name="Incident Description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Location"
                    ),
                ),
                (
                    "class_period",
                    models.CharField(
                        blank=True,
                        help_text="Class or period when incident occurred",
                        max_length=50,
                        verbose_name="Class Period",
                    ),
                ),
                (
                    "reported_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who reported this incident",
                        max_length=50,
                        null=True,
                        verbose_name="Reported By ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Report Date"
                    ),
                ),
                ("witnesses", models.TextField(blank=True, verbose_name="Witnesses")),
                (
                    "investigated_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who investigated this incident",
                        max_length=50,
                        null=True,
                        verbose_name="Investigated By ID",
                    ),
                ),
                (
                    "investigation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Investigation Date"
                    ),
                ),
                (
                    "investigation_notes",
                    models.TextField(blank=True, verbose_name="Investigation Notes"),
                ),
                (
                    "evidence_collected",
                    models.TextField(blank=True, verbose_name="Evidence Collected"),
                ),
                (
                    "student_statement",
                    models.TextField(
                        blank=True,
                        help_text="Student's account of the incident",
                        verbose_name="Student Statement",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("verbal_warning", "Verbal Warning"),
                            ("written_warning", "Written Warning"),
                            ("detention", "Detention"),
                            ("in_school_suspension", "In-School Suspension"),
                            ("out_of_school_suspension", "Out-of-School Suspension"),
                            ("expulsion", "Expulsion"),
                            ("counseling", "Counseling Required"),
                            ("parent_conference", "Parent Conference"),
                            ("community_service", "Community Service"),
                            ("behavioral_contract", "Behavioral Contract"),
                            ("loss_of_privileges", "Loss of Privileges"),
                            ("restitution", "Restitution Required"),
                            ("referral_external", "External Referral"),
                            ("mentoring", "Mentoring Program"),
                            ("probation", "Academic/Behavioral Probation"),
                            ("no_action", "No Action Taken"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Primary Action Taken",
                    ),
                ),
                (
                    "additional_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of additional actions taken",
                        verbose_name="Additional Actions",
                    ),
                ),
                (
                    "action_description",
                    models.TextField(
                        help_text="Detailed description of actions taken",
                        verbose_name="Action Description",
                    ),
                ),
                (
                    "action_start_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date when action begins (e.g., suspension start)",
                        null=True,
                        verbose_name="Action Start Date",
                    ),
                ),
                (
                    "action_end_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date when action ends (e.g., suspension end)",
                        null=True,
                        verbose_name="Action End Date",
                    ),
                ),
                (
                    "action_authorized_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who authorized the disciplinary action",
                        max_length=50,
                        null=True,
                        verbose_name="Action Authorized By ID",
                    ),
                ),
                (
                    "authorization_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Authorization Date"
                    ),
                ),
                (
                    "parent_notified",
                    models.BooleanField(default=False, verbose_name="Parent Notified"),
                ),
                (
                    "parent_notification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Parent Notification Date"
                    ),
                ),
                (
                    "notification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phone", "Phone Call"),
                            ("email", "Email"),
                            ("letter", "Letter"),
                            ("in_person", "In Person"),
                            ("sms", "SMS"),
                            ("multiple", "Multiple Methods"),
                        ],
                        max_length=20,
                        verbose_name="Notification Method",
                    ),
                ),
                (
                    "notified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who notified the parent",
                        max_length=50,
                        null=True,
                        verbose_name="Notified By ID",
                    ),
                ),
                (
                    "parent_response",
                    models.TextField(
                        blank=True,
                        help_text="Parent's response to notification",
                        verbose_name="Parent Response",
                    ),
                ),
                (
                    "parent_meeting_scheduled",
                    models.BooleanField(
                        default=False, verbose_name="Parent Meeting Scheduled"
                    ),
                ),
                (
                    "parent_meeting_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Parent Meeting Date"
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, verbose_name="Follow-up Required"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Follow-up Date"
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(blank=True, verbose_name="Follow-up Notes"),
                ),
                (
                    "follow_up_completed",
                    models.BooleanField(
                        default=False, verbose_name="Follow-up Completed"
                    ),
                ),
                (
                    "monitoring_required",
                    models.BooleanField(
                        default=False, verbose_name="Ongoing Monitoring Required"
                    ),
                ),
                (
                    "monitoring_period_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Monitoring Period (Days)"
                    ),
                ),
                (
                    "progress_updates",
                    models.TextField(blank=True, verbose_name="Progress Updates"),
                ),
                (
                    "record_status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("investigating", "Under Investigation"),
                            ("action_pending", "Action Pending"),
                            ("action_taken", "Action Taken"),
                            ("resolved", "Resolved"),
                            ("appealed", "Under Appeal"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="reported",
                        max_length=15,
                        verbose_name="Record Status",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Resolved"
                    ),
                ),
                (
                    "resolution_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolution Date"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution Notes"),
                ),
                (
                    "resolved_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who resolved this record",
                        max_length=50,
                        null=True,
                        verbose_name="Resolved By ID",
                    ),
                ),
                (
                    "appealed",
                    models.BooleanField(default=False, verbose_name="Appealed"),
                ),
                (
                    "appeal_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Appeal Date"
                    ),
                ),
                (
                    "appeal_notes",
                    models.TextField(blank=True, verbose_name="Appeal Notes"),
                ),
                (
                    "appeal_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upheld", "Upheld"),
                            ("modified", "Modified"),
                            ("overturned", "Overturned"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        verbose_name="Appeal Outcome",
                    ),
                ),
                (
                    "preventive_measures",
                    models.TextField(
                        blank=True,
                        help_text="Measures put in place to prevent similar incidents",
                        verbose_name="Preventive Measures",
                    ),
                ),
                (
                    "lessons_learned",
                    models.TextField(
                        blank=True,
                        help_text="Key insights from this incident",
                        verbose_name="Lessons Learned",
                    ),
                ),
                (
                    "intervention_plan",
                    models.TextField(
                        blank=True,
                        help_text="Specific interventions or support for student",
                        verbose_name="Intervention Plan",
                    ),
                ),
                (
                    "counseling_recommended",
                    models.BooleanField(
                        default=False, verbose_name="Counseling Recommended"
                    ),
                ),
                (
                    "counseling_completed",
                    models.BooleanField(
                        default=False, verbose_name="Counseling Completed"
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        help_text="Academic session when incident occurred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_records",
                        to="core.fiscalperiod",
                        verbose_name="Academic Session",
                    ),
                ),
                (
                    "other_students_involved",
                    models.ManyToManyField(
                        blank=True,
                        related_name="involved_disciplinary_records",
                        to="students.student",
                        verbose_name="Other Students Involved",
                    ),
                ),
                (
                    "related_subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subject/class where incident occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                        verbose_name="Related Subject",
                    ),
                ),
                (
                    "staff_witnesses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="witnessed_incidents",
                        to="hr.staff",
                        verbose_name="Staff Witnesses",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinary_records",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplinary Record",
                "verbose_name_plural": "Disciplinary Records",
                "ordering": ["-incident_date", "-report_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "incident_date"],
                        name="discipline__student_2dc614_idx",
                    ),
                    models.Index(
                        fields=["incident_type"], name="discipline__inciden_2f6c9f_idx"
                    ),
                    models.Index(
                        fields=["severity_level"], name="discipline__severit_6a2810_idx"
                    ),
                    models.Index(
                        fields=["record_status"], name="discipline__record__b3f27e_idx"
                    ),
                    models.Index(
                        fields=["is_resolved"], name="discipline__is_reso_243637_idx"
                    ),
                    models.Index(
                        fields=["action_taken"], name="discipline__action__e280aa_idx"
                    ),
                    models.Index(
                        fields=["academic_session"],
                        name="discipline__academi_0e4625_idx",
                    ),
                    models.Index(
                        fields=["incident_number"],
                        name="discipline__inciden_165e63_idx",
                    ),
                    models.Index(
                        fields=["action_start_date", "action_end_date"],
                        name="discipline__action__bea793_idx",
                    ),
                    models.Index(
                        fields=["student", "record_status"],
                        name="discipline__student_7d780f_idx",
                    ),
                    models.Index(
                        fields=["incident_date", "severity_level"],
                        name="discipline__inciden_a35ce5_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("action_end_date__gte", models.F("action_start_date")),
                            ("action_end_date__isnull", True),
                            _connector="OR",
                        ),
                        name="action_end_after_start",
                    )
                ],
            },
        ),
    ]
