# Generated by Django 5.2 on 2025-12-30 10:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dormitory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Dormitory Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Dormitory Code",
                    ),
                ),
                (
                    "dormitory_type",
                    models.CharField(
                        choices=[
                            ("BOYS", "Boys Dormitory"),
                            ("GIRLS", "Girls Dormitory"),
                            ("MIXED", "Mixed Dormitory"),
                            ("STAFF", "Staff Quarters"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Dormitory Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Building"
                    ),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="Floor"),
                ),
                (
                    "wing",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Wing/Section"
                    ),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Total Capacity",
                    ),
                ),
                (
                    "current_occupancy",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Current Occupancy",
                    ),
                ),
                (
                    "room_count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Number of Rooms",
                    ),
                ),
                (
                    "beds_per_room",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Beds per Room",
                    ),
                ),
                (
                    "has_bathroom",
                    models.BooleanField(default=True, verbose_name="Has Bathroom"),
                ),
                (
                    "has_study_area",
                    models.BooleanField(default=False, verbose_name="Has Study Area"),
                ),
                (
                    "has_common_room",
                    models.BooleanField(default=False, verbose_name="Has Common Room"),
                ),
                (
                    "has_laundry",
                    models.BooleanField(
                        default=False, verbose_name="Has Laundry Facilities"
                    ),
                ),
                (
                    "has_kitchen",
                    models.BooleanField(default=False, verbose_name="Has Kitchen"),
                ),
                (
                    "has_wifi",
                    models.BooleanField(default=False, verbose_name="Has WiFi"),
                ),
                (
                    "has_security",
                    models.BooleanField(default=True, verbose_name="Has Security"),
                ),
                (
                    "facilities_description",
                    models.TextField(blank=True, verbose_name="Facilities Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "is_available_for_new_admissions",
                    models.BooleanField(
                        default=True,
                        help_text="Whether new students can be assigned to this dormitory",
                        verbose_name="Available for New Admissions",
                    ),
                ),
                (
                    "maintenance_status",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent Condition"),
                            ("GOOD", "Good Condition"),
                            ("FAIR", "Fair Condition"),
                            ("NEEDS_REPAIR", "Needs Repair"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("CONDEMNED", "Condemned"),
                        ],
                        db_index=True,
                        default="GOOD",
                        max_length=20,
                        verbose_name="Maintenance Status",
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Maintenance Date"
                    ),
                ),
                (
                    "next_maintenance_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Maintenance Due"
                    ),
                ),
                (
                    "rules_and_regulations",
                    models.TextField(blank=True, verbose_name="Rules and Regulations"),
                ),
                (
                    "emergency_procedures",
                    models.TextField(blank=True, verbose_name="Emergency Procedures"),
                ),
                (
                    "dormitory_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Dormitory Phone"
                    ),
                ),
                (
                    "dormitory_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Dormitory Email"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Administrative Notes"),
                ),
            ],
            options={
                "verbose_name": "Dormitory",
                "verbose_name_plural": "Dormitories",
                "ordering": ["dormitory_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="BoardingEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "boarding_type",
                    models.CharField(
                        choices=[
                            ("FULL_BOARDER", "Full Boarder"),
                            ("WEEKLY_BOARDER", "Weekly Boarder"),
                            ("FLEXI_BOARDER", "Flexible Boarder"),
                        ],
                        help_text="Type of boarding arrangement",
                        max_length=20,
                        verbose_name="Boarding Type",
                    ),
                ),
                (
                    "auto_create_invoice",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create invoice when enrollment is approved",
                        verbose_name="Auto-Create Invoice",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Room Number"
                    ),
                ),
                (
                    "bed_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Bed Number"
                    ),
                ),
                (
                    "boarding_roll_number",
                    models.CharField(
                        blank=True,
                        help_text="Roll number for dormitory attendance and management",
                        max_length=20,
                        verbose_name="Boarding Roll Number",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(verbose_name="Boarding Enrollment Date"),
                ),
                (
                    "effective_start_date",
                    models.DateField(
                        help_text="Date when boarding actually starts",
                        verbose_name="Effective Start Date",
                    ),
                ),
                (
                    "effective_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when boarding ends",
                        null=True,
                        verbose_name="Effective End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "guardian_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether guardian has provided written consent",
                        verbose_name="Guardian Consent",
                    ),
                ),
                (
                    "consent_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Consent Date"
                    ),
                ),
                (
                    "consent_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="boarding/consents/%Y/%m/",
                        verbose_name="Consent Document",
                    ),
                ),
                (
                    "boarding_days",
                    models.JSONField(
                        blank=True,
                        help_text="JSON array of days (e.g., ['Monday', 'Tuesday', 'Wednesday'])",
                        null=True,
                        verbose_name="Boarding Days",
                    ),
                ),
                (
                    "dietary_requirements",
                    models.TextField(blank=True, verbose_name="Dietary Requirements"),
                ),
                (
                    "medical_requirements",
                    models.TextField(blank=True, verbose_name="Medical Requirements"),
                ),
                (
                    "special_accommodations",
                    models.TextField(blank=True, verbose_name="Special Accommodations"),
                ),
                (
                    "emergency_contact_during_boarding",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Emergency Contact During Boarding",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Emergency Contact Name",
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Emergency Contact Relationship",
                    ),
                ),
                (
                    "reason_for_boarding",
                    models.TextField(blank=True, verbose_name="Reason for Boarding"),
                ),
                (
                    "termination_reason",
                    models.TextField(blank=True, verbose_name="Termination Reason"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Administrative Notes"),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_enrollments",
                        to="academics.academicsession",
                        verbose_name="Academic Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boarding Enrollment",
                "verbose_name_plural": "Boarding Enrollments",
                "ordering": [
                    "-academic_session__start_date",
                    "dormitory",
                    "boarding_roll_number",
                ],
            },
        ),
    ]
