# Generated by Django 5.2 on 2025-12-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boarding", "0001_initial"),
        ("fees", "0001_initial"),
        ("hr", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardingenrollment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_boarding_enrollments",
                to="hr.staff",
                verbose_name="Approved By",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="boarding_invoice",
            field=models.OneToOneField(
                blank=True,
                help_text="Invoice generated for this boarding enrollment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boarding_enrollment",
                to="fees.feeinvoice",
                verbose_name="Boarding Invoice",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="consenting_guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boarding_consents",
                to="students.guardian",
                verbose_name="Consenting Guardian",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_enrollments",
                to="students.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="dormitory",
            name="assistant_dormitory_master",
            field=models.ForeignKey(
                blank=True,
                help_text="Assistant/deputy dormitory master",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assisted_dormitories",
                to="hr.staff",
                verbose_name="Assistant Dormitory Master",
            ),
        ),
        migrations.AddField(
            model_name="dormitory",
            name="dormitory_master",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary person responsible for this dormitory",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_dormitories",
                to="hr.staff",
                verbose_name="Dormitory Master",
            ),
        ),
        migrations.AddField(
            model_name="boardingenrollment",
            name="dormitory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boarding_enrollments",
                to="boarding.dormitory",
                verbose_name="Dormitory",
            ),
        ),
        migrations.AddIndex(
            model_name="dormitory",
            index=models.Index(
                fields=["dormitory_type", "is_active"],
                name="boarding_do_dormito_57b0e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dormitory",
            index=models.Index(fields=["code"], name="boarding_do_code_0ae0a1_idx"),
        ),
        migrations.AddIndex(
            model_name="dormitory",
            index=models.Index(
                fields=["maintenance_status"], name="boarding_do_mainten_67d371_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dormitory",
            index=models.Index(
                fields=["is_available_for_new_admissions"],
                name="boarding_do_is_avai_41110b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dormitory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_occupancy__lte", models.F("total_capacity"))
                ),
                name="occupancy_not_exceed_capacity",
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["student", "academic_session"],
                name="boarding_bo_student_9b4dc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["boarding_type"], name="boarding_bo_boardin_2fdea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(fields=["status"], name="boarding_bo_status_44eb28_idx"),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["dormitory", "status"], name="boarding_bo_dormito_b2688a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["enrollment_date"], name="boarding_bo_enrollm_79bc35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["effective_start_date"], name="boarding_bo_effecti_90f32b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardingenrollment",
            index=models.Index(
                fields=["boarding_roll_number"], name="boarding_bo_boardin_8a1c29_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardingenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "PENDING"])),
                fields=("student", "academic_session"),
                name="unique_active_boarding_per_student_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardingenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("boarding_roll_number__isnull", False),
                    models.Q(("boarding_roll_number", ""), _negated=True),
                    ("status", "ACTIVE"),
                ),
                fields=("dormitory", "academic_session", "boarding_roll_number"),
                name="unique_boarding_roll_per_dormitory_session",
            ),
        ),
    ]
