# Generated by Django 5.2 on 2026-04-04 05:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boarding", "0002_initial"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dormitory",
            name="occupancy_not_exceed_capacity",
        ),
        migrations.RemoveIndex(
            model_name="dormitory",
            name="boarding_do_code_0ae0a1_idx",
        ),
        migrations.RemoveField(
            model_name="dormitory",
            name="current_occupancy",
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="auto_create_invoice",
            field=models.BooleanField(
                default=True,
                help_text="When True, the post_save signal attempts invoice creation. Set to False when BulkBoardingEnrollmentService handles invoices explicitly.",
                verbose_name="Auto-Create Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="boarding_days",
            field=models.JSONField(
                blank=True,
                help_text="Required for Flexible Boarders — JSON list of day names, e.g. ['Monday', 'Tuesday', 'Wednesday']",
                null=True,
                verbose_name="Boarding Days",
            ),
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="boarding_roll_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated sequential number per dormitory and session",
                max_length=20,
                verbose_name="Boarding Roll Number",
            ),
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="boarding_type",
            field=models.CharField(
                choices=[
                    ("FULL_BOARDER", "Full Boarder"),
                    ("WEEKLY_BOARDER", "Weekly Boarder"),
                    ("FLEXI_BOARDER", "Flexible Boarder"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Boarding Type",
            ),
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="effective_end_date",
            field=models.DateField(
                blank=True,
                help_text="Date when boarding ends — defaults to session end date",
                null=True,
                verbose_name="Effective End Date",
            ),
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="effective_start_date",
            field=models.DateField(
                help_text="Date when boarding actually begins",
                verbose_name="Effective Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="emergency_contact_during_boarding",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Emergency Contact Phone"
            ),
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="enrollment_date",
            field=models.DateField(
                help_text="Administrative date the enrollment was recorded",
                verbose_name="Boarding Enrollment Date",
            ),
        ),
        migrations.AlterField(
            model_name="boardingenrollment",
            name="guardian_consent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the consenting guardian has provided written consent",
                verbose_name="Guardian Consent",
            ),
        ),
        migrations.AlterField(
            model_name="dormitory",
            name="assistant_dormitory_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assisted_dormitories",
                to="hr.staff",
                verbose_name="Assistant Dormitory Master",
            ),
        ),
        migrations.AlterField(
            model_name="dormitory",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Unique short identifier for this dormitory (e.g., DORM-B-001)",
                max_length=20,
                unique=True,
                verbose_name="Dormitory Code",
            ),
        ),
        migrations.AlterField(
            model_name="dormitory",
            name="dormitory_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_dormitories",
                to="hr.staff",
                verbose_name="Dormitory Master",
            ),
        ),
        migrations.AlterField(
            model_name="dormitory",
            name="is_available_for_new_admissions",
            field=models.BooleanField(
                default=True,
                help_text="Un-check to stop new students being assigned here",
                verbose_name="Available for New Admissions",
            ),
        ),
        migrations.AlterField(
            model_name="dormitory",
            name="room_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Rooms"
            ),
        ),
        migrations.AlterField(
            model_name="dormitory",
            name="total_capacity",
            field=models.PositiveIntegerField(
                help_text="Maximum number of students this dormitory can hold",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Total Capacity",
            ),
        ),
    ]
