# Generated by Django 5.2 on 2025-12-30 10:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("core", "0002_initial"),
        ("fees", "0001_initial"),
        ("finance", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Measurement Name"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UNIFORM", "Uniform Measurements"),
                            ("SPORTS", "Sports Equipment"),
                            ("HEALTH", "Health Measurements"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="UNIFORM",
                        max_length=15,
                        verbose_name="Category",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum reasonable value",
                        max_digits=6,
                        null=True,
                        verbose_name="Minimum Value",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum reasonable value",
                        max_digits=6,
                        null=True,
                        verbose_name="Maximum Value",
                    ),
                ),
                (
                    "applicable_age_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Minimum Age"
                    ),
                ),
                (
                    "applicable_age_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maximum Age"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=100, verbose_name="Display Order"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Is Required"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit of measurement (cm, inches, etc.)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurement_types",
                        to="core.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Type",
                "verbose_name_plural": "Measurement Types",
                "ordering": ["category", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Measurement Value",
                    ),
                ),
                (
                    "measurement_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Measurement Date",
                    ),
                ),
                (
                    "measurement_context",
                    models.CharField(
                        choices=[
                            ("ADMISSION", "Admission"),
                            ("ANNUAL", "Annual Check"),
                            ("UNIFORM_ORDER", "Uniform Order"),
                            ("HEALTH_CHECK", "Health Check"),
                            ("UPDATE", "Update/Correction"),
                            ("OTHER", "Other"),
                        ],
                        default="ANNUAL",
                        max_length=50,
                        verbose_name="Measurement Context",
                    ),
                ),
                (
                    "measurement_method",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual (Tape Measure)"),
                            ("DIGITAL", "Digital Tool"),
                            ("ESTIMATED", "Estimated"),
                            ("SELF_REPORTED", "Self Reported"),
                            ("PARENT_REPORTED", "Parent Reported"),
                        ],
                        default="MANUAL",
                        max_length=50,
                        verbose_name="Measurement Method",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Verified"
                    ),
                ),
                (
                    "verified_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who verified this measurement",
                        max_length=50,
                        null=True,
                        verbose_name="Verified By ID",
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verification Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this is the most current measurement",
                        verbose_name="Is Current",
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_measurements",
                        to="academics.academicsession",
                        verbose_name="Academic Session",
                    ),
                ),
                (
                    "measurement_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_measurements",
                        to="uniforms.measurementtype",
                        verbose_name="Measurement Type",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Measurement",
                "verbose_name_plural": "Student Measurements",
                "ordering": ["-measurement_date", "measurement_type__display_order"],
            },
        ),
        migrations.CreateModel(
            name="UniformItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Item Name")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Item Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("UNIFORM", "School Uniform"),
                            ("SPORTS", "Sports Uniform"),
                            ("PE", "PE Kit"),
                            ("ACCESSORY", "Accessory"),
                            ("SHOES", "Shoes"),
                            ("BAG", "School Bag"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="UNIFORM",
                        max_length=20,
                        verbose_name="Item Type",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unisex")],
                        default="U",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Category"
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Subcategory"
                    ),
                ),
                (
                    "requires_sizing",
                    models.BooleanField(default=True, verbose_name="Requires Sizing"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost price per unit (for COGS calculation)",
                        max_digits=10,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Selling price per unit",
                        max_digits=10,
                        verbose_name="Selling Price",
                    ),
                ),
                (
                    "markup_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Markup percentage (calculated: (selling_price - unit_cost) / unit_cost * 100)",
                        max_digits=5,
                        verbose_name="Markup Percentage",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Barcode"
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(default=0, verbose_name="Current Stock"),
                ),
                (
                    "reorder_level",
                    models.IntegerField(default=10, verbose_name="Reorder Level"),
                ),
                (
                    "maximum_stock",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maximum Stock"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Supplier Name"
                    ),
                ),
                (
                    "supplier_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Supplier Contact"
                    ),
                ),
                (
                    "supplier_item_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Supplier Item Code"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uniforms/items/",
                        verbose_name="Item Image",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, verbose_name="Color"),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Material"
                    ),
                ),
                (
                    "care_instructions",
                    models.TextField(blank=True, verbose_name="Care Instructions"),
                ),
                (
                    "is_taxable",
                    models.BooleanField(default=True, verbose_name="Is Taxable"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Is Mandatory"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cogs_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cost of Goods Sold expense account (auto-assigned if blank)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_items_cogs",
                        to="finance.account",
                        verbose_name="COGS Account",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset account for this inventory item (auto-assigned from category if blank)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_items_inventory",
                        to="finance.account",
                        verbose_name="Inventory Account",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Revenue account for sales (auto-assigned if blank)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_items_revenue",
                        to="finance.account",
                        verbose_name="Revenue Account",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tax rate to apply (uses default if blank)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uniform_items",
                        to="core.taxrate",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.ForeignKey(
                        help_text="Unit of measure for inventory tracking (pcs, dozen, etc.)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_items",
                        to="core.unitofmeasure",
                        verbose_name="Unit of Measure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniform Item",
                "verbose_name_plural": "Uniform Items",
                "ordering": ["item_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="UniformPurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="PO Number",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(max_length=100, verbose_name="Supplier Name"),
                ),
                (
                    "supplier_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Supplier Contact"
                    ),
                ),
                (
                    "supplier_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Supplier Email"
                    ),
                ),
                (
                    "supplier_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Supplier Phone"
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Order Date",
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expected Delivery Date"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Actual Delivery Date"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Shipping Cost",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Payment Terms"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Paid Amount",
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Balance Due",
                    ),
                ),
                (
                    "auto_create_journal_entry",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create journal entry when goods are received",
                        verbose_name="Auto-Create Journal Entry",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("ORDERED", "Ordered"),
                            ("RECEIVED", "Received"),
                            ("PARTIAL", "Partially Received"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_by_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Approved By ID",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fiscal period when PO was created",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_purchase_orders",
                        to="core.fiscalperiod",
                        verbose_name="Fiscal Period",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Journal entry for goods receipt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uniform_purchase_orders",
                        to="finance.journalentry",
                        verbose_name="Journal Entry",
                    ),
                ),
                (
                    "payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Accounts Payable account to credit when PO is received",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_purchase_orders",
                        to="finance.account",
                        verbose_name="Accounts Payable Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniform Purchase Order",
                "verbose_name_plural": "Uniform Purchase Orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="UniformSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "sale_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Sale Number",
                    ),
                ),
                (
                    "sale_type",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("ISSUANCE", "Free Issuance"),
                            ("LOAN", "Temporary Loan"),
                            ("REPLACEMENT", "Replacement"),
                        ],
                        default="SALE",
                        max_length=20,
                        verbose_name="Sale Type",
                    ),
                ),
                (
                    "sale_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Sale Date",
                    ),
                ),
                (
                    "auto_create_invoice",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create fee invoice when sale is finalized",
                        verbose_name="Auto-Create Invoice",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Paid Amount",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Balance",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total cost of goods sold (calculated from unit costs)",
                        max_digits=12,
                        verbose_name="Total Cost (COGS)",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gross profit (total_amount - total_cost)",
                        max_digits=12,
                        verbose_name="Gross Profit",
                    ),
                ),
                (
                    "gross_margin_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gross margin percentage ((total_amount - total_cost) / total_amount * 100)",
                        max_digits=5,
                        verbose_name="Gross Margin %",
                    ),
                ),
                (
                    "auto_create_journal_entry",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create journal entries when sale is completed",
                        verbose_name="Auto-Create Journal Entry",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Payment"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partially Paid"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Payment Reference"
                    ),
                ),
                (
                    "issued_by_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Issued By ID",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Issued At"
                    ),
                ),
                (
                    "return_date",
                    models.DateField(
                        blank=True,
                        help_text="For loaned items",
                        null=True,
                        verbose_name="Return Date",
                    ),
                ),
                (
                    "discount_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for discount (staff child, sibling, etc.)",
                        max_length=200,
                        verbose_name="Discount Reason",
                    ),
                ),
                (
                    "discount_approved_by_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID who approved the discount",
                        max_length=50,
                        null=True,
                        verbose_name="Discount Approved By ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Internal Notes"),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniform_sales",
                        to="academics.academicsession",
                    ),
                ),
                (
                    "cogs_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cost of Goods Sold expense account to debit",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_sales_cogs",
                        to="finance.account",
                        verbose_name="COGS Account",
                    ),
                ),
                (
                    "fee_invoice",
                    models.OneToOneField(
                        blank=True,
                        help_text="Invoice generated for this uniform sale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uniform_sale",
                        to="fees.feeinvoice",
                        verbose_name="Fee Invoice",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        help_text="Fiscal period when this sale was recorded",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_sales",
                        to="core.fiscalperiod",
                        verbose_name="Fiscal Period",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Inventory asset account to credit (reduce inventory)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_sales_inventory",
                        to="finance.account",
                        verbose_name="Inventory Account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Journal entry for this uniform sale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uniform_sales",
                        to="finance.journalentry",
                        verbose_name="Journal Entry",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_sales",
                        to="core.paymentmethod",
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Accounts receivable to debit (if not paid immediately)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_sales_receivable",
                        to="finance.account",
                        verbose_name="Receivable Account",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Uniform sales revenue account to credit",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uniform_sales_revenue",
                        to="finance.account",
                        verbose_name="Revenue Account",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniform_sales",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniform Sale",
                "verbose_name_plural": "Uniform Sales",
                "ordering": ["-sale_date"],
            },
        ),
        migrations.CreateModel(
            name="UniformSize",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Size Name")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        unique=True,
                        verbose_name="Size Code",
                    ),
                ),
                (
                    "size_type",
                    models.CharField(
                        choices=[
                            ("NUMERIC", "Numeric (e.g., 32, 34, 36)"),
                            ("ALPHA", "Alphabetic (e.g., S, M, L, XL)"),
                            ("AGE_BASED", "Age-Based (e.g., 6-7 years)"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="ALPHA",
                        max_length=15,
                        verbose_name="Size Type",
                    ),
                ),
                (
                    "min_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Minimum Height (cm)",
                    ),
                ),
                (
                    "max_height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Maximum Height (cm)",
                    ),
                ),
                (
                    "min_chest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Minimum Chest (cm)",
                    ),
                ),
                (
                    "max_chest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Maximum Chest (cm)",
                    ),
                ),
                (
                    "min_waist",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Minimum Waist (cm)",
                    ),
                ),
                (
                    "max_waist",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Maximum Waist (cm)",
                    ),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Minimum Age"
                    ),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maximum Age"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=100, verbose_name="Display Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniform Size",
                "verbose_name_plural": "Uniform Sizes",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["size_type", "is_active"],
                        name="uniforms_un_size_ty_38d762_idx",
                    ),
                    models.Index(fields=["code"], name="uniforms_un_code_b6ed5b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UniformSaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit (for COGS calculation)",
                        max_digits=10,
                        verbose_name="Unit Cost",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Price"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of goods sold for this line",
                        max_digits=12,
                        verbose_name="Total Cost (COGS)",
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Tax Percentage",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Tax Amount",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Discount Percentage",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Discount Amount",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="uniforms.uniformsale",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uniform_sale_items",
                        to="core.taxrate",
                    ),
                ),
                (
                    "uniform_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_items",
                        to="uniforms.uniformitem",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_items",
                        to="uniforms.uniformsize",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniform Sale Item",
                "verbose_name_plural": "Uniform Sale Items",
                "ordering": ["sale", "uniform_item"],
            },
        ),
        migrations.CreateModel(
            name="UniformPurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.PositiveIntegerField(verbose_name="Quantity Ordered"),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantity Received"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Price"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="uniforms.uniformpurchaseorder",
                    ),
                ),
                (
                    "uniform_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_order_items",
                        to="uniforms.uniformitem",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_order_items",
                        to="uniforms.uniformsize",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Item",
                "verbose_name_plural": "Purchase Order Items",
                "ordering": ["purchase_order", "uniform_item"],
            },
        ),
        migrations.AddField(
            model_name="uniformitem",
            name="available_sizes",
            field=models.ManyToManyField(
                blank=True,
                related_name="uniform_items",
                to="uniforms.uniformsize",
                verbose_name="Available Sizes",
            ),
        ),
        migrations.CreateModel(
            name="StudentUniformSize",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "sizing_method",
                    models.CharField(
                        choices=[
                            ("MEASURED", "Based on Measurements"),
                            ("FITTED", "Physically Fitted"),
                            ("PREVIOUS_ORDER", "Based on Previous Order"),
                            ("PARENT_PROVIDED", "Parent Provided"),
                            ("ESTIMATED", "Estimated"),
                        ],
                        default="MEASURED",
                        max_length=20,
                        verbose_name="Sizing Method",
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Confidence"),
                            ("MEDIUM", "Medium Confidence"),
                            ("LOW", "Low Confidence"),
                        ],
                        default="HIGH",
                        max_length=15,
                        verbose_name="Confidence Level",
                    ),
                ),
                (
                    "recommendation_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Recommendation Date",
                    ),
                ),
                (
                    "alternative_sizes",
                    models.JSONField(
                        blank=True,
                        help_text="List of alternative size IDs",
                        null=True,
                        verbose_name="Alternative Sizes",
                    ),
                ),
                (
                    "growth_allowance",
                    models.BooleanField(default=True, verbose_name="Growth Allowance"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Current"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_uniform_sizes",
                        to="academics.academicsession",
                        verbose_name="Academic Session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniform_sizes",
                        to="students.student",
                        verbose_name="Student",
                    ),
                ),
                (
                    "uniform_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_size_recommendations",
                        to="uniforms.uniformitem",
                        verbose_name="Uniform Item",
                    ),
                ),
                (
                    "recommended_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_recommendations",
                        to="uniforms.uniformsize",
                        verbose_name="Recommended Size",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Uniform Size",
                "verbose_name_plural": "Student Uniform Sizes",
                "ordering": ["-recommendation_date"],
            },
        ),
        migrations.CreateModel(
            name="UniformStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Quantity in Stock"),
                ),
                (
                    "reserved_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Quantity reserved in pending sales",
                        verbose_name="Reserved Quantity",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Storage Location"
                    ),
                ),
                (
                    "bin_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Bin Number"
                    ),
                ),
                (
                    "total_cost_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value at cost price (quantity * unit_cost)",
                        max_digits=12,
                        verbose_name="Total Cost Value",
                    ),
                ),
                (
                    "total_selling_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total value at selling price (quantity * selling_price)",
                        max_digits=12,
                        verbose_name="Total Selling Value",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_records",
                        to="uniforms.uniformsize",
                    ),
                ),
                (
                    "uniform_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_records",
                        to="uniforms.uniformitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uniform Stock",
                "verbose_name_plural": "Uniform Stock",
                "ordering": ["uniform_item", "size"],
            },
        ),
        migrations.CreateModel(
            name="MeasurementSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was created (in school's operational timezone)",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this record was last updated (in school's operational timezone)",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who created this record",
                        max_length=50,
                        null=True,
                        verbose_name="Created By ID",
                    ),
                ),
                (
                    "updated_by_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of user who last updated this record",
                        max_length=50,
                        null=True,
                        verbose_name="Updated By ID",
                    ),
                ),
                (
                    "created_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was created",
                        null=True,
                        verbose_name="Created From IP",
                    ),
                ),
                (
                    "updated_from_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which this record was last updated",
                        null=True,
                        verbose_name="Updated From IP",
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True,
                        help_text="Explanation for why this change was made",
                        max_length=255,
                        null=True,
                        verbose_name="Change Reason",
                    ),
                ),
                (
                    "session_name",
                    models.CharField(max_length=100, verbose_name="Session Name"),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("ADMISSION", "Admission Measurements"),
                            ("ANNUAL", "Annual Measurement Drive"),
                            ("CLASS_BASED", "Class-based Measurements"),
                            ("INDIVIDUAL", "Individual Measurement"),
                            ("UNIFORM_ORDER", "Uniform Order Measurements"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Session Type",
                    ),
                ),
                (
                    "session_date",
                    models.DateField(db_index=True, verbose_name="Session Date"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End Time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_students_measured",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Students Measured"
                    ),
                ),
                (
                    "total_measurements_taken",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Measurements Taken"
                    ),
                ),
                (
                    "coordinator_id",
                    models.CharField(
                        blank=True,
                        help_text="User ID of session coordinator",
                        max_length=50,
                        null=True,
                        verbose_name="Coordinator ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_sessions",
                        to="academics.academicsession",
                        verbose_name="Academic Session",
                    ),
                ),
                (
                    "target_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="measurement_sessions",
                        to="academics.class",
                        verbose_name="Target Classes",
                    ),
                ),
                (
                    "target_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="measurement_sessions",
                        to="students.student",
                        verbose_name="Target Students",
                    ),
                ),
            ],
            options={
                "verbose_name": "Measurement Session",
                "verbose_name_plural": "Measurement Sessions",
                "ordering": ["-session_date"],
                "indexes": [
                    models.Index(
                        fields=["session_date", "status"],
                        name="uniforms_me_session_5d8876_idx",
                    ),
                    models.Index(
                        fields=["academic_session"],
                        name="uniforms_me_academi_dabe92_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="measurementtype",
            index=models.Index(
                fields=["category", "is_active"], name="uniforms_me_categor_4b6535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurementtype",
            index=models.Index(fields=["code"], name="uniforms_me_code_9520f5_idx"),
        ),
        migrations.AddIndex(
            model_name="studentmeasurement",
            index=models.Index(
                fields=["student", "measurement_type"],
                name="uniforms_st_student_066c39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentmeasurement",
            index=models.Index(
                fields=["measurement_date"], name="uniforms_st_measure_f3527b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmeasurement",
            index=models.Index(
                fields=["is_current"], name="uniforms_st_is_curr_66b9ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmeasurement",
            index=models.Index(
                fields=["academic_session"], name="uniforms_st_academi_443f9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmeasurement",
            index=models.Index(
                fields=["is_verified"], name="uniforms_st_is_veri_0c8df1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentmeasurement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("student", "measurement_type"),
                name="unique_current_measurement_per_student_type",
            ),
        ),
        migrations.AddIndex(
            model_name="uniformpurchaseorder",
            index=models.Index(
                fields=["po_number"], name="uniforms_un_po_numb_38d6c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformpurchaseorder",
            index=models.Index(
                fields=["order_date"], name="uniforms_un_order_d_10885e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformpurchaseorder",
            index=models.Index(fields=["status"], name="uniforms_un_status_659c10_idx"),
        ),
        migrations.AddIndex(
            model_name="uniformpurchaseorder",
            index=models.Index(
                fields=["fiscal_period"], name="uniforms_un_fiscal__e738b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformsale",
            index=models.Index(
                fields=["sale_number"], name="uniforms_un_sale_nu_e90136_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformsale",
            index=models.Index(
                fields=["student", "sale_date"], name="uniforms_un_student_7b2ea0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformsale",
            index=models.Index(fields=["status"], name="uniforms_un_status_2caa39_idx"),
        ),
        migrations.AddIndex(
            model_name="uniformsale",
            index=models.Index(
                fields=["sale_date"], name="uniforms_un_sale_da_3efe99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformsale",
            index=models.Index(
                fields=["fiscal_period"], name="uniforms_un_fiscal__ec230d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformsale",
            index=models.Index(
                fields=["academic_session"], name="uniforms_un_academi_9f2ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformitem",
            index=models.Index(fields=["code"], name="uniforms_un_code_a8fd2d_idx"),
        ),
        migrations.AddIndex(
            model_name="uniformitem",
            index=models.Index(
                fields=["item_type", "is_active"], name="uniforms_un_item_ty_3f1393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniformitem",
            index=models.Index(fields=["sku"], name="uniforms_un_sku_318992_idx"),
        ),
        migrations.AddIndex(
            model_name="studentuniformsize",
            index=models.Index(
                fields=["student", "uniform_item"],
                name="uniforms_st_student_aa40a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentuniformsize",
            index=models.Index(
                fields=["academic_session"], name="uniforms_st_academi_2d70df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentuniformsize",
            index=models.Index(
                fields=["is_current"], name="uniforms_st_is_curr_1e4230_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentuniformsize",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("student", "uniform_item", "academic_session"),
                name="unique_current_uniform_size_per_student_item_session",
            ),
        ),
        migrations.AddIndex(
            model_name="uniformstock",
            index=models.Index(
                fields=["uniform_item", "size"], name="uniforms_un_uniform_61477b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="uniformstock",
            unique_together={("uniform_item", "size")},
        ),
    ]
