# Generated by Django 5.2 on 2026-04-04 05:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_academicprogress_days_attended_and_more"),
        ("core", "0004_remove_specialaccountmappings_petty_cash_account_and_more"),
        ("fees", "0003_alter_discountpolicy_max_discount_per_student_and_more"),
        ("finance", "0003_remove_expenseline_expense_account_and_more"),
        ("students", "0001_initial"),
        ("uniforms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurementsession",
            name="academic_session",
        ),
        migrations.RemoveField(
            model_name="measurementsession",
            name="target_classes",
        ),
        migrations.RemoveField(
            model_name="measurementsession",
            name="target_students",
        ),
        migrations.RemoveIndex(
            model_name="studentmeasurement",
            name="uniforms_st_is_curr_66b9ad_idx",
        ),
        migrations.RemoveField(
            model_name="measurementtype",
            name="applicable_age_max",
        ),
        migrations.RemoveField(
            model_name="measurementtype",
            name="applicable_age_min",
        ),
        migrations.RemoveField(
            model_name="uniformsize",
            name="max_age",
        ),
        migrations.RemoveField(
            model_name="uniformsize",
            name="min_age",
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Short uppercase identifier used in code (e.g. HEIGHT, CHEST, WAIST). Used by the size recommendation algorithm — do not change after setup.",
                max_length=20,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="display_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=100,
                help_text="Controls the order measurements appear in forms and reports",
                verbose_name="Display Order",
            ),
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="is_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether this measurement must be recorded for every student",
                verbose_name="Is Required",
            ),
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="max_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum reasonable value for this measurement type",
                max_digits=6,
                null=True,
                verbose_name="Maximum Value",
            ),
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="min_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum reasonable value for this measurement type",
                max_digits=6,
                null=True,
                verbose_name="Minimum Value",
            ),
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="unit",
            field=models.ForeignKey(
                help_text="Unit this measurement is recorded in (cm, kg, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="measurement_types",
                to="core.unitofmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
        migrations.AlterField(
            model_name="studentmeasurement",
            name="academic_session",
            field=models.ForeignKey(
                help_text="Term this measurement was recorded in. Used for session-based reporting and scoping size recommendations.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_measurements",
                to="academics.academicsession",
                verbose_name="Academic Session",
            ),
        ),
        migrations.AlterField(
            model_name="studentmeasurement",
            name="is_current",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True for the most recent measurement of this type for this student",
                verbose_name="Is Current",
            ),
        ),
        migrations.AlterField(
            model_name="studentmeasurement",
            name="measurement_context",
            field=models.CharField(
                choices=[
                    ("ADMISSION", "Admission"),
                    ("ANNUAL", "Annual Check"),
                    ("UNIFORM_ORDER", "Uniform Order"),
                    ("HEALTH_CHECK", "Health Check"),
                    ("UPDATE", "Update / Correction"),
                    ("OTHER", "Other"),
                ],
                default="UNIFORM_ORDER",
                max_length=20,
                verbose_name="Context",
            ),
        ),
        migrations.AlterField(
            model_name="studentmeasurement",
            name="measurement_method",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual (Tape Measure)"),
                    ("DIGITAL", "Digital Tool"),
                    ("ESTIMATED", "Estimated"),
                    ("SELF_REPORTED", "Self Reported"),
                    ("PARENT_REPORTED", "Parent Reported"),
                ],
                default="MANUAL",
                max_length=20,
                verbose_name="Method",
            ),
        ),
        migrations.AlterField(
            model_name="studentmeasurement",
            name="measurement_type",
            field=models.ForeignKey(
                help_text="What is being measured (Height, Chest, Waist, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_measurements",
                to="uniforms.measurementtype",
                verbose_name="Measurement Type",
            ),
        ),
        migrations.AlterField(
            model_name="studentmeasurement",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Value",
            ),
        ),
        migrations.AlterField(
            model_name="studentmeasurement",
            name="verified_by_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the user who verified this measurement",
                max_length=50,
                null=True,
                verbose_name="Verified By ID",
            ),
        ),
        migrations.AlterField(
            model_name="studentuniformsize",
            name="alternative_sizes",
            field=models.JSONField(
                blank=True,
                help_text="Ordered list of alternative size PKs (from recommendation algorithm)",
                null=True,
                verbose_name="Alternative Sizes",
            ),
        ),
        migrations.AlterField(
            model_name="studentuniformsize",
            name="growth_allowance",
            field=models.BooleanField(
                default=True,
                help_text="Whether one size up was applied for expected growth",
                verbose_name="Growth Allowance",
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="markup_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Auto-calculated: (selling_price - unit_cost) / unit_cost × 100",
                max_digits=5,
                verbose_name="Markup %",
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="reorder_level",
            field=models.IntegerField(
                default=10,
                help_text="Low-stock warning triggers when stock falls to or below this",
                verbose_name="Reorder Level",
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Selling Price",
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                help_text="Tax rate to apply (uses system default if blank)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uniform_items",
                to="core.taxrate",
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="unit_of_measure",
            field=models.ForeignKey(
                help_text="Unit for inventory tracking (pcs, dozen, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uniform_items",
                to="core.unitofmeasure",
                verbose_name="Unit of Measure",
            ),
        ),
        migrations.AlterField(
            model_name="uniformpurchaseorder",
            name="auto_create_journal_entry",
            field=models.BooleanField(
                default=True, verbose_name="Auto-Create Journal Entry"
            ),
        ),
        migrations.AlterField(
            model_name="uniformpurchaseorder",
            name="fiscal_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uniform_purchase_orders",
                to="core.fiscalperiod",
                verbose_name="Fiscal Period",
            ),
        ),
        migrations.AlterField(
            model_name="uniformpurchaseorder",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Goods-receipt journal entry created when PO status → RECEIVED",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uniform_purchase_orders",
                to="finance.journalentry",
                verbose_name="Journal Entry",
            ),
        ),
        migrations.AlterField(
            model_name="uniformpurchaseorderitem",
            name="currency",
            field=models.CharField(blank=True, max_length=3, verbose_name="Currency"),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="auto_create_invoice",
            field=models.BooleanField(default=True, verbose_name="Auto-Create Invoice"),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="currency",
            field=models.CharField(
                blank=True,
                help_text="Blank = school's primary currency",
                max_length=3,
                verbose_name="Sale Currency",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1.000000"),
                help_text="Rate at time of sale — stored permanently, never recalculated",
                max_digits=12,
                verbose_name="Exchange Rate",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="fee_invoice",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uniform_sale",
                to="fees.feeinvoice",
                verbose_name="Fee Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="return_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GOOD", "Good Condition — Can Resell"),
                    ("FAIR", "Fair Condition — Can Resell with Discount"),
                    ("WORN", "Worn — Cannot Resell"),
                    ("DAMAGED", "Damaged — Cannot Resell"),
                    ("UNUSABLE", "Unusable — Write Off"),
                ],
                max_length=20,
                verbose_name="Return Condition",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsaleitem",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Discount %",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsaleitem",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Tax %",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsaleitem",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost per unit at time of sale (for COGS calculation)",
                max_digits=10,
                verbose_name="Unit Cost",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsize",
            name="max_chest",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Max Chest (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsize",
            name="max_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Max Height (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsize",
            name="max_waist",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Max Waist (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsize",
            name="min_chest",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Min Chest (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsize",
            name="min_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Min Height (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsize",
            name="min_waist",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Min Waist (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="uniformstock",
            name="total_cost_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cached: quantity × unit_cost",
                max_digits=12,
                verbose_name="Total Cost Value",
            ),
        ),
        migrations.AlterField(
            model_name="uniformstock",
            name="total_selling_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cached: quantity × selling_price",
                max_digits=12,
                verbose_name="Total Selling Value",
            ),
        ),
        migrations.AddIndex(
            model_name="studentmeasurement",
            index=models.Index(
                fields=["student", "is_current"], name="uniforms_st_student_ceacf0_idx"
            ),
        ),
        migrations.DeleteModel(
            name="MeasurementSession",
        ),
    ]
