# Generated by Django 5.2 on 2026-03-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uniforms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="uniformsale",
            name="uniforms_un_academi_9f2ae8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="uniformstock",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="uniformsale",
            name="academic_session",
        ),
        migrations.AlterField(
            model_name="uniformstock",
            name="size",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for items that do not require sizing",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_records",
                to="uniforms.uniformsize",
            ),
        ),
        migrations.AddConstraint(
            model_name="uniformstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("size__isnull", False)),
                fields=("uniform_item", "size"),
                name="unique_stock_per_item_and_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="uniformstock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("size__isnull", True)),
                fields=("uniform_item",),
                name="unique_stock_per_unsized_item",
            ),
        ),
    ]
