# Generated by Django 5.2 on 2026-03-08 18:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("finance", "0001_initial"),
        ("uniforms", "0002_remove_uniformsale_uniforms_un_academi_9f2ae8_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="uniformsale",
            name="uniforms_un_cancell_f4dd21_idx",
        ),
        migrations.RemoveIndex(
            model_name="uniformsale",
            name="uniforms_un_returne_2eb073_idx",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="care_instructions",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="material",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="maximum_stock",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="supplier_contact",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="supplier_item_code",
        ),
        migrations.RemoveField(
            model_name="uniformitem",
            name="supplier_name",
        ),
        migrations.AlterField(
            model_name="measurementsession",
            name="coordinator_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Coordinator ID"
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="markup_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Calculated: (selling_price - unit_cost) / unit_cost * 100",
                max_digits=5,
                verbose_name="Markup Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="reorder_level",
            field=models.IntegerField(
                default=10,
                help_text="Triggers low-stock warning when available quantity falls to or below this level",
                verbose_name="Reorder Level",
            ),
        ),
        migrations.AlterField(
            model_name="uniformitem",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Stock Keeping Unit — primary external identifier",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="auto_create_invoice",
            field=models.BooleanField(
                default=True,
                help_text="Automatically create fee invoice when sale is finalised",
                verbose_name="Auto-Create Invoice",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="auto_create_journal_entry",
            field=models.BooleanField(
                default=True, verbose_name="Auto-Create Journal Entry"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="cancellation_journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_uniform_sales",
                to="finance.journalentry",
                verbose_name="Cancellation Journal Entry",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="Cancellation Reason"),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="cancelled",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Cancelled"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="cancelled_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cancelled By ID"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="cancelled_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelled On"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Discount Amount",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="discount_approved_by_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Discount Approved By ID",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="discount_reason",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Discount Reason"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="gross_margin_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="Gross Margin %",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="gross_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Gross Profit",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="internal_notes",
            field=models.TextField(blank=True, verbose_name="Internal Notes"),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Issued At"),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="issued_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Issued By ID"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uniform_sales",
                to="finance.journalentry",
                verbose_name="Journal Entry",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Paid Amount",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="partial_return",
            field=models.BooleanField(default=False, verbose_name="Partial Return"),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uniform_sales",
                to="core.paymentmethod",
                verbose_name="Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Payment Reference"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="return_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GOOD", "Good Condition - Can Resell"),
                    ("FAIR", "Fair Condition - Can Resell with Discount"),
                    ("WORN", "Worn - Cannot Resell"),
                    ("DAMAGED", "Damaged - Cannot Resell"),
                    ("UNUSABLE", "Unusable - Write Off"),
                ],
                max_length=20,
                verbose_name="Return Condition",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="return_date",
            field=models.DateField(
                blank=True,
                help_text="For loaned items — when they should be returned",
                null=True,
                verbose_name="Expected Return Date",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="return_journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="returned_uniform_sales",
                to="finance.journalentry",
                verbose_name="Return Journal Entry",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="return_reason",
            field=models.TextField(blank=True, verbose_name="Return Reason"),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="returned",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Returned"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="returned_by_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Returned By ID"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="returned_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Returned On"
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Subtotal",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Tax Amount",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Total Amount",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsale",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Total Cost (COGS)",
            ),
        ),
        migrations.AlterField(
            model_name="uniformsaleitem",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Total Cost (COGS)"
            ),
        ),
    ]
